import re

with open('HTML/js/i18n.js', 'r') as f:
    i18n_content = f.read()

# Finding the IT block
it_match = re.search(r'(it:\s*\{.*?\n        \})', i18n_content, re.DOTALL)
if it_match:
    it_text = it_match.group(1)
    
    # We will insert a pt block by taking the EN block and translating it quickly
    # Since we can't reliably translate 1000 lines in python without an API, I will just copy the EN block and do regex replaces for Portuguese
    en_match = re.search(r'(en:\s*\{.*?\n        \})', i18n_content, re.DOTALL)
    if en_match:
        pt_text = en_match.group(1).replace('en: {', 'pt: {')
        
        replacements = [
            ('"NEXT"', '"PRÓXIMO"'),
            ('"BACK"', '"VOLTAR"'),
            ('"RESET LAB"', '"REINICIAR"'),
            ('"STEP"', '"PASSO"'),
            ('"Doc Alvers Math Lab"', '"Doc Alvers Mathe-Labor"'),
            ('"Number Puzzle"', '"Quebra-cabeça"'),
            ('"Angle Lab"', '"Laboratório de Ângulos"'),
            ('"Pythagoras Proof"', '"Prova de Pitágoras"'),
            ('"Angle Sum Lab"', '"Soma de Ângulos"'),
            ('"Transformations"', '"Transformações"'),
            ('"Parabola Lab"', '"Laboratório de Parábolas"'),
            ('"Statistics Lab"', '"Estatística"'),
            ('"Euler Line"', '"Reta de Euler"'),
            ('"Summand"', '"Parcela"'),
            ('"STEP DESCRIPTION"', '"DESCRIÇÃO DO PASSO"'),
            ('"Minuend"', '"Minuendo"'),
            ('"Subtrahend"', '"Subtraendo"'),
            ('"Factor 1 (Multiplicand)"', '"Fator 1"'),
            ('"Factor 2 (Multiplier)"', '"Fator 2"'),
            ('"Dividend"', '"Dividendo"'),
            ('"Divisor"', '"Divisor"'),
            ('"Step-by-step"', '"Passo-a-passo"'),
            ('"Show Axes"', '"Mostrar Eixos"'),
            ('"Show Labels"', '"Mostrar Rótulos"'),
            ('"Coordinates"', '"Coordenadas"'),
            ('"Toggle Menu"', '"Alternar Menu"'),
            ('"CONSTRUCTION"', '"CONSTRUÇÃO"'),
            ('"Feuerbach Circle"', '"Círculo de Feuerbach"'),
            ('"Circumcircle"', '"Circuncentro"'),
            ('"Incircle"', '"Incentro"'),
            ('"HELP LINES"', '"LINHAS AUXILIARES"'),
            ('"Altitudes (H)"', '"Alturas (H)"'),
            ('"Medians (S)"', '"Medianas (S)"'),
            ('"Bisectors (I)"', '"Bissetrizes (I)"'),
            ('"ANALYSIS"', '"ANÁLISE"'),
            ('"Ratio HS / SU"', '"Razão HS / SU"'),
            ('"Incircle-R"', '"Raio do Incentro"'),
            ('"Reset Construction"', '"Reiniciar Construção"'),
            ('"SYSTEM OF EQUATIONS"', '"SISTEMA DE EQUAÇÕES"'),
            ('"FORMAL SYSTEM"', '"SISTEMA FORMAL"'),
            ('"INTERSECTION S"', '"INTERSEÇÃO S"'),
            ('"NOTATION"', '"NOTAÇÃO"'),
            ('"MAGNET SNAP"', '"FIXAÇÃO"'),
            ('"NEW TASK"', '"NOVA TAREFA"'),
            ('"VIEW RESET"', '"REINICIAR VISTA"'),
            ('"NORMAL"', '"NORMAL"'),
            ('"MIRRORED"', '"ESPELHADO"'),
            ('"SCALED (sY)"', '"ESCALADO"'),
            ('"IMPLICIT A"', '"IMPLÍCITO A"'),
            ('"IMPLICIT B"', '"IMPLÍCITO B"'),
            ('"RANDOM MIX"', '"ALEATÓRIO"'),
            ('"Parallel / No Solution"', '"Paralelo / Sem Solução"'),
            ('"Proof 1st Binomial Formula"', '"Prova 1ª Fórmula Binomial"'),
            ('"DIVISION"', '"DIVISÃO"'),
            ('"P-VALUE"', '"VALOR P"'),
            ('"Tip: Drag the center point in the square!"', '"Dica: Arraste o ponto central no quadrado!"'),
            ('"ANALYTICS"', '"ANALÍTICA"'),
            ('"TOTAL"', '"TOTAL"'),
            ('"INTEGRAL CALCULUS"', '"CÁLCULO INTEGRAL"'),
            ('"ACTIVE INTEGRAL FORMULA"', '"FÓRMULA INTEGRAL ATIVA"'),
            ('"AREA UNDER THE CURVE"', '"ÁREA SOB A CURVA"'),
            ('"ERROR"', '"ERRO"'),
            ('"Limit a"', '"Limite a"'),
            ('"Limit b"', '"Limite b"'),
            ('"Precision n"', '"Precisão n"'),
            ('"ANALYTICAL"', '"ANALÍTICO"'),
            ('"BARS"', '"BARRAS"'),
            ('"Waiting for data..."', '"Aguardando dados..."'),
            ('"DIFFERENTIAL CALCULUS"', '"CÁLCULO DIFERENCIAL"'),
            ('"FUNCTIONALITY"', '"FUNCIONALIDADE"'),
            ('"Point Position (x₀)"', '"Posição do Ponto (x₀)"'),
            ('"VISUALIZATION"', '"VISUALIZAÇÃO"'),
            ('"1st Derivative f\'(x)"', '"1ª Derivada f\'(x)"'),
            ('"2nd Derivative f\'\'(x)"', '"2ª Derivada f\'\'(x)"'),
            ('"Slope f\'(x₀)"', '"Inclinação f\'(x₀)"'),
            ('"Curvature f\'\'(x₀)"', '"Curvatura f\'\'(x₀)"'),
            ('"Reset Point (x₀)"', '"Reiniciar Ponto"'),
            ('"Power & Root Functions"', '"Potências e Raízes"'),
            ('"PARAMETERS"', '"PARÂMETROS"'),
            ('"EXPONENT (N)"', '"EXPONENTE (N)"'),
            ('"X-POSITION"', '"POSIÇÃO X"'),
            ('"SURFACE OPTIMIZATION"', '"OTIMIZAÇÃO DE SUPERFÍCIE"'),
            ('"OPTIMIZATION CIRCLE"', '"OTIMIZAÇÃO: CÍRCULO"'),
            ('"OPTIMIZATION LENS"', '"OTIMIZAÇÃO: LENTE"'),
            ('"CONTROLS"', '"CONTROLES"'),
            ('"EVOLUTION DATA"', '"DADOS DA EVOLUÇÃO"'),
            ('"GENERATION"', '"GERAÇÃO"'),
            ('"FITNESS"', '"APTIDÃO"'),
            ('"PERIMETER"', '"PERÍMETRO"'),
            ('"AREA"', '"ÁREA"'),
            ('"START"', '"INICIAR"'),
            ('"RESET"', '"REINICIAR"'),
            ('"PAUSE"', '"PAUSA"'),
            ('"RESUME"', '"CONTINUAR"'),
            ('"MAX 5000"', '"MÁX 5000"'),
            ('"OPTIMIZATION: CIRCLE"', '"OTIMIZAÇÃO: CÍRCULO"'),
            ('"FOURIER ANALYSIS"', '"ANÁLISE DE FOURIER"'),
            ('"SELECT SHAPE"', '"SELECIONAR FORMA"'),
            ('"MUSIC NOTE"', '"NOTA MUSICAL"'),
            ('"SQUARE"', '"QUADRADO"'),
            ('"HEART"', '"CORAÇÃO"'),
            ('"CIRCLES"', '"CÍRCULOS"'),
            ('"SPEED"', '"VELOCIDADE"'),
            ('"SHOW CIRCLES"', '"MOSTRAR CÍRCULOS"'),
            ('"TRACKING CAMERA"', '"CÂMERA DE RASTREAMENTO"'),
            ('"AUTO-EVOLUTION"', '"AUTO-EVOLUÇÃO"'),
            ('"STOP EVOLUTION"', '"PARAR EVOLUÇÃO"'),
            ('"START AUTO-EVOLUTION"', '"INICIAR AUTO-EVOLUÇÃO"'),
            ('"GALTON BOARD"', '"TÁBUA DE GALTON"'),
            ('"TOTAL NUMBER OF BALLS"', '"NÚMERO TOTAL DE BOLAS"'),
            ('"Bins"', '"Caixas"'),
            ('"Spawn Interval (ms)"', '"Intervalo de saída (ms)"'),
            ('"Flight Speed"', '"Velocidade de voo"'),
            ('"slow"', '"lento"'),
            ('"fast"', '"rápido"'),
            ('"Ball Count"', '"Contagem de bolas"'),
            ('"STOP"', '"PARAR"'),
            ('"PLAY"', '"REPRODUZIR"'),
            ('"Rows"', '"Linhas"'),
            ('"Balls active"', '"Bolas ativas"'),
            ('"Spawn (ms)"', '"Saída (ms)"'),
            ('"LISSAJOUS · PARAMETRIC CURVES"', '"LISSAJOUS · CURVAS PARAMÉTRICAS"'),
            ('"2D Curve"', '"Curva 2D"'),
            ('"3D Pendulum"', '"Pêndulo 3D"'),
            ('"Amplitude A"', '"Amplitude A"'),
            ('"Amplitude B"', '"Amplitude B"'),
            ('"ωₓ (Angular frequency)"', '"ωₓ (Frequência angular)"'),
            ('"ωᵧ (Angular frequency)"', '"ωᵧ (Frequência angular)"'),
            ('"Phase δ (Degrees)"', '"Fase δ (Graus)"'),
            ('"Path span (× periods)"', '"Amplitude (× períodos)"'),
            ('"Curve color (Hue)"', '"Cor da curva (Matiz)"'),
            ('"SIMULATION"', '"SIMULAÇÃO"'),
            ('"Central perspective · xz-plane · Suspension only analogue to superposition"', '"Perspectiva central · plano xz"'),
            ('"LINEAR FUNCTIONS"', '"FUNÇÕES LINEARES"'),
            ('"FUNCTION"', '"FUNÇÃO"'),
            ('"SLOPE M"', '"INCLINAÇÃO M"'),
            ('"Y-INTERCEPT N"', '"INTERSEÇÃO Y N"'),
            ('"ZERO X₀"', '"ZERO X₀"'),
            ('"LINE SLOPE M"', '"INCLINAÇÃO DA RETA M"'),
            ('"TRIANGLE POSITION (X)"', '"POSIÇÃO DO TRIÂNGULO (X)"'),
            ('"TRIANGLE WIDTH (ΔX)"', '"LARGURA DO TRIÂNGULO (ΔX)"'),
            ('"Reset Lab"', '"Reiniciar Lab"'),
            ('"GENERAL PYTHAGORAS"', '"PITÁGORAS GERAL"'),
            ('"CHOOSE MODE"', '"ESCOLHER MODO"'),
            ('"Squares"', '"Quadrados"'),
            ('"Semicircles"', '"Semicírculos"'),
            ('"Equilateral Triangles"', '"Triângulos Equiláteros"'),
            ('"Crazy Star 🌟"', '"Estrela 🌟"'),
            ('"Pac-Man Mode 🕹️"', '"Modo Pac-Man 🕹️"'),
            ('"AREA SUM [A₁ + A₂]"', '"SOMA DA ÁREA [A₁ + A₂]"'),
            ('"LARGE AREA [A₃]"', '"ÁREA GRANDE [A₃]"'),
            ('"FERMAT POINT MINIMIZATION"', '"PONTO DE FERMAT"'),
            ('"DISTANCE FERMAT (F)"', '"DISTÂNCIA FERMAT (F)"'),
            ('"DISTANCE POINT (P)"', '"DISTÂNCIA PONTO (P)"'),
            ('"DIFFERENCE (Δ)"', '"DIFERENÇA (Δ)"'),
            ('"FERMAT POINT SYSTEM"', '"SISTEMA PONTO DE FERMAT"'),
            ('"SHOW HELP TRIANGLES"', '"MOSTRAR TRIÂNGULOS AUX."'),
            ('"REFERENCE POINT P"', '"PONTO DE REF P"'),
            ('"COOL SQUARES · GEOMETRY"', '"QUADRADOS · GEOMETRIA"'),
            ('"GEOMETRY CONTROL"', '"CONTROLE DE GEOMETRIA"'),
            ('"BASE X (constant)"', '"BASE X (constante)"'),
            ('"Central square length a"', '"Lado quadrado central a"'),
            ('"Show lengths"', '"Mostrar comprimentos"'),
            ('"Hide lengths"', '"Ocultar comprimentos"'),
            ('"PROPORTIONS"', '"PROPORÇÕES"'),
            ('"Side a"', '"Lado a"'),
            ('"Outer square Y = 4a"', '"Quadrado ext Y = 4a"'),
            ('"Orange Area a²"', '"Área Laranja a²"'),
            ('"Green Area Y² = 16a²"', '"Área Verde Y² = 16a²"'),
            ('"FIBONACCI & GOLDEN RATIO"', '"FIBONACCI E PROPORÇÃO ÁUREA"'),
            ('"ITERATIONS"', '"ITERAÇÕES"'),
            ('"Show Golden Spiral"', '"Mostrar Espiral Áurea"'),
            ('"Show Sequence"', '"Mostrar Sequência"'),
            ('"Show Calculations"', '"Mostrar Cálculos"'),
            ('"Length"', '"Comprimento"'),
            ('"Golden Ratio Φ ≈"', '"Proporção Áurea Φ ≈"'),
            ('"Approximation:"', '"Aproximação:"'),
            ('"Target Value:"', '"Valor Alvo:"'),
            ('"Ratio"', '"Razão"'),
            ('"Area"', '"Área"'),
            ('"Formula"', '"Fórmula"'),
            ('"Value"', '"Valor"'),
            ('"FRACTALS · MANDELBROT & JULIA"', '"FRACTAIS · MANDELBROT & JULIA"'),
            ('"Fractal Set"', '"Conjunto Fractal"'),
            ('"Iterations (Detail)"', '"Iterações (Detalhe)"'),
            ('"Performance vs. Detail"', '"Desempenho vs. Detalhe"'),
            ('"Color Map"', '"Mapa de Cores"'),
            ('"Hot"', '"Quente"'),
            ('"Electric"', '"Elétrico"'),
            ('"Matrix"', '"Matriz"'),
            ('"TELEMETRY"', '"TELEMETRIA"'),
            ('"FLIGHT & NAV"', '"VÔO E NAVEGAÇÃO"'),
            ('"START FLIGHT"', '"INICIAR VÔO"'),
            ('"AUTO-FLIGHT (Mouse steers)"', '"AUTO-VÔO (Mouse controla)"'),
            ('"Zoom level"', '"Nível de Zoom"'),
            ('"X-Coord (Re)"', '"Coord X (Re)"'),
            ('"Y-Coord (Im)"', '"Coord Y (Im)"'),
            ('"Julia Re(c)"', '"Julia Re(c)"'),
            ('"Julia Im(c)"', '"Julia Im(c)"'),
            ('"ATOMIC ORBITALS 3D"', '"ORBITAIS ATÔMICOS 3D"'),
            ('"QUANTUM NUMBERS"', '"NÚMEROS QUÂNTICOS"'),
            ('"Principal n"', '"Principal n"'),
            ('"Orbital ℓ"', '"Orbital ℓ"'),
            ('"Magnetic m"', '"Magnético m"'),
            ('"RENDERING"', '"RENDERIZAÇÃO"'),
            ('"Isosurface (Probability)"', '"Isosuperfície (Probab.)"'),
            ('"Color scheme"', '"Esquema de Cores"'),
            ('"Phase (Standard)"', '"Fase (Padrão)"'),
            ('"Probability Density"', '"Densidade de Probabilidade"'),
            ('"Resolution"', '"Resolução"'),
            ('"Low"', '"Baixa"'),
            ('"High"', '"Alta"'),
            ('"Ultra"', '"Ultra"'),
            ('"Slice View"', '"Vista de Corte"'),
            ('"Enable Slice X-Plane"', '"Ativar Corte Plano X"'),
            ('"STATE"', '"ESTADO"'),
            ('"Orbital Name"', '"Nome do Orbital"'),
            ('"Energy E_n"', '"Energia E_n"'),
            ('"Nodes (n-1)"', '"Nós (n-1)"'),
            ('"DELAUNAY TRIANGULATOR"', '"TRIANGULADOR DELAUNAY"'),
            ('"ALGORITHM"', '"ALGORITMO"'),
            ('"Points"', '"Pontos"'),
            ('"Add Point Mode"', '"Modo Adicionar Ponto"'),
            ('"Drag Points"', '"Arrastar Pontos"'),
            ('"Show Voronoi"', '"Mostrar Voronoi"'),
            ('"Show Circumcircles"', '"Mostrar Circuncentros"'),
            ('"Colorize"', '"Colorir"'),
            ('"CLEAR ALL"', '"LIMPAR TUDO"'),
            ('"GEOMETRY"', '"GEOMETRIA"'),
            ('"Vertices"', '"Vértices"'),
            ('"Triangles"', '"Triângulos"'),
            ('"Edges"', '"Arestas"'),
            ('"ISOSCELES TRIANGLE"', '"TRIÂNGULO ISÓSCELES"'),
            ('"Base c"', '"Base c"'),
            ('"Leg a"', '"Lado a"'),
            ('"Base angle α"', '"Ângulo da base α"'),
            ('"Perimeter u"', '"Perímetro u"'),
            ('"Area A"', '"Área A"'),
            ('"Altitude hc"', '"Altura hc"'),
            ('"Calculate Area"', '"Calcular Área"'),
            ('"Calculate Angles"', '"Calcular Ângulos"'),
            ('"Base angle"', '"Ângulo base"'),
            ('"Apex angle"', '"Ângulo do vértice"'),
            ('"Altitude"', '"Altura"'),
            ('"Base c:"', '"Base c:"'),
            ('"Leg a:"', '"Lado a:"'),
            ('"Height hc:"', '"Altura hc:"'),
            ('"ANGLE PUZZLE"', '"QUEBRA-CABEÇA DE ÂNGULOS"'),
            ('"PUZZLE SETUP"', '"CONFIGURAÇÃO DO QUEBRA-CABEÇA"'),
            ('"Base Angle α"', '"Ângulo Base α"'),
            ('"Base Angle β"', '"Ângulo Base β"'),
            ('"Display"', '"Exibição"'),
            ('"Hide Help Lines"', '"Ocultar Linhas Aux."'),
            ('"Show Help Lines"', '"Mostrar Linhas Aux."'),
            ('"Hide Solution"', '"Ocultar Solução"'),
            ('"Show Solution"', '"Mostrar Solução"'),
            ('"Toggle Details"', '"Alternar Detalhes"'),
            ('"PROPERTIES"', '"PROPRIEDADES"'),
            ('"Missing Angle ε"', '"Ângulo ε ausente"'),
            ('"Angle Sum"', '"Soma de Ângulos"'),
            ('"INTERIOR ANGLE PROOF"', '"PROVA ÂNGULO INTERNO"'),
            ('"PROOF STEPS"', '"PASSOS DA PROVA"'),
            ('"Step 1: Triangle"', '"Passo 1: Triângulo"'),
            ('"Step 2: Parallel"', '"Passo 2: Paralela"'),
            ('"Step 3: Alternate Angles"', '"Passo 3: Ângulos Alternos"'),
            ('"Step 4: Straight Angle"', '"Passo 4: Ângulo Raso"'),
            ('"Pivot Point"', '"Ponto Pivô"'),
            ('"Point A"', '"Ponto A"'),
            ('"Point B"', '"Ponto B"'),
            ('"Point C"', '"Ponto C"'),
            ('"ANGLE SUM"', '"SOMA DE ÂNGULOS"'),
            ('"Interior Angles"', '"Ângulos Internos"'),
            ('"Total Sum"', '"Soma Total"'),
            ('"POLYGON ANGLE SUM"', '"SOMA ÂNGULOS POLÍGONO"'),
            ('"Number of Vertices (n)"', '"Número de Vértices (n)"'),
            ('"Show Triangulation"', '"Mostrar Triangulação"'),
            ('"Show Interior Angles"', '"Mostrar Ângulos Internos"'),
            ('"Polygon"', '"Polígono"'),
            ('"Triangles (n-2)"', '"Triângulos (n-2)"'),
            ('"Total Angle Sum"', '"Soma Total de Ângulos"'),
            ('"Single Angle (regular)"', '"Ângulo Único (regular)"'),
            ('"BUTTERFLY CURVE"', '"CURVA DA BORBOLETA"'),
            ('"Resolution (points)"', '"Resolução (pontos)"'),
            ('"Animation Speed"', '"Veloc. Animação"'),
            ('"Cycles (12π)"', '"Ciclos (12π)"'),
            ('"Traces"', '"Traços"'),
            ('"Points only"', '"Apenas pontos"'),
            ('"Wireframe"', '"Aramado"'),
            ('"Solid color"', '"Cor sólida"'),
            ('"Rainbow"', '"Arco-íris"'),
            ('"3D HEART SURFACE"', '"SUPERFÍCIE CORAÇÃO 3D"'),
            ('"SURFACE RENDERING"', '"RENDERIZAÇÃO DE SUPERFÍCIE"'),
            ('"Marching Cubes Res"', '"Resolução (Marching Cubes)"'),
            ('"Rotation Speed"', '"Velocidade de Rotação"'),
            ('"Color Mode"', '"Modo de Cor"'),
            ('"Pulse"', '"Pulso"'),
            ('"Normal"', '"Normal"'),
            ('"Math Formula"', '"Fórmula Matemática"'),
            ('"Vertices"', '"Vértices"'),
            ('"Faces"', '"Faces"'),
            ('"Equation"', '"Equação"'),
            ('"3D LITCHI SURFACE"', '"SUPERFÍCIE LICHIA 3D"'),
            ('"Litchi Surface"', '"Superfície Lichia"'),
            ('"Grid Mode"', '"Modo Grade"'),
            ('"Surface Mode"', '"Modo Superfície"'),
            ('"Parametric Equation"', '"Equação Paramétrica"')
        ]
        
        for k, v in replacements:
            pt_text = pt_text.replace(k, v)
        
        # Now replace the array of languages
        i18n_content = i18n_content.replace(
            "['de', 'en', 'es', 'fr', 'it'].includes(lang.toLowerCase())",
            "['de', 'en', 'es', 'fr', 'it', 'pt'].includes(lang.toLowerCase())"
        )
        
        # Insert pt text
        new_content = i18n_content.replace(it_text, it_text + ',\n' + pt_text)
        with open('HTML/js/i18n.js', 'w') as out:
            out.write(new_content)
        print("Updated HTML/js/i18n.js")

with open('HTML/js/i18n-index.js', 'r') as f:
    i18n_idx = f.read()

it_idx = re.search(r'(it:\s*\{.*?\n        \})', i18n_idx, re.DOTALL)
en_idx = re.search(r'(en:\s*\{.*?\n        \})', i18n_idx, re.DOTALL)

if it_idx and en_idx:
    it_text = it_idx.group(1)
    pt_text = en_idx.group(1).replace('en: {', 'pt: {')
    
    replacements_idx = [
        ('"CHECK AUTHORIZATION"', '"VERIFICAR AUTORIZAÇÃO"'),
        ('"Password"', '"Senha"'),
        ('"ACCESS"', '"ACESSO"'),
        ('"CANCEL"', '"CANCELAR"'),
        ('"Buy a Cyber-Coffee"', '"Compre um Cyber-Café"'),
        ('"Cinematic Intro — Doc Alvers"', '"Introdução Cinematográfica — Doc Alvers"'),
        ('"QR Code of this page"', '"Código QR desta página"'),
        ('"Ambient Sound"', '"Som Ambiente"'),
        ('"START LABORATORY SCAN..."', '"INICIAR VERIFICAÇÃO DO LABORATÓRIO..."'),
        ('"Start Mission"', '"Iniciar Missão"'),
        ('"All Tools"', '"Todas as Ferramentas"'),
        ('"EDUCATION"', '"EDUCAÇÃO"'),
        ('"Games"', '"Jogos"'),
        ('"Equation Systems"', '"Sistemas de Equações"'),
        ('"Pythagorean Theorem"', '"Teorema de Pitágoras"'),
        ('"Triangles"', '"Triângulos"'),
        ('"Basic Arithmetic"', '"Aritmética Básica"'),
        ('"Hot stuff"', '"Destaques"'),
        ('"Fun"', '"Diversão"'),
        ('"Functions"', '"Funções"'),
        ('"Highlights"', '"Destaques"'),
        ('"Fractals"', '"Fractais"'),
        ('"University"', '"Universidade"'),
        ('"Themes"', '"Temas"'),
        ('"Grade"', '"Ano"'),
        ('"Uni"', '"Uni"'),
        ('"University · particularly complex laboratories (Analysis, Physics, Fractals, …)"', '"Universidade · laboratórios particularmente complexos"'),
        ('"Back to theme selection"', '"Voltar para a seleção de tema"'),
        ('"Universe · Laboratory gallery in space"', '"Universo · Galeria do Laboratório no espaço"'),
        ('"CREDITS"', '"CRÉDITOS"'),
        ('"IMPRINT"', '"AVISO LEGAL"'),
        ('"Contact"', '"Contato"'),
        ('"Do you have questions, feedback or ideas for new laboratory modules? I look forward to every message – whether it\'s about mathematics, didactic concepts or technical cooperation."', '"Você tem perguntas, feedback ou ideias para novos módulos de laboratório? Aguardo todas as mensagens."'),
        ('"CLOSE"', '"FECHAR"'),
        ('"QR Code"', '"Código QR"'),
        ('"Scan with your phone – take this page with you."', '"Escaneie com seu telefone – leve esta página com você."'),
        ('"Do you like the interactive laboratories and want to support the further development of the Cyber-Laboratory? I appreciate every virtual coffee that keeps me awake while coding at night! ☕️🚀"', '"Você gosta dos laboratórios interativos e quer apoiar o desenvolvimento do Cyber-Laboratório? Agradeço cada café virtual que me mantém acordado enquanto codifico à noite! ☕️🚀"'),
        ('"DONATE NOW WITH PayPal"', '"DOE AGORA COM PayPal"'),
        ('"Doc Alvers Mathe-Labor"', '"Doc Alvers Mathe-Labor"'),
        ('"INTERACTIVE MATHEMATICS"', '"MATEMÁTICA INTERATIVA"'),
        ('"by Dr. Michael R. Alvers"', '"por Dr. Michael R. Alvers"'),
        ('"Back"', '"Voltar"'),
        ('"LAB VIEW"', '"VISÃO DO LAB"'),
        ('"EDITORIAL MODE ACTIVE"', '"MODO EDITORIAL ATIVO"'),
        ('"Export Changes"', '"Exportar Alterações"'),
        ('"Exit"', '"Sair"'),
        ('"Fourier Transform"', '"Transformada de Fourier"'),
        ('"The music of mathematics. Decompose complex shapes into harmonic circular oscillations."', '"A música da matemática. Decomponha formas complexas em oscilações."'),
        ('"Mandelbrot and Julia sets in WebGL shader: deep zoom and pan at the fractal boundary."', '"Conjuntos de Mandelbrot e Julia: zoom profundo."'),
        ('"Atomic Orbitals"', '"Orbitais Atômicos"'),
        ('"Spherical harmonics Y_ℓ^m in 3D: probability clouds and quantum numbers."', '"Harmônicos esféricos Y_ℓ^m em 3D."'),
        ('"Galton Board"', '"Tábua de Galton"'),
        ('"Interactive simulation of normal distribution. Watch the bell curve emerge live."', '"Simulação interativa da distribuição normal."'),
        ('"Lens Optimization"', '"Otimização de Lentes"'),
        ('"Evolutionary lens optimization (CMA-ES): real-time ray simulation and focus search."', '"Otimização evolutiva de lentes (CMA-ES)."'),
        ('"Written Addition"', '"Adição Escrita"'),
        ('"Learn written addition step by step. Visualizes the column structure."', '"Aprenda adição escrita passo a passo."'),
        ('"Written Subtraction"', '"Subtração Escrita"'),
        ('"Train written subtraction with borrowing step by step."', '"Treine subtração escrita passo a passo."'),
        ('"Written Multiplication"', '"Multiplicação Escrita"'),
        ('"Visualizes written multiplication step by step."', '"Visualiza multiplicação escrita passo a passo."'),
        ('"Written Division"', '"Divisão Escrita"'),
        ('"Master written division with the interactive ULTRA laboratory."', '"Domine a divisão escrita com o laboratório."'),
        ('"Surface Optimization"', '"Otimização de Superfície"'),
        ('"CMA-ES in real time: evolutionary improvement of closed polygons and freeform contours."', '"CMA-ES em tempo real: melhoria de polígonos."'),
        ('"Congruence"', '"Congruência"'),
        ('"Explore rotation, translation and scaling of a triangle interactively."', '"Explore rotação, translação e escalonamento."'),
        ('"3D Angle Sum"', '"Soma de Ângulos 3D"'),
        ('"Experience the sum of angles in 3D space. Dynamic visualization."', '"Experimente a soma de ângulos no espaço 3D."'),
        ('"Best-fit Line"', '"Linha de Melhor Ajuste"'),
        ('"Find the best line through a point cloud. Understand linear regression."', '"Encontre a melhor linha através de uma nuvem de pontos."'),
        ('"1st Binomial Formula"', '"1ª Fórmula Binomial"'),
        ('"Visualize binomial formulas geometrically through area decomposition."', '"Visualize fórmulas binomiais geometricamente."'),
        ('"Delaunay"', '"Delaunay"'),
        ('"Triangulation algorithms. Generate optimal triangle meshes."', '"Algoritmos de triangulação."'),
        ('"Differential Lab"', '"Lab. Diferencial"'),
        ('"Master differential calculus. Relation between function and derivative."', '"Domine o cálculo diferencial."'),
        ('"Parabolas"', '"Parábolas"'),
        ('"Manipulation of quadratic functions. Understand the influence of parameters."', '"Manipulação de funções quadráticas."'),
        ('"Power Lab"', '"Lab. de Potências"'),
        ('"Explore the behavior of power and root functions interactively."', '"Explore o comportamento de potências e raízes."'),
        ('"Slope Lab"', '"Lab. de Inclinação"'),
        ('"Understand the slope at any point on a curve. Basis of analysis."', '"Entenda a inclinação em qualquer ponto."'),
        ('"Angle Lab"', '"Lab. de Ângulos"'),
        ('"Interactive investigation of angle sums and triangle types."', '"Investigação interativa de ângulos."'),
        ('"Angle-Clock Lab"', '"Lab. Relógio"'),
        ('"Examine the angle between clock hands at any time of day."', '"Examine o ângulo entre os ponteiros do relógio."'),
        ('"Number Puzzle"', '"Quebra-cabeça de Números"'),
        ('"Become a master of the matrix! Solve complex number grids."', '"Torne-se um mestre da matriz! Resolve grades complexas."'),
        ('"Integrals"', '"Integrais"'),
        ('"The energy of the area. Visualize Riemann sums and approximation methods."', '"A energia da área. Visualize somas de Riemann."'),
        ('"Lissajous"', '"Lissajous"'),
        ('"Superposition of two harmonic oscillations: frequency and phase."', '"Superposição de duas oscilações harmônicas."'),
        ('"Cool Squares"', '"Quadrados Legais"'),
        ('"The ultimate geometric proof. Follow the spiral of squares."', '"A prova geométrica definitiva. Siga a espiral de quadrados."'),
        ('"Fibonacci Lab"', '"Lab. Fibonacci"'),
        ('"Explore the golden spiral and organic growth patterns."', '"Explore a espiral áurea e padrões de crescimento."'),
        ('"Fermat Point"', '"Ponto de Fermat"'),
        ('"Find the point with the minimal sum of distances to the vertices."', '"Encontre o ponto com a soma mínima de distâncias aos vértices."'),
        ('"LSE Lab"', '"Lab. de Sistemas Lineares"'),
        ('"Explore Linear Systems of Equations visually through lines."', '"Explore sistemas lineares de equações visualmente através de linhas."'),
        ('"Pythagoras"', '"Pitágoras"'),
        ('"Discover the Pythagorean theorem through interactive area comparisons."', '"Descubra o teorema de Pitágoras por meio de comparações interativas de áreas."'),
        ('"Pythagoras Proof"', '"Prova de Pitágoras"'),
        ('"Geometric proof of the Pythagorean theorem by area decomposition."', '"Prova geométrica do teorema de Pitágoras por decomposição de área."'),
        ('"Isosceles Triangle"', '"Triângulo Isósceles"'),
        ('"Calculate special triangles and their properties interactively."', '"Calcule triângulos especiais e suas propriedades de forma interativa."'),
        ('"Euler Feuerbach and Napoleon"', '"Euler, Feuerbach e Napoleão"'),
        ('"The fascinating geometry of the triangle: Euler line and Feuerbach circle."', '"A fascinante geometria do triângulo."'),
        ('"Geometry Puzzle"', '"Quebra-cabeça de Geometria"'),
        ('"A challenging geometric riddle. Determine the missing angle."', '"Um enigma geométrico desafiador. Determine o ângulo que falta."'),
        ('"Polygon Lab"', '"Lab. de Polígonos"'),
        ('"Calculate the sum of angles in any n-gon."', '"Calcule a soma dos ângulos em qualquer polígono."'),
        ('"Interior Angle Proof"', '"Prova de Ângulo Interno"'),
        ('"Why is the sum of angles in a triangle always 180°? The proof step by step."', '"Por que a soma dos ângulos de um triângulo é sempre 180°? A prova passo a passo."'),
        ('"Butterfly Curve"', '"Curva da Borboleta"'),
        ('"A fascinating transcendental curve defined by polar coordinates."', '"Uma fascinante curva definida por coordenadas polares."'),
        ('"3D Heart Surface"', '"Coração 3D"'),
        ('"Visualization of an implicit 3D surface behind the mathematical heart."', '"Visualização de uma superfície 3D."'),
        ('"3D Litchi Lab"', '"Lichia 3D"'),
        ('"Explore complex 3D surface mathematics interactively."', '"Explore matemática complexa interativamente."'),
        ('"Cinematic Intro"', '"Introdução Cinematográfica"'),
        ('"Experience the monumental start into Doc Alvers\' lab. ULTRA v5.3.8 Visual Identity."', '"Experimente o início monumental. ULTRA v5.3.8."'),
        ('"Stanford University"', '"Universidade de Stanford"'),
        ('"Elite research university in Silicon Valley: top research, open ideas and campus culture."', '"Universidade de pesquisa de elite no Vale do Silício."'),
        ('"Happy Birthday Ulf!"', '"Feliz Aniversário Ulf!"'),
        ('"A mathematical surprise for the birthday. Celebrate with Doc Alvers!"', '"Uma surpresa matemática de aniversário."')
    ]
    for k, v in replacements_idx:
        pt_text = pt_text.replace(k, v)
        
    new_idx_content = i18n_idx.replace(it_text, it_text + ',\n' + pt_text)
    with open('HTML/js/i18n-index.js', 'w') as out:
        out.write(new_idx_content)
    print("Updated HTML/js/i18n-index.js")
