// generated by docpad/tools/rallye_web.mjs from docpad/web/esc.js - edit there, not here
// esc.js - the one HTML escape of DOCPAD's modules (it was copied into 16 files; Doc 05.10.2026, refactor 3): & < > " as
// entities, for text and double-quoted attributes. Classic script, loaded before the modules; defines self.CPHtml
// (module.exports in Node, where the modules require it).
//   CPHtml.esc(value) -> string
(function (root) {
  'use strict';
  const MAP = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' };
  const esc = (t) => String(t).replace(/[&<>"]/g, (c) => MAP[c]);
  const CPHtml = { esc };
  if (typeof module === 'object' && module.exports) module.exports = CPHtml;
  else root.CPHtml = CPHtml;
})(typeof self !== 'undefined' ? self : this);
