// generated by docpad/tools/rallye_web.mjs from docpad/web/quiz.js - edit there, not here
// The Quiz menu beside Interactive (Doc 04.10.2026: "Da oben neben Interactive schreibst du bitte rein Quiz ... kleines
// 1x1 ... in bestimmter Zeit ... 20 Aufgaben richtig gelöst ... dann dürfen sie spielen"): a layer over the LCD asks the
// small times table against the clock - whoever has GOAL right before the time runs out may play the Rechen-Rallye
// (rallye.js), which opens only from here. The calculator's keys and the computer's keyboard answer; a wrong answer shows
// the right one and the next task comes, the clock runs on. The calculator itself stays exactly as it was. The look is
// the idle show's (idleshow.css): the display's background, the royal blue ink, the palette, sizes in cqw of #calc.
//   const q = CPQuiz.create({ screen, tex, lang: () => 'de', sound: () => bool })   q.open('1x1')  q.key(id)  q.isOpen()
// DOM-free parts (nextTask) also in Node for the tests.
(function (root) {
  'use strict';
  // 20 right in two minutes - the big times table gets three (Doc 04.10.2026: "da müssten wir dann mehr Zeit geben")
  const GOAL = 20, TIME = 120, TIMES = { big: 180 };
  const timeOf = kind => TIMES[kind] || TIME;
  const TEXT = {
    de: { tag: { mul: 'Kleines 1⋅1', div: 'Kleines 1÷1', big: 'Großes 1⋅1', sq: 'Quadratzahlen', sqrt: 'Quadratwurzeln' },
      intro: min => GOAL + ' Aufgaben richtig in ' + min + ' Minuten – dann wartet die Rechen-Rallye!',
      how: 'Tippe die Lösung mit den Zifferntasten. Falsch? Dann siehst du die richtige Lösung und die nächste Aufgabe kommt – die Uhr läuft weiter.',
      go: 'Los', end: 'Ende', again: 'Nochmal', play: 'Rechen-Rallye!', won: 'Geschafft!', lost: 'Zeit um!',
      wonIn: (n, t) => n + ' richtig in ' + t, errors: n => n === 0 ? 'ohne Fehler' : n === 1 ? '1 Fehler' : n + ' Fehler',
      // time up: how many right and wrong, and how many were missing to the goal - "18 von 20 richtig" with "12 Fehler" read
      // as twenty tasks, though there were thirty (Doc 04.10.2026: "da stimmt was nie. Nach Adam Ries")
      tally: (r, w) => r + ' richtig, ' + w + ' falsch', missing: (g, m) => g + ' richtige waren das Ziel – ' + (m === 1 ? '1 hat' : m + ' haben') + ' gefehlt.',
      left: 'Sekunden' },
    en: { tag: { mul: 'Times tables', div: 'Division tables', big: 'Big times tables', sq: 'Square numbers', sqrt: 'Square roots' },
      intro: min => GOAL + ' right in ' + min + ' minutes – then the Math Rally is yours!',
      how: 'Type the answer with the number keys. Wrong? You see the right answer and the next task comes – the clock runs on.',
      go: 'Go', end: 'End', again: 'Again', play: 'Math Rally!', won: 'Well done!', lost: 'Time is up!',
      wonIn: (n, t) => n + ' right in ' + t, errors: n => n === 0 ? 'no mistakes' : n === 1 ? '1 mistake' : n + ' mistakes',
      tally: (r, w) => r + ' right, ' + w + ' wrong', missing: (g, m) => g + ' right was the goal – ' + m + ' ' + (m === 1 ? 'was' : 'were') + ' missing.',
      left: 'seconds' }
  };

  // The next task: the small times table (mul: a · b), the small division table (div: a·b ÷ a, Doc 04.10.2026: "das kleine
  // Eins durch Eins ... als zweiten") - both factors 2 … 10 (1 · n is no task), a·b and b·a counting as one -, the square
  // numbers (sq: n²) and the square roots (sqrt: √n², Doc 04.10.2026: "noch zwei Quizze ... Wurzel ... Quadrat") for n
  // 2 … 12 ("erstmal nur bis zwölf" - to 20 would be a second level), the big times table (big: 11 … 20 times 2 … 9, either
  // way round, "das große Einmaleins ... als extra Quiz"); never a task of the last six again.
  // { a, b, r, op }: r = a · b, a ÷ b, a², √a
  const OPS = ['mul', 'div', 'big', 'sq', 'sqrt'];
  function nextTask(recent, rng, op) {
    rng = rng || Math.random;
    op = OPS.includes(op) ? op : 'mul';
    for (let tries = 0; ; tries++) {
      let t, k;
      if (op === 'sq' || op === 'sqrt') {
        const n = 2 + Math.floor(rng() * 11);
        k = op + n;
        t = op === 'sq' ? { a: n, b: 2, r: n * n, op } : { a: n * n, b: 2, r: n, op };
      } else if (op === 'big') {
        const x = 11 + Math.floor(rng() * 10), y = 2 + Math.floor(rng() * 8);
        k = 'b' + x + 'x' + y;
        t = rng() < .5 ? { a: x, b: y, r: x * y, op } : { a: y, b: x, r: x * y, op };
      } else {
        const x = 2 + Math.floor(rng() * 9), y = 2 + Math.floor(rng() * 9);
        k = op === 'div' ? 'd' + x + ':' + y : 'm' + Math.min(x, y) + 'x' + Math.max(x, y);
        t = op === 'div' ? { a: x * y, b: x, r: y, op } : { a: x, b: y, r: x * y, op };
      }
      if (!recent.includes(k) || tries > 50) {
        recent.push(k);
        if (recent.length > 6) recent.shift();
        return t;
      }
    }
  }
  // a task's operator as on the calculator: ÷ for division; times a dot in German, × in English (Doc 04.10.2026: "das
  // geteilt durch Zeichen, so wie auf dem Taschenrechner ... beim Eins X eins, das ist die englische Schreibweise")
  // ⋅ U+22C5 is the dot of \\cdot (fonts.css); squares and roots show ² and √ (the high-score list's column)
  const opText = (t, de) => ({ div: '÷', sq: '²', sqrt: '√' }[t.op] || (de ? '⋅' : '×'));
  // a task as plain text, for the game's bridges: 7 ⋅ 8, 56 ÷ 8, 13², √169
  const taskText = (t, de) => t.op === 'sq' ? t.a + '²' : t.op === 'sqrt' ? '√' + t.a : t.a + ' ' + opText(t, de) + ' ' + t.b;
  // a task as TeX, the answer left out or given: 7 · 8 = …, 56 ÷ 8 = …, 13² = …, √169 = …
  const taskTex = (t, r, de) => (t.op === 'sq' ? t.a + '^{2}' : t.op === 'sqrt' ? '\\sqrt{' + t.a + '}' :
    t.a + (t.op === 'div' ? '\\div ' : de ? '\\cdot ' : '\\times ') + t.b) + ' =' + (r === undefined ? '' : ' ' + r);
  const mmss = s => Math.floor(s / 60) + ':' + String(Math.floor(s % 60)).padStart(2, '0');

  // rally: further options for the game (rallye.js create), e.g. { startLevel } from rallye.html
  function create({ screen, tex, lang, sound, rally }) {
    const body = document.body;
    let layer = null, phase = '', task = null, input = '', right = 0, wrong = 0, t0 = 0, clock = 0, lock = false, recent = [], kind = 'mul';
    let game = null, actx = null;
    const L = () => TEXT[lang() === 'de' ? 'de' : 'en'];
    const esc = s => String(s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
    const pill = (k, t, cls) => '<span class="qz-pill' + (cls ? ' ' + cls : '') + '"><b>' + k + '</b>' + esc(t) + '</span>';

    // a short tone (only with the key click switched on: ⚙ ▸ sound, off by default - quiet in class)
    function tone(f, ms, type) {
      if (!sound()) return;
      try {
        actx = actx || new (window.AudioContext || window.webkitAudioContext)();
        const o = actx.createOscillator(), g = actx.createGain(), t = actx.currentTime;
        o.type = type || 'sine'; o.frequency.value = f;
        g.gain.setValueAtTime(.18, t); g.gain.exponentialRampToValueAtTime(.001, t + ms / 1000);
        o.connect(g); g.connect(actx.destination); o.start(t); o.stop(t + ms / 1000 + .02);
      } catch (e) { /* no sound - no matter */ }
    }

    function open(which) {
      if (layer) return;
      kind = { '1d1': 'div', div: 'div', big: 'big', sq: 'sq', sqrt: 'sqrt', mix: 'mix' }[which] || 'mul';
      layer = document.createElement('div');
      layer.className = 'qz-layer';
      layer.addEventListener('pointerdown', ev => {
        ev.stopPropagation();                              // the calculator below gets nothing (the game's canvas took its own)
        if (ev.target.closest('[data-qz="close"]')) close();
      });
      screen.appendChild(layer);
      body.classList.add('qz-on');                         // keeps the idle show away (idleshow.js BUSY)
      intro();
      requestAnimationFrame(() => layer && layer.classList.add('on'));
    }
    function close() {
      clearInterval(clock); clock = 0;
      if (game) { game.stop(); game = null; }
      if (layer) { const l = layer; l.classList.remove('on'); setTimeout(() => l.remove(), 300); }
      layer = null; phase = '';
      body.classList.remove('qz-on');
    }
    function frame(inner) {
      layer.innerHTML = '<span class="qz-x" data-qz="close" title="' + L().end + '">✕</span>' +
        '<span class="qz-tag">' + esc(L().tag[kind] || L().tag.mul) + '</span><div class="qz-body">' + inner + '</div>';
    }

    function intro() {
      phase = 'intro';
      frame('<div class="qz-big">' + esc(L().intro(timeOf(kind) / 60)) + '</div><div class="qz-how">' + esc(L().how) + '</div>' +
        '<div class="qz-pills">' + pill('EXE', L().go, 'go') + pill('Clear', L().end) + '</div>');
    }
    function start() {
      phase = 'run'; right = 0; wrong = 0; input = ''; lock = false; recent = [];
      task = nextTask(recent, null, kind);
      t0 = performance.now();
      frame('<div class="qz-dots">' + '<i></i>'.repeat(GOAL) + '</div>' +
        '<div class="qz-task"><span class="qz-q"></span><span class="qz-a"></span></div><div class="qz-fb"></div>' +
        '<div class="qz-ring"><svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="44"/><circle class="arc" cx="50" cy="50" r="44"/></svg>' +
        '<b></b><span>' + esc(L().left) + '</span></div>');
      showTask();
      clearInterval(clock);
      clock = setInterval(tickClock, 100);
      tickClock();
    }
    const left = () => Math.max(0, timeOf(kind) - (performance.now() - t0) / 1000);
    function tickClock() {
      if (phase !== 'run') return;
      const s = left(), ring = layer.querySelector('.qz-ring');
      ring.querySelector('b').textContent = Math.ceil(s);
      ring.querySelector('.arc').style.strokeDashoffset = 276.5 * (1 - s / timeOf(kind));
      ring.classList.toggle('late', s <= 15);
      if (s <= 0) finish(false);
    }
    function showTask() {
      layer.querySelector('.qz-q').innerHTML = tex(taskTex(task, undefined, lang() === 'de'));
      showInput();
    }
    function showInput() {
      layer.querySelector('.qz-a').innerHTML = input ? tex(input) : '<i class="qz-caret"></i>';
    }
    function submit() {
      if (!input || lock) return;
      const card = layer.querySelector('.qz-task'), fb = layer.querySelector('.qz-fb'), ok = +input === task.r;
      lock = true;
      if (ok) {
        right++;
        layer.querySelectorAll('.qz-dots i')[right - 1].className = 'on';
        card.classList.add('ok'); tone(880, 120);
      } else {
        wrong++;
        card.classList.add('bad'); tone(196, 220, 'triangle');
        fb.innerHTML = tex(taskTex(task, task.r, lang() === 'de'));
      }
      setTimeout(() => {
        if (phase !== 'run') return;
        card.classList.remove('ok', 'bad'); fb.innerHTML = '';
        if (right >= GOAL) { finish(true); return; }
        task = nextTask(recent, null, kind); input = ''; lock = false;
        showTask();
      }, ok ? 260 : 1300);
    }
    function finish(won) {
      clearInterval(clock); clock = 0;
      const used = timeOf(kind) - left();
      phase = won ? 'won' : 'lost';
      if (won) { tone(660, 120); setTimeout(() => tone(990, 260), 130); }
      frame('<div class="qz-head ' + phase + '">' + esc(won ? L().won : L().lost) + '</div>' +
        '<div class="qz-big">' + esc(won ? L().wonIn(GOAL, mmss(used)) : L().tally(right, wrong)) + '</div>' +
        '<div class="qz-how">' + esc(won ? L().errors(wrong) : L().missing(GOAL, GOAL - right)) + '</div>' +
        '<div class="qz-pills">' + (won ? pill('EXE', L().play, 'go') : pill('EXE', L().again, 'go')) + pill('Clear', L().end) + '</div>');
    }
    // Vorführmodus (Doc 04.10.2026: "dass ich nicht jedes Mal erst die ganze zwanzig Aufgaben lösen muss"): the game at
    // once, its gates mixing 1×1 and 1:1 - only by Option+R, on no menu, so the class still earns it
    function show() {
      if (!layer) { open('mix'); kind = 'mix'; }
      clearInterval(clock); clock = 0;
      if (game) { game.stop(); game = null; }
      play();
    }
    function play() {
      phase = 'game';
      layer.innerHTML = '<span class="qz-x" data-qz="close" title="' + L().end + '">✕</span><canvas class="rl-canvas"></canvas>';
      game = root.CPRallye.create(Object.assign({ canvas: layer.querySelector('canvas'), lang, tone, onExit: close, op: kind }, rally || {}));
      game.start();
      window.CPRallyeNow = game;                           // for testing from the console: CPRallyeNow.info()
    }

    // a key of the calculator (act in docpad.html) or of the computer: while the layer is open it takes them all
    function key(id) {
      if (!layer) return false;
      if (id === 'ESC') { close(); return true; }
      if (phase === 'game') { game.key(id); return true; }
      if (id === 'CLEAR') {
        if (phase === 'run' && input && !lock) { input = ''; showInput(); } else close();
        return true;
      }
      if (id === 'EXE') {
        if (phase === 'intro' || phase === 'lost') start();
        else if (phase === 'won') play();
        else submit();
        return true;
      }
      if (phase !== 'run' || lock) return true;
      if (/^[0-9]$/.test(id) && input.length < 3) {
        input += id; showInput();
        if (input.length >= String(task.r).length) submit();   // as many digits as the answer has: checked at once
      } else if (id === 'BS' && input) { input = input.slice(0, -1); showInput(); }
      return true;
    }
    // the computer's keyboard, before the calculator's own handler (docpad.html: d = Demo, letters = commands ...)
    const KB = { Enter: 'EXE', ' ': 'EXE', Backspace: 'BS', Delete: 'CLEAR', Escape: 'ESC',
      ArrowLeft: 'LEFT', ArrowRight: 'RIGHT', ArrowUp: 'UP', ArrowDown: 'DOWN' };
    addEventListener('keydown', ev => {
      if (ev.altKey && !ev.metaKey && !ev.ctrlKey && ev.code === 'KeyR') {   // Option+R: the Vorführmodus (by position: ® on a Mac)
        ev.preventDefault(); ev.stopImmediatePropagation();
        if (!screen.classList.contains('off')) show();             // not with the calculator switched off
        return;
      }
      if (!layer) return;
      const field = ev.target && ev.target.closest && ev.target.closest('.qz-layer input');
      if (field) {                                         // the game's nickname field: letters go into it, never to the calculator
        ev.stopImmediatePropagation();
        if (ev.key === 'Enter') { ev.preventDefault(); key('EXE'); }
        else if (ev.key === 'Escape') { ev.preventDefault(); field.blur(); }
        return;
      }
      if (ev.metaKey || ev.ctrlKey || ev.altKey) return;
      ev.preventDefault(); ev.stopImmediatePropagation();
      const id = KB[ev.key] || (/^[0-9]$/.test(ev.key) ? ev.key : '');
      // in the game ▲ ▼ held down are a pedal (Doc 04.10.2026: "Arrow Up, Arrow Down auf der Tastatur ... tut nichts")
      if (phase === 'game' && (id === 'UP' || id === 'DOWN')) { if (!ev.repeat) { key(id); game.hold(id, true); } return; }
      if (id && !(ev.repeat && phase !== 'game')) key(id);
    }, true);
    addEventListener('keyup', ev => {
      const id = KB[ev.key];
      if (layer && phase === 'game' && game && (id === 'UP' || id === 'DOWN')) game.hold(id, false);
    }, true);
    addEventListener('blur', () => { if (game) { game.hold('UP', false); game.hold('DOWN', false); } });

    return { open, close, key, show, isOpen: () => !!layer };
  }

  const CPQuiz = { create, nextTask, taskTex, taskText, opText, OPS, GOAL, TIME, timeOf };
  if (typeof module === 'object' && module.exports) module.exports = CPQuiz;
  else root.CPQuiz = CPQuiz;
})(typeof self !== 'undefined' ? self : this);
