// generated by docpad/tools/rallye_web.mjs from docpad/web/rallye.js - edit there, not here
// The Rechen-Rallye (Doc 04.10.2026: "ein ganz einfaches Spiel ... auf einer Straße navigieren mit den Pfeiltasten vom
// Casio", then "könnten wir das Spiel vielleicht in 3D machen? Dass ... die Straße so gebogen kommt?"), the reward of the
// Quiz menu (quiz.js) - it opens only from there, or by Option+R for showing it. Pseudo-3D as in the arcade racers of the
// eighties: the road is a chain of short segments projected towards the horizon; shifting their centres bends it into
// curves, raising them makes hills (the technique of Lou's Pseudo 3D Page and Jake Gordon's "How to build a racing game";
// the code is our own). The car keeps its lane in the curves - easy for the class: ◀ ▶ change lanes (the calculator's
// cursor pad, the arrow keys, a swipe or a tap at the side), ▲ ▼ give gas and brake. Traffic and cones come up, stars are
// to be picked up, and every few seconds a sign bridge asks a task - 1·1, 1÷1 or both - with an answer board over each
// lane: the right lane brings a bonus, a wrong one costs a life. Three lives, faster and faster. The palette: λ orange
// car, Υ red and ink blue traffic, φ green verges, red and white kerbs; the numbers in the LaTeX font (fonts.css).
//   const g = CPRallye.create({ canvas, lang: () => 'de', tone(f, ms, type), onExit, op: 'mul' | 'div' | 'mix' })
//   g.start()  g.key(id)  g.stop()          DOM-free parts (gateAnswers, obstacleRow, buildTrack) also in Node for the tests.
(function (root) {
  'use strict';
  const LANES = 3, LANE_X = [-2 / 3, 0, 2 / 3];               // lane centres in road half-widths (the road is -1 … 1)
  // the world: SEG world units per segment, a kerb stripe every RUMBLE segments, the road's half width, the camera
  // CAMH above it with a 100° field of view, DRAW segments to the horizon; the player stands PZ in front of the camera
  const SEG = 200, RUMBLE = 3, ROADW = 1000, CAMH = 700, DEPTH = 1 / Math.tan(50 * Math.PI / 180), DRAW = 150, PZ = CAMH * DEPTH;
  const CARW = 420;                                           // a car's width in world units (a lane is 667)
  const C = { sky: 'rgb(118, 168, 222)', haze: 'rgb(214, 230, 242)', fog: 'rgb(214, 230, 242)', mount: 'rgb(132, 150, 190)',
    hill: 'rgb(98, 136, 52)', grass: 'rgb(121, 158, 49)', road: '#41454d',
    line: '#f7f8f3', kerb: 'rgb(176, 36, 24)', car: 'rgb(245, 194, 66)', red: 'rgb(176, 36, 24)', ink: 'rgb(25, 52, 130)',
    paper: '#f7f8f3', glass: 'rgba(16, 24, 44, .9)', grey: '#7a8294', cone: 'rgb(232, 98, 34)', tree: 'rgb(70, 104, 30)',
    trunk: 'rgb(96, 70, 44)', green: 'rgb(121, 158, 49)' };
  const TEXT = {
    de: { title: 'Rechen-Rallye', lanes: 'Im Rennen: ◀ ▶ Spur', gas: '▲ Gas   ▼ Bremse', gate: 'Fahr durch die richtige Lösung!',
      go: 'Los', over: 'Game over', again: 'Nochmal', end: 'Ende', points: 'Punkte', best: 'Rekord', record: 'Neuer Rekord!',
      right: 'Richtig!', level: n => 'Level ' + n, nitro: 'NITRO!',
      board: 'Hitliste', name: 'Dein Spitzname', note: 'Bitte keinen echten Namen', save: 'Eintragen', loading: 'Hitliste lädt …',
      saved: n => 'Eingetragen – Platz ' + n + '!', offline: 'Hitliste gerade nicht erreichbar', empty: 'Noch leer – sei die oder der Erste!',
      demo: 'Vorführung: hier wird nichts eingetragen', pick: 'Dein Auto  ◀ ▶', levels: 'Vorführung: 1 – 9 springt im Rennen ins Level' },
    en: { title: 'Math Rally', lanes: 'In the race: ◀ ▶ lanes', gas: '▲ gas   ▼ brake', gate: 'Drive through the right answer!',
      go: 'Go', over: 'Game over', again: 'Again', end: 'End', points: 'Points', best: 'Best', record: 'New record!',
      right: 'Right!', level: n => 'Level ' + n, nitro: 'NITRO!',
      board: 'High scores', name: 'Your nickname', note: 'Please no real names', save: 'Enter', loading: 'Loading high scores …',
      saved: n => 'Entered – place ' + n + '!', offline: 'High scores out of reach right now', empty: 'Still empty – be the first!',
      demo: 'Show mode: nothing is entered here', pick: 'Your car  ◀ ▶', levels: 'Show mode: 1 – 9 jump to a level in the race' }
  };
  // the high-score list (Doc 04.10.2026: "ein Spieler gibt sich einen Namen, und wir machen dann eine Hitliste"): the
  // edge function rallye-scores (forloop/supabase/functions) - it checks the nickname and the score and keeps the top ten
  const SCORES = 'https://fyfhxzyymmurlaenmzse.supabase.co/functions/v1/rallye-scores', TOP = 10;
  async function scores(body) {
    const r = await fetch(SCORES, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
    const j = await r.json().catch(() => ({}));
    if (!r.ok && r.status !== 409) throw new Error(j.error || 'HTTP ' + r.status);
    return Object.assign(j, { status: r.status });
  }

  // The pictures (Doc 04.10.2026: "fotorealistischer ... echte Autos", then "Fantasie Autos, die eben auch cool aussehen ...
  // schön Bergen und echten Bäumen"): generated with Gemini's image model as original designs - no real model, no brand,
  // no logo -, cut free from a magenta background and saved as WebP in web/rallye/. Loaded once; until a picture is there
  // (or without it) the game draws its own shapes as before.
  const ART = { cars: ['car_orange', 'car_red', 'car_green'], traffic: ['tr_blue', 'tr_silver', 'tr_white', 'tr_red'],
    trees: ['tree_oak', 'tree_fir', 'tree_birch'], bush: 'bush', alps: 'alps', dusk: 'alps_sunset',
    animals: ['cow', 'horse', 'sheep'], elephant: 'elephant', houses: ['house', 'barn'] };
  // how wide each stands, in world units (a car is 420): a cow, a horse, a sheep, now and then an elephant, houses far off
  const WIDTH = { cow: 600, horse: 560, sheep: 340, elephant: 1500, house: 1700, barn: 1600 };
  // the land beside the road (Doc 04.10.2026: "den grünen Rasen nicht ganz so gleichmäßig"): meadows of their own green,
  // now and then a yellowish field or a lake - long stretches each, so nothing flickers
  const MEADOW = ['rgb(121, 158, 49)', 'rgb(106, 146, 46)', 'rgb(132, 166, 60)', 'rgb(114, 150, 62)', 'rgb(128, 152, 52)'];
  const CROP = 'rgb(178, 170, 86)', VERGE = 'rgb(104, 140, 42)', WATER = 'rgb(74, 124, 166)', GLINT = 'rgb(132, 176, 210)';
  const IMG = {};
  const pic = name => {
    if (!IMG[name] && typeof Image !== 'undefined') { const im = new Image(); im.decoding = 'async'; im.src = 'rallye/' + name + '.webp'; IMG[name] = im; }
    const im = IMG[name];
    return im && im.complete && im.naturalWidth ? im : null;
  };

  function shuffle(a, rng) {
    for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(rng() * (i + 1)); [a[i], a[j]] = [a[j], a[i]]; }
    return a;
  }
  // The gate's three answers: the right one and two near misses, shuffled - the slips that happen: for 1·1 a factor too
  // many or too few, one or ten off; for 1÷1 one or two off and the divisor itself; for n² the neighbours' squares, n·(n±1)
  // and 2n (doubled instead of squared); for √ the neighbours and half the radicand
  function gateAnswers(t, rng) {
    rng = rng || Math.random;
    const r = t.r, n = t.op === 'sq' ? t.a : r;
    const pool = t.op === 'div' ? [r + 1, r - 1, r + 2, r - 2, t.b]
      : t.op === 'sq' ? [(n - 1) * (n - 1), (n + 1) * (n + 1), n * (n - 1), n * (n + 1), 2 * n, r + 10, r - 10]
      : t.op === 'sqrt' ? [r + 1, r - 1, r + 2, r - 2].concat(t.a % 2 ? [] : [t.a / 2])
      : [r + t.a, r - t.a, r + t.b, r - t.b, r + 1, r - 1, r + 10, r - 10];
    const near = shuffle([...new Set(pool)].filter(v => v > 0 && v !== r), rng);
    return shuffle([r, near[0], near[1]], rng);
  }
  // A row of obstacles: one or two lanes blocked (car or cone), never all three; a star in a free lane now and then
  function obstacleRow(rng) {
    rng = rng || Math.random;
    const lanes = shuffle([0, 1, 2], rng), n = rng() < .35 ? 2 : 1;
    const blocked = lanes.slice(0, n).map(l => ({ lane: l, kind: rng() < .6 ? 'car' : 'cone', color: rng() < .5 ? C.red : C.ink }));
    return { blocked, star: rng() < .45 ? lanes[n] : -1 };
  }

  // The track: straights, curves, hills, S-bends and both together, back to the start's height so it loops; trees,
  // bushes and signs with the signs of arithmetic at the side
  function buildTrack(rng) {
    rng = rng || Math.random;
    const segs = [];
    const lastY = () => segs.length ? segs[segs.length - 1].p2.world.y : 0;
    const add = (curve, y) => {
      const n = segs.length;
      segs.push({ index: n, curve, dark: Math.floor(n / RUMBLE) % 2 === 1, sprites: [],
        p1: { world: { y: lastY(), z: n * SEG } }, p2: { world: { y, z: (n + 1) * SEG } } });
    };
    const easeIn = (a, b, p) => a + (b - a) * p * p, easeInOut = (a, b, p) => a + (b - a) * (-Math.cos(p * Math.PI) / 2 + .5);
    // hill: the height it climbs (or drops) in segments; a segment's height is where it ends, so the last one reaches y1
    function road(enter, hold, leave, curve, hill) {
      const y0 = lastY(), y1 = y0 + hill * SEG, n = enter + hold + leave;
      for (let i = 0; i < enter; i++) add(easeIn(0, curve, i / enter), easeInOut(y0, y1, (i + 1) / n));
      for (let i = 0; i < hold; i++) add(curve, easeInOut(y0, y1, (enter + i + 1) / n));
      for (let i = 0; i < leave; i++) add(easeInOut(curve, 0, i / leave), easeInOut(y0, y1, (enter + hold + i + 1) / n));
    }
    road(10, 40, 10, 0, 0);
    while (segs.length < 1600) {
      const r = rng(), len = 20 + Math.floor(rng() * 40), c = (1 + rng() * 2.4) * (rng() < .5 ? -1 : 1);
      const up = lastY() > 1200 ? -1 : lastY() < -1200 ? 1 : (rng() < .5 ? -1 : 1), h = up * (2 + rng() * 4);
      if (r < .18) road(10, len, 10, 0, 0);
      else if (r < .45) road(15, len, 15, c, 0);
      else if (r < .65) road(15, len, 15, 0, h);
      else if (r < .88) road(15, len, 15, c, h);
      else { road(12, 18, 12, c, 0); road(12, 18, 12, -c, 0); }   // an S-bend
    }
    road(20, 20, 20, 0, -lastY() / SEG);                    // back to the start's height, then straight into the loop
    road(10, 40, 10, 0, 0);
    for (const side of ['L', 'R']) {                       // the fields, each side on its own
      for (let i = 0; i < segs.length;) {
        const len = 30 + Math.floor(rng() * 60), r = rng();
        const kind = i > 80 && len > 45 && r < .1 ? 'lake' : r < .2 ? 'crop' : 'meadow', shade = Math.floor(rng() * MEADOW.length);
        for (let j = i; j < Math.min(segs.length, i + len); j++) segs[j][side] = { kind, shade };
        i += len;
      }
    }
    const land = (s, x) => (x < 0 ? s.L : s.R).kind;       // what lies at that side: meadow, crop or lake
    const put = (s, sp) => { if (land(s, sp.x) !== 'lake' || Math.abs(sp.x) < 1.55) s.sprites.push(sp); };   // nothing stands on the water
    const side = () => (rng() < .5 ? -1 : 1);
    segs.forEach((s, i) => {
      if (i % 7 === 0) put(s, { kind: 'tree', x: -(1.5 + rng() * 1.6), k: .8 + rng() * .5, v: Math.floor(rng() * 3) });
      if (i % 7 === 3) put(s, { kind: 'tree', x: 1.5 + rng() * 1.6, k: .8 + rng() * .5, v: Math.floor(rng() * 3) });
      if (i % 11 === 5) put(s, { kind: 'bush', x: side() * (1.3 + rng() * .4), k: .8 + rng() * .4 });
      // a little herd on a meadow: cows, horses or sheep, facing either way
      if (i % 29 === 14 && rng() < .7) {
        const x0 = side() * (2.1 + rng() * 1.6), kind = ART.animals[Math.floor(rng() * 3)], n = 1 + Math.floor(rng() * 3);
        for (let k = 0; k < n; k++) {                       // each one on a meadow of its own segment (a lake may begin)
          const t = segs[(i + k * 2) % segs.length], x = x0 + Math.sign(x0) * k * .45;
          if (land(t, x) === 'meadow') t.sprites.push({ kind: 'pic', pic: kind, x, k: .9 + rng() * .2, flip: rng() < .5 });
        }
      }
      if (i % 233 === 120 && rng() < .35) {                // and, for fun, an elephant - about two a lap
        const x0 = side() * (2.8 + rng());
        if (land(s, x0) !== 'lake') s.sprites.push({ kind: 'pic', pic: 'elephant', x: x0, k: 1, flip: rng() < .5 });
      }
      if (i % 89 === 44) {                                 // a farm far off
        const x0 = side() * (4 + rng() * 2.5);
        if (land(s, x0) !== 'lake') s.sprites.push({ kind: 'pic', pic: ART.houses[Math.floor(rng() * 2)], x: x0, k: 1, flip: rng() < .5 });
      }
    });
    return segs;
  }
  // a far range of mountains and nearer hills, as heights across one turn of the horizon
  const ridge = (rng, n, lo, hi) => Array.from({ length: n }, () => lo + rng() * (hi - lo));

  // startLevel: the level a show-mode ride starts in (rallye.html?level=5)
  function create({ canvas, lang, tone, onExit, op, startLevel }) {
    const ctx = canvas.getContext('2d'), rng = Math.random;
    Object.values(ART).flat().forEach(pic);                 // ask for every picture now, so they are there for the ride
    let W = 0, H = 0, dpr = 1, raf = 0, last = 0, alive = true, f = null;
    let track = [], L = 0, mountains = [], hills = [], skyOff = 0, hillOff = 0;
    let state = 'ready', lane = 1, px = 0, speed = 0, boost = 0, pos = 0, bonus = 0, lives = 3, hurt = 0, time = 0, level = 1;
    let objs = [], fx = [], spawnZ = 0, gateZ = 0, recent = [], best = 0, newBest = false, flash = null;
    const held = { UP: false, DOWN: false };                 // ▲ ▼ held on the keyboard: a pedal
    let dusk = 0, streak = 0, nitro = 0, cheated = false;    // evening light 0 … 1; right gates in a row; nitro seconds left
    let gateTask = null, warned = false;                     // the next bridge's task, chosen early; its warning signs set
    // speed in segments per second (4 km/h each): 16 at first, 3 more each level, at most 42 - braking goes down to MIN in
    // every level, gas adds up to GAS (Doc 04.10.2026: 30 was "brutal schnell", then "das Langsamste ist immer noch zu schnell")
    const MIN = 4, GAS = 14, base = () => Math.min(16 + (level - 1) * 3, 42);
    const T = () => TEXT[lang() === 'de' ? 'de' : 'en'];
    try { best = Math.floor(+localStorage.getItem('cp.rallye.best') || 0); } catch (e) { /* private window */ }   // whole points (an older ride kept parts)
    const lerp = (a, b, p) => a + (b - a) * p;
    const segAt = z => track[Math.floor(((z % L) + L) % L / SEG) % track.length];
    const score = () => Math.floor(pos / SEG / 2 + bonus);  // whole points (nitro adds parts of one)
    const said = t => root.CPQuiz.taskText(t, lang() === 'de');   // 7 ⋅ 8, 56 ÷ 8, 13², √169 - the language's signs (quiz.js)
    const ask = t => said(t) + ' = ?';

    // the screen: the horizon at 40 % of the height, the player's plane at 86 %; the road at that plane as wide as the
    // view (a wide case gets wide verges, the road does not stretch)
    function frame() {
      const vw = Math.min(W, H * 1.25);
      f = { cx: W / 2, hy: H * .4, fx: .5 * vw * CAMH / ROADW, fy: H * .46 };
    }
    function resize() {
      dpr = window.devicePixelRatio || 1;
      W = canvas.clientWidth; H = canvas.clientHeight;
      canvas.width = Math.round(W * dpr); canvas.height = Math.round(H * dpr);
      frame();
      draw();
    }
    const ro = window.ResizeObserver ? new ResizeObserver(resize) : null;
    if (ro) ro.observe(canvas);

    function reset() {
      track = buildTrack(rng); L = track.length * SEG;
      mountains = ridge(rng, 18, .05, .16); hills = ridge(rng, 26, .02, .07);
      lane = 1; px = 0; speed = 0; boost = 0; pos = 0; bonus = 0; lives = 3; hurt = 0; time = 0; level = 1;
      objs = []; fx = []; spawnZ = 60 * SEG; gateZ = 130 * SEG; recent = []; newBest = false; flash = null;
      gateTask = nextTask(); warned = false;
      dusk = 0; streak = 0; nitro = 0; cheated = false;
    }
    function start() { reset(); state = 'ready'; resize(); card(); loop(performance.now()); }
    function stop() { alive = false; cancelAnimationFrame(raf); if (ro) ro.disconnect(); panel.remove(); }
    function go() { reset(); state = 'run'; card(); tone(523, 90); if (op === 'mix' && startLevel > 1) jump(startLevel); }
    // show mode (Option+R, rallye.html): straight into a level to look at it (Doc 04.10.2026: "Wie kann ich mir die
    // einzelnen Level angucken?") - its speed, its traffic, from 3 on the evening at once; a quiz-earned ride cannot
    function jump(n) {
      level = Math.min(Math.max(n, 1), 9); time = (level - 1) * 20; dusk = level >= 3 ? 1 : 0;
      fx.push({ text: T().level(level), x: W / 2, y: H * .3, t: 0, color: C.paper, big: true }); tone(784, 120);
    }

    function key(id) {
      if (id === 'CLEAR') { onExit(); return; }
      if (op === 'mix' && state === 'run' && /^[1-9]$/.test(id)) { jump(+id); return; }
      if (state === 'over' && (id === 'SAVE' || id === 'EXE') && canSave()) { save(); return; }
      if (state === 'ready' && (id === 'LEFT' || id === 'RIGHT')) { choose(mycar + (id === 'LEFT' ? -1 : 1)); return; }
      if (state !== 'run') { if (id === 'EXE' || id === 'UP') go(); return; }
      if (id === 'LEFT' && lane > 0) { lane--; tone(330, 40); }
      else if (id === 'RIGHT' && lane < LANES - 1) { lane++; tone(330, 40); }
      else if (id === 'UP') boost = Math.min(boost + 4, GAS);    // a press (the calculator's cursor pad): a push
      else if (id === 'DOWN') boost = Math.max(boost - 4, MIN - base());
    }
    function hold(id, on) { if (id in held) held[id] = on; }
    // touch: a swipe left / right changes lanes, up / down is gas / brake, a tap at a side changes lanes too
    let p0 = null;
    canvas.addEventListener('pointerdown', ev => { p0 = { x: ev.clientX, y: ev.clientY }; });
    canvas.addEventListener('pointerup', ev => {
      if (!p0) return;
      const dx = ev.clientX - p0.x, dy = ev.clientY - p0.y, r = canvas.getBoundingClientRect();
      p0 = null;
      if (Math.max(Math.abs(dx), Math.abs(dy)) > 24) key(Math.abs(dx) > Math.abs(dy) ? (dx < 0 ? 'LEFT' : 'RIGHT') : (dy < 0 ? 'UP' : 'DOWN'));
      else if (state !== 'run') key('EXE');
      else { const q = (ev.clientX - r.left) / r.width; if (q < .4) key('LEFT'); else if (q > .6) key('RIGHT'); }
    });

    const OPS = root.CPQuiz.OPS;                            // show mode mixes every kind of task
    const nextTask = () => root.CPQuiz.nextTask(recent, rng, op === 'mix' ? OPS[Math.floor(rng() * OPS.length)] : op);
    // --- the world moves: speed in segments per second ---
    function update(dt) {
      time += dt;
      const lv = 1 + Math.floor(time / 20);
      if (lv > level) { level = lv; fx.push({ text: T().level(level), x: W / 2, y: H * .3, t: 0, color: C.paper, big: true }); tone(784, 120); }
      if (held.UP) boost = Math.min(boost + 10 * dt, GAS);     // held: gas and brake as long as the key is down
      if (held.DOWN) boost = Math.max(boost - 14 * dt, MIN - base());
      // from level 3 the evening comes, over some ten seconds (Doc: "Ausbau der Stufe 1": the ride into the sunset)
      dusk += ((level >= 3 ? 1 : 0) - dusk) * Math.min(1, dt * .12);
      // nitro: three right gates in a row - faster, a flame, twice the points for the way, five seconds
      if (nitro > 0) { nitro = Math.max(0, nitro - dt); bonus += speed * dt / 2; }
      const target = Math.max(MIN, base() + boost) + (nitro > 0 ? 18 : 0);
      speed += (target - speed) * Math.min(1, dt * 2.5);
      const ps = segAt(pos + PZ), was = pos;
      pos += speed * SEG * dt;
      px += (LANE_X[lane] - px) * Math.min(1, dt * 9);
      hurt = Math.max(0, hurt - dt);
      skyOff += .0012 * ps.curve * speed * dt; hillOff += .0024 * ps.curve * speed * dt;
      // what lies ahead: rows of obstacles, and now and then a sign bridge with a clear stretch before and after it
      while (spawnZ < pos + DRAW * SEG) {
        // the warning signs, both sides, about two seconds before the bridge at this level's speed
        const warnZ = gateZ - Math.max(30, base() * 2.2) * SEG;
        if (!warned && spawnZ >= warnZ) {
          for (const side of [-1, 1]) objs.push({ kind: 'warn', side, z: warnZ, task: gateTask });
          warned = true;
        }
        if (spawnZ >= gateZ) {
          const t = gateTask;
          objs.push({ kind: 'gate', z: gateZ, task: t, answers: gateAnswers(t, rng), done: false });
          spawnZ = gateZ + 22 * SEG; gateZ += (165 + Math.floor(rng() * 60)) * SEG;   // a bridge every 8 to 11 s
          gateTask = nextTask(); warned = false;
          continue;
        }
        if (gateZ - spawnZ < 22 * SEG) { spawnZ = gateZ; continue; }
        const row = obstacleRow(rng);
        row.blocked.forEach(o => objs.push({ kind: o.kind, lane: o.lane, color: o.color, z: spawnZ, v: o.kind === 'car' ? 4 + rng() * 4 : 0,
          look: Math.floor(rng() * ART.traffic.length) }));
        if (row.star >= 0) objs.push({ kind: 'star', lane: row.star, z: spawnZ });
        spawnZ += Math.max(24, 42 - (level - 1) * 3) * SEG;     // about 2 s apart at first, closer each level
      }
      const me = pos + PZ;
      for (const o of objs) {
        if (o.v) o.z += o.v * SEG * dt;                     // slow traffic drives ahead of us
        if (o.kind === 'gate') {
          if (!o.done && o.z <= me) {
            o.done = true;
            const at = LANE_X.reduce((b, x, i) => Math.abs(x - px) < Math.abs(LANE_X[b] - px) ? i : b, 0);
            if (o.answers[at] === o.task.r) {
              bonus += 100; flash = { color: 'rgba(121,158,49,.35)', t: .35 };
              fx.push({ text: T().right + ' +100', x: W / 2, y: H * .55, t: 0, color: C.green }); tone(880, 90); setTimeout(() => tone(1175, 140), 90);
              if (++streak >= 3) {
                streak = 0; nitro = 5;
                fx.push({ text: T().nitro, x: W / 2, y: H * .42, t: 0, color: C.car, big: true });
                setTimeout(() => { tone(523, 70); setTimeout(() => tone(784, 70), 70); setTimeout(() => tone(1047, 160), 140); }, 250);
              }
            } else {
              fx.push({ text: said(o.task) + ' = ' + o.task.r, x: W / 2, y: H * .5, t: 0, color: C.red, big: true });
              hit();
            }
          }
          continue;
        }
        if (o.kind === 'warn' || o.hit || Math.abs(o.z - me) > SEG * .6 || Math.abs(LANE_X[o.lane] - px) > .42) continue;
        o.hit = true;
        if (o.kind === 'star') { bonus += 25; fx.push({ text: '+25', x: W / 2, y: H * .62, t: 0, color: C.car }); tone(1320, 70); }
        else if (!hurt) hit();
      }
      objs = objs.filter(o => o.z > was - SEG * 4 && !(o.hit && o.kind === 'star'));
    }
    function hit() {
      streak = 0;
      lives--; hurt = 1.4; flash = { color: 'rgba(176,36,24,.35)', t: .35 }; tone(150, 260, 'sawtooth');
      if (lives <= 0) over();
    }
    function over() {
      state = 'over';
      if (score() > best) { best = score(); newBest = true; try { localStorage.setItem('cp.rallye.best', String(best)); } catch (e) { /* private window */ } }
      board = { top: null, err: '', mine: null, rank: 0, busy: false, seconds: Math.max(3, Math.round(time)) };
      card();
      const mine = board;
      scores(op === 'mix' ? { action: 'top' } : { action: 'top', op }).then(j => { if (board === mine) { board.top = j.top || []; card(true); } })
        .catch(() => { if (board === mine) { board.err = T().offline; card(); } });
      tone(392, 160); setTimeout(() => tone(262, 320), 170);
    }
    // what fades: the flash of a hit or a right gate, the texts floating up - also after the end, so nothing stays on the card
    function fade(dt) {
      fx.forEach(q => { q.t += dt; q.y -= dt * H * .08; });
      fx = fx.filter(q => q.t < 1.2);
      if (flash) { flash.t -= dt; if (flash.t <= 0) flash = null; }
    }

    // --- drawing ---
    const font = (w, size, fam) => w + ' ' + Math.max(1, Math.round(size)) + 'px ' + (fam === 'o' ? "'Orbitron', sans-serif" : "'Raleway', 'Helvetica Neue', Arial, sans-serif");
    function rrect(x, y, w, h, r) { ctx.beginPath(); if (ctx.roundRect) ctx.roundRect(x, y, w, h, Math.max(0, r)); else ctx.rect(x, y, w, h); }
    function poly(color, ...p) { ctx.fillStyle = color; ctx.beginPath(); ctx.moveTo(p[0], p[1]); for (let i = 2; i < p.length; i += 2) ctx.lineTo(p[i], p[i + 1]); ctx.closePath(); ctx.fill(); }
    function project(p, camX, camY, camZ) {
      const cz = p.world.z - camZ;
      p.cz = cz; p.scale = DEPTH / cz;
      p.x = f.cx - p.scale * camX * f.fx;
      p.y = f.hy - p.scale * (p.world.y - camY) * f.fy;
      p.w = p.scale * ROADW * f.fx;
    }
    function sky() {
      const g = ctx.createLinearGradient(0, 0, 0, f.hy);
      g.addColorStop(0, mix(C.sky, 'rgb(64, 58, 118)', dusk)); g.addColorStop(1, mix(C.haze, 'rgb(246, 168, 120)', dusk));
      ctx.fillStyle = g; ctx.fillRect(0, 0, W, f.hy + 2);
      const alps = pic(ART.alps), eve = pic(ART.dusk);
      if (alps) {
        panorama(alps, 1);
        if (eve && dusk > .01) panorama(eve, dusk);          // the evening's panorama fading in over the day's
        const haze = ctx.createLinearGradient(0, f.hy - H * .07, 0, f.hy + 2);   // haze where the far road meets the mountains
        haze.addColorStop(0, fogA(0)); haze.addColorStop(1, fogA(.9 - .45 * dusk));   // less of it in the evening
        ctx.fillStyle = haze; ctx.fillRect(0, f.hy - H * .07, W, H * .07 + 2);
      } else {
        range(mountains, C.mount, skyOff, H * .09);
        range(hills, C.hill, hillOff, H * .035);
      }
      ctx.fillStyle = C.grass; ctx.fillRect(0, f.hy, W, H - f.hy);
    }
    // colours between day and evening
    const rgb = c => c.match(/[\d.]+/g).map(Number);
    function mix(a, b, t) { const p = rgb(a), q = rgb(b); return 'rgb(' + p.map((v, i) => Math.round(v + (q[i] - v) * t)).join(',') + ')'; }
    const fogC = () => mix(C.fog, 'rgb(236, 170, 140)', dusk);
    const fogA = al => fogC().replace('rgb(', 'rgba(').replace(')', ',' + al + ')');
    // the panorama standing on the horizon, mirrored side by side so it runs on seamlessly in the bends
    function panorama(im, alpha) {
      const h = f.hy * 1.02, w = h * im.naturalWidth / im.naturalHeight, o = ((skyOff * w * 2) % (2 * w) + 2 * w) % (2 * w);
      ctx.globalAlpha = alpha;
      for (let x = -o, i = 0; x < W; x += w, i++) {
        if (x + w < 0) continue;
        const x0 = Math.floor(x);                           // whole pixels, one pixel of overlap: no hairline at the joins
        if (i % 2) { ctx.save(); ctx.translate(x0 + w + 1, 0); ctx.scale(-1, 1); ctx.drawImage(im, 0, f.hy - h + 2, w + 1, h); ctx.restore(); }
        else ctx.drawImage(im, x0, f.hy - h + 2, w + 1, h);
      }
      ctx.globalAlpha = 1;
    }
    // a picture standing on the road: x its middle, y its foot, w its width on the screen
    function stand(im, x, y, w, flip) {
      const h = w * im.naturalHeight / im.naturalWidth;
      if (!flip) { ctx.drawImage(im, x - w / 2, y - h, w, h); return; }
      ctx.save(); ctx.translate(x, 0); ctx.scale(-1, 1); ctx.drawImage(im, -w / 2, y - h, w, h); ctx.restore();
    }
    function shadow(x, y, w) { ctx.fillStyle = 'rgba(0,0,0,.32)'; ctx.beginPath(); ctx.ellipse(x, y - w * .02, w * .52, w * .07, 0, 0, 7); ctx.fill(); }
    function range(hs, color, off, lift) {                  // one turn of the horizon is 1.6 screen widths
      const span = Math.max(W, H) * 1.6, n = hs.length, step = span / n, o = ((off % 1) + 1) % 1 * span;
      ctx.fillStyle = color; ctx.beginPath(); ctx.moveTo(-step, f.hy + lift);
      for (let i = -1; i <= Math.ceil(W / step) + 1; i++) {
        const k = Math.floor((i * step + o) / step), x = i * step - (o % step);
        ctx.lineTo(x, f.hy + lift - hs[((k % n) + n) % n] * H);
      }
      ctx.lineTo(W + step, f.hy + lift); ctx.closePath(); ctx.fill();
    }
    function segment(s, n) {
      // the grass and the fog exactly the band; road and kerbs one pixel further down - a farther segment drawn later must
      // not lay a line of grass over the nearer one's top (seen as thin lines across the road)
      const a = s.p1, b = s.p2, top = b.y, h = a.y - b.y, ay = a.y + 1;
      // road and grass each one colour - bands of light and dark at speed flickered (Doc 04.10.2026: "die Straße wird immer
      // hell dunkel, hell dunkel ... Das verwirrt sehr"); the kerbs and the centre dashes alone show the speed
      field(s, a, b, top, h);
      const r1 = a.w / 7, r2 = b.w / 7, kerb = s.dark ? C.kerb : C.line;
      poly(kerb, a.x - a.w - r1, ay, a.x - a.w, ay, b.x - b.w, b.y, b.x - b.w - r2, b.y);
      poly(kerb, a.x + a.w + r1, ay, a.x + a.w, ay, b.x + b.w, b.y, b.x + b.w + r2, b.y);
      poly(C.road, a.x - a.w, ay, a.x + a.w, ay, b.x + b.w, b.y, b.x - b.w, b.y);
      if (!s.dark) {
        const l1 = a.w / 30, l2 = b.w / 30, w1 = a.w * 2 / LANES, w2 = b.w * 2 / LANES;
        for (let i = 1; i < LANES; i++) poly(C.line, a.x - a.w + w1 * i - l1, ay, a.x - a.w + w1 * i + l1, ay, b.x - b.w + w2 * i + l2, b.y, b.x - b.w + w2 * i - l2, b.y);
      }
      const fog = 1 - Math.exp(-Math.pow(n / DRAW * 1.8, 2));
      if (fog > .02) { ctx.globalAlpha = fog; ctx.fillStyle = fogC(); ctx.fillRect(0, top, W, h); ctx.globalAlpha = 1; }
    }
    // the land of one band: each side its field; a lake from 1.7 road widths out, a strip of meadow before it; a crop
    // field with a green verge; now and then a glint on the water
    function field(s, a, b, top, h) {
      const mid = (a.x + b.x) / 2;
      for (const [f2, dir] of [[s.L, -1], [s.R, 1]]) {
        const fl = f2 || { kind: 'meadow', shade: 0 }, x0 = dir < 0 ? 0 : mid, x1 = dir < 0 ? mid : W;
        ctx.fillStyle = fl.kind === 'meadow' ? MEADOW[fl.shade] : VERGE; ctx.fillRect(x0, top, x1 - x0, h);
        if (fl.kind === 'meadow') continue;
        const o = fl.kind === 'lake' ? 1.7 : 1.4, ea = a.x + dir * a.w * o, eb = b.x + dir * b.w * o, edge = dir < 0 ? 0 : W;
        poly(fl.kind === 'lake' ? WATER : CROP, ea, a.y + 1, eb, b.y, edge, b.y, edge, a.y + 1);
        if (fl.kind === 'lake' && s.index % 5 === 0) {
          const ga = a.x + dir * a.w * 2.4, gb = b.x + dir * b.w * 2.4, gy = b.y + h * .3;
          ctx.fillStyle = GLINT; ctx.fillRect(Math.min(ga, gb, edge), gy, Math.abs(edge - (ga + gb) / 2), Math.max(1, h * .25));
        }
      }
    }
    // nitro: two flickering flames out of the exhausts, towards us (in the car's own frame: 0,0 is its foot)
    function flames(cw) {
      ctx.globalCompositeOperation = 'lighter';              // they glow: added light, not paint
      for (const dx of [-.19, .19]) {
        const x = dx * cw, y = -cw * .13, len = cw * (.14 + Math.random() * .08), wd = cw * (.075 + Math.random() * .02);
        const g = ctx.createRadialGradient(x, y, 0, x, y, len * 1.4);
        g.addColorStop(0, 'rgba(255,250,210,1)'); g.addColorStop(.3, 'rgba(255,190,60,.85)'); g.addColorStop(.7, 'rgba(255,90,30,.35)'); g.addColorStop(1, 'rgba(255,60,20,0)');
        ctx.fillStyle = g; ctx.beginPath(); ctx.ellipse(x, y + len * .35, wd, len, 0, 0, 7); ctx.fill();
      }
      ctx.globalCompositeOperation = 'source-over';
    }
    // nitro: streaks along the sides of the picture, rushing by
    function streaks() {
      ctx.strokeStyle = 'rgba(255,255,255,.55)'; ctx.lineCap = 'round';
      for (let i = 0; i < 14; i++) {
        const side = i % 2 ? 1 : -1, r = Math.random(), x = W / 2 + side * W * (.3 + r * .22), y = f.hy + (H - f.hy) * Math.random();
        const len = H * (.06 + Math.random() * .1), dx = (x - W / 2) * .25, dy = (y - f.hy) * .25 + len;
        ctx.lineWidth = Math.max(1, H * .004); ctx.beginPath(); ctx.moveTo(x, y); ctx.lineTo(x + dx * len / dy, y + len); ctx.stroke();
      }
      ctx.lineCap = 'butt';
    }
    // a car from behind: x the middle, y where it stands on the road, w its width on the screen
    function carRear(x, y, w, color) {
      const h = w * .62;
      ctx.fillStyle = '#111'; ctx.fillRect(x - w * .47, y - h * .24, w * .19, h * .26); ctx.fillRect(x + w * .28, y - h * .24, w * .19, h * .26);
      ctx.fillStyle = color; rrect(x - w * .38, y - h * 1.2, w * .76, h * .45, w * .12); ctx.fill();
      ctx.fillStyle = C.glass; rrect(x - w * .31, y - h * 1.13, w * .62, h * .3, w * .07); ctx.fill();
      ctx.fillStyle = color; rrect(x - w * .5, y - h * .86, w, h * .66, w * .1); ctx.fill();
      ctx.fillStyle = 'rgb(220, 40, 40)'; rrect(x - w * .46, y - h * .74, w * .17, h * .14, w * .03); ctx.fill(); rrect(x + w * .29, y - h * .74, w * .17, h * .14, w * .03); ctx.fill();
      ctx.fillStyle = 'rgba(0,0,0,.35)'; ctx.fillRect(x - w * .48, y - h * .34, w * .96, h * .1);
      ctx.fillStyle = C.paper; ctx.fillRect(x - w * .12, y - h * .58, w * .24, h * .12);
    }
    function cone(x, y, w) {
      const h = w * 1.35;
      poly(C.cone, x, y - h, x + w / 2, y, x - w / 2, y);
      ctx.fillStyle = C.paper; ctx.fillRect(x - w * .27, y - h * .55, w * .54, h * .14);
    }
    function star(x, y, r) {
      ctx.beginPath();
      for (let i = 0; i < 10; i++) { const a = -Math.PI / 2 + i * Math.PI / 5, q = i % 2 ? r * .45 : r; ctx.lineTo(x + Math.cos(a) * q, y + Math.sin(a) * q); }
      ctx.closePath(); ctx.fillStyle = C.car; ctx.fill(); ctx.lineWidth = r * .14; ctx.strokeStyle = 'rgba(120,80,0,.55)'; ctx.stroke();
    }
    function scenery(sp, x, y, k) {                         // k: screen px per world unit
      if (sp.kind === 'pic') { const im = pic(sp.pic); if (im) stand(im, x, y, WIDTH[sp.pic] * sp.k * k, sp.flip); return; }
      const im = sp.kind === 'tree' ? pic(ART.trees[sp.v || 0]) : sp.kind === 'bush' ? pic(ART.bush) : null;
      if (im) { stand(im, x, y, (sp.kind === 'tree' ? 760 : 380) * sp.k * k); return; }
      if (sp.kind === 'tree') {
        const s = 520 * sp.k * k;
        ctx.fillStyle = C.trunk; ctx.fillRect(x - s * .08, y - s * .6, s * .16, s * .6);
        ctx.fillStyle = C.tree; ctx.beginPath(); ctx.arc(x, y - s * .9, s * .45, 0, 7); ctx.fill();
        ctx.beginPath(); ctx.arc(x - s * .22, y - s * .68, s * .3, 0, 7); ctx.arc(x + s * .24, y - s * .7, s * .3, 0, 7); ctx.fill();
      } else if (sp.kind === 'bush') {
        const s = 260 * sp.k * k;
        ctx.fillStyle = C.tree; ctx.beginPath(); ctx.ellipse(x, y - s * .35, s * .6, s * .38, 0, 0, 7); ctx.fill();
      }
    }
    // the warning sign before a bridge (Doc 04.10.2026: "mach echte Vorwarnschilder"): a red-bordered triangle on a post,
    // as on the road, with the sign of the task that comes - ⋅ (× in English), ÷, x², √
    function warnSign(x, y, k, sym) {
      const s = 360 * k, post = s * 1.05, top = y - post - s * .9;
      ctx.fillStyle = '#6b7079'; ctx.fillRect(x - s * .035, y - post, s * .07, post);
      ctx.lineJoin = 'round'; ctx.lineWidth = Math.max(1, s * .05); ctx.strokeStyle = '#d8dbe0';
      ctx.beginPath(); ctx.moveTo(x, top); ctx.lineTo(x + s * .52, y - post); ctx.lineTo(x - s * .52, y - post); ctx.closePath();
      ctx.fillStyle = C.kerb; ctx.fill(); ctx.stroke();
      const i = s * .17;                                    // the white inside of the red border
      ctx.beginPath(); ctx.moveTo(x, top + i * 1.15); ctx.lineTo(x + s * .52 - i, y - post - i * .55); ctx.lineTo(x - s * .52 + i, y - post - i * .55); ctx.closePath();
      ctx.fillStyle = '#fff'; ctx.fill(); ctx.lineJoin = 'miter';
      if (s < 8) return;
      // the sign, big enough to read from afar: the dot and ÷ drawn as shapes (a glyph's dot is tiny), × as two strokes
      const cx = x, cy = y - post - s * .29, d = s * .085;
      ctx.fillStyle = '#111'; ctx.strokeStyle = '#111'; ctx.lineCap = 'round';
      const dot = (u, v, r) => { ctx.beginPath(); ctx.arc(u, v, r, 0, 7); ctx.fill(); };
      if (sym === '⋅') dot(cx, cy, d * 1.05);
      else if (sym === '÷') { ctx.lineWidth = d * .9; ctx.beginPath(); ctx.moveTo(cx - s * .16, cy); ctx.lineTo(cx + s * .16, cy); ctx.stroke(); dot(cx, cy - s * .12, d * .75); dot(cx, cy + s * .12, d * .75); }
      else if (sym === '×') { ctx.lineWidth = d * .9; const e = s * .11; ctx.beginPath(); ctx.moveTo(cx - e, cy - e); ctx.lineTo(cx + e, cy + e); ctx.moveTo(cx + e, cy - e); ctx.lineTo(cx - e, cy + e); ctx.stroke(); }
      else { ctx.font = font(700, s * (sym.length > 1 ? .4 : .5)); ctx.textAlign = 'center'; ctx.textBaseline = 'middle'; ctx.fillText(sym, cx, cy + s * .02); }
      ctx.lineCap = 'butt';
    }
    function gate(o, x, y, k) {                             // the sign bridge: the task on the banner, an answer over each lane
      const post = 1.14 * ROADW * k, top = y - 1500 * k;
      ctx.fillStyle = '#5b606b'; ctx.fillRect(x - post - 30 * k, top, 60 * k, 1500 * k); ctx.fillRect(x + post - 30 * k, top, 60 * k, 1500 * k);
      ctx.fillStyle = C.ink; rrect(x - post, top, post * 2, 330 * k, 40 * k); ctx.fill();
      ctx.textAlign = 'center'; ctx.textBaseline = 'middle';
      if (230 * k > 5) { ctx.fillStyle = C.paper; ctx.font = font(700, 230 * k); ctx.fillText(ask(o.task), x, top + 175 * k); }
      o.answers.forEach((v, i) => {
        const bx = x + LANE_X[i] * ROADW * k, bw = 440 * k, bh = 300 * k, by = top + 420 * k;
        ctx.strokeStyle = '#5b606b'; ctx.lineWidth = Math.max(1, 14 * k);
        ctx.beginPath(); ctx.moveTo(bx - bw * .3, top + 330 * k); ctx.lineTo(bx - bw * .3, by); ctx.moveTo(bx + bw * .3, top + 330 * k); ctx.lineTo(bx + bw * .3, by); ctx.stroke();
        ctx.fillStyle = o.done && v === o.task.r ? C.green : C.paper; rrect(bx - bw / 2, by, bw, bh, 40 * k); ctx.fill();
        ctx.lineWidth = Math.max(1, 16 * k); ctx.strokeStyle = C.ink; ctx.stroke();
        if (bh > 6) { ctx.fillStyle = C.ink; ctx.font = font(700, 230 * k); ctx.fillText(String(v), bx, by + bh * .54); }
      });
    }

    function draw() {
      if (!W || !H || !track.length) return;
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
      sky();
      const tpos = ((pos % L) + L) % L, base = segAt(tpos), bp = (tpos % SEG) / SEG;
      const ps = segAt(tpos + PZ), pp = ((tpos + PZ) % SEG) / SEG, py = lerp(ps.p1.world.y, ps.p2.world.y, pp);
      let maxy = H, x = 0, dx = -(base.curve * bp);
      const shown = [];
      for (let n = 0; n < DRAW; n++) {
        const s = track[(base.index + n) % track.length], camZ = tpos - (s.index < base.index ? L : 0);
        project(s.p1, px * ROADW - x, py + CAMH, camZ);
        project(s.p2, px * ROADW - x - dx, py + CAMH, camZ);
        x += dx; dx += s.curve;
        s.clip = maxy; shown[n] = s;
        if (s.p1.cz <= DEPTH || s.p2.y >= s.p1.y || s.p2.y >= maxy) continue;
        segment(s, n);
        maxy = s.p1.y;
      }
      // what stands on the road, by the segment it is in
      const at = [];
      for (const o of objs) {
        const rel = o.z - pos;
        if (rel <= PZ * .5 || rel >= (DRAW - 1) * SEG) continue;
        const n = Math.floor(rel / SEG + bp);
        if (n >= DRAW) continue;
        (at[n] = at[n] || []).push({ o, pct: (rel / SEG + bp) - n });
      }
      // from the horizon to the front, each cut off where a hill nearer by hides it
      for (let n = DRAW - 1; n > 0; n--) {
        const s = shown[n];
        if (!s || s.p1.cz <= DEPTH) continue;
        ctx.save(); ctx.beginPath(); ctx.rect(0, 0, W, s.clip); ctx.clip();
        ctx.globalAlpha = Math.max(.15, Math.exp(-Math.pow(n / DRAW * 1.8, 2)));
        for (const sp of s.sprites) { const k = s.p1.scale * f.fx; scenery(sp, s.p1.x + sp.x * ROADW * k, s.p1.y, k); }
        (at[n] || []).sort((a, b) => b.pct - a.pct).forEach(({ o, pct }) => {
          const k = lerp(s.p1.scale, s.p2.scale, pct) * f.fx, cx = lerp(s.p1.x, s.p2.x, pct), y = lerp(s.p1.y, s.p2.y, pct);
          if (o.kind === 'gate') { gate(o, cx, y, k); return; }
          if (o.kind === 'warn') {
            const t = o.task, sym = t.op === 'sq' ? 'x²' : t.op === 'sqrt' ? '√' : root.CPQuiz.opText(t, lang() === 'de');
            warnSign(cx + o.side * 1.4 * ROADW * k, y, k, sym);
            return;
          }
          const ox = cx + LANE_X[o.lane] * ROADW * k;
          if (o.kind === 'car') {
            const im = pic(ART.traffic[o.look || 0]);
            if (im) { shadow(ox, y, CARW * k); stand(im, ox, y + CARW * k * .02, CARW * k); } else carRear(ox, y, CARW * k, o.color);
          }
          else if (o.kind === 'cone') cone(ox, y, 260 * k);
          else star(ox, y - 260 * k, 120 * k);
        });
        ctx.globalAlpha = 1;
        ctx.restore();
      }
      // the player's car: in front, tilting into a lane change, blinking while hurt
      if (!(hurt > 0 && Math.floor(hurt * 10) % 2)) {
        const k = f.fx / CAMH, y = f.hy + f.fy + (state === 'run' ? Math.sin(time * 26) * .6 : 0);
        const im = pic(ART.cars[mycar]), cw = CARW * 1.12 * k;
        ctx.save(); ctx.translate(W / 2, y); ctx.rotate((LANE_X[lane] - px) * .35);
        if (im) { shadow(0, 0, cw); stand(im, 0, cw * .02, cw); } else carRear(0, 0, CARW * 1.05 * k, C.car);
        if (nitro > 0) flames(cw);
        ctx.restore();
      }
      if (nitro > 0 && state === 'run') streaks();
      if (dusk > .01) {                                     // the evening's warm light over everything below the HUD
        ctx.globalCompositeOperation = 'multiply'; ctx.globalAlpha = dusk * .45;
        ctx.fillStyle = 'rgb(255, 176, 140)'; ctx.fillRect(0, 0, W, H);
        ctx.globalCompositeOperation = 'source-over'; ctx.globalAlpha = 1;
      }
      if (flash) { ctx.fillStyle = flash.color; ctx.fillRect(0, 0, W, H); }
      ctx.textAlign = 'center'; ctx.textBaseline = 'middle';
      for (const q of fx) {
        ctx.globalAlpha = Math.max(0, 1 - q.t / 1.2);
        ctx.font = font(700, q.big ? H * .065 : H * .05);
        ctx.lineWidth = H * .008; ctx.strokeStyle = 'rgba(0,0,0,.45)'; ctx.strokeText(q.text, q.x, q.y);
        ctx.fillStyle = q.color; ctx.fillText(q.text, q.x, q.y);
      }
      ctx.globalAlpha = 1;
      hud();
    }
    function hud() {
      const s = H * .05, pad = s * .5, right = pad + s * 1.5;   // right: room for the layer's ✕ (quiz.css .qz-x)
      ctx.textBaseline = 'middle';
      ctx.fillStyle = 'rgba(16,24,44,.55)'; rrect(pad, pad, s * 4.6, s * 1.25, s * .4); ctx.fill();
      ctx.fillStyle = C.paper; ctx.textAlign = 'left'; ctx.font = font(700, s * .8); ctx.fillText(String(score()), pad + s * .45, pad + s * .66);
      ctx.font = font(700, s * .5); ctx.lineWidth = s * .12; ctx.strokeStyle = 'rgba(16,24,44,.55)';   // the level under the score
      ctx.strokeText(T().level(level), pad + s * .45, pad + s * 1.75); ctx.fillText(T().level(level), pad + s * .45, pad + s * 1.75);
      ctx.textAlign = 'right'; ctx.font = font(400, s * .9);
      ctx.fillStyle = 'rgba(16,24,44,.55)'; rrect(W - right - s * 3.6, pad, s * 3.6, s * 1.25, s * .4); ctx.fill();
      for (let i = 0; i < 3; i++) { ctx.fillStyle = i < lives ? '#e5484d' : 'rgba(255,255,255,.25)'; ctx.fillText('♥', W - right - s * .35 - i * s * 1.05, pad + s * .66); }
      if (state === 'run') tacho(pad, s);
      // the next task, readable long before its bridge comes near
      const g = objs.find(o => o.kind === 'gate' && !o.done && o.z - pos < DRAW * SEG);
      if (g && state === 'run') {
        const t = ask(g.task);
        ctx.font = font(700, s * .95); const tw = ctx.measureText(t).width;
        ctx.fillStyle = 'rgba(25,52,130,.9)'; rrect(W / 2 - tw / 2 - s * .6, pad + s * 1.65, tw + s * 1.2, s * 1.35, s * .5); ctx.fill();
        ctx.fillStyle = C.paper; ctx.textAlign = 'center'; ctx.fillText(t, W / 2, pad + s * 2.35);
      }
    }
    // The speedometer, bottom left (Doc 04.10.2026: "kannst du unten irgendwie noch einen Speed Indicator einzeichnen"):
    // a round dial 0 … 240 km/h over 240°, a tick every 20, the last 40 in red, the needle in the car's orange, the number
    // inside - so what ▲ ▼ do is to be seen
    function tacho(pad, s) {
      const r = Math.min(H * .085, W * .13), cx = pad + r * 1.08, cy = H - pad - r * 1.02, MAXK = 240;
      const ang = v => Math.PI * (5 / 6) + (Math.min(v, MAXK) / MAXK) * Math.PI * (4 / 3);   // 150° … 390°
      const kmh = speed * 4;
      ctx.fillStyle = 'rgba(16,24,44,.62)'; ctx.beginPath(); ctx.arc(cx, cy, r * 1.08, 0, 7); ctx.fill();
      ctx.lineCap = 'round';
      ctx.lineWidth = r * .1; ctx.strokeStyle = 'rgba(247,248,243,.18)'; ctx.beginPath(); ctx.arc(cx, cy, r * .86, ang(0), ang(MAXK)); ctx.stroke();
      ctx.strokeStyle = 'rgba(229,72,77,.85)'; ctx.beginPath(); ctx.arc(cx, cy, r * .86, ang(200), ang(MAXK)); ctx.stroke();
      ctx.strokeStyle = C.car; ctx.beginPath(); ctx.arc(cx, cy, r * .86, ang(0), ang(kmh)); ctx.stroke();
      ctx.lineWidth = Math.max(1, r * .035); ctx.strokeStyle = 'rgba(247,248,243,.8)';
      for (let v = 0; v <= MAXK; v += 20) {
        const a = ang(v), q = v % 60 ? .64 : .56;
        ctx.beginPath(); ctx.moveTo(cx + Math.cos(a) * r * q, cy + Math.sin(a) * r * q); ctx.lineTo(cx + Math.cos(a) * r * .72, cy + Math.sin(a) * r * .72); ctx.stroke();
      }
      const a = ang(kmh);
      ctx.lineWidth = r * .07; ctx.strokeStyle = C.car;
      ctx.beginPath(); ctx.moveTo(cx - Math.cos(a) * r * .12, cy - Math.sin(a) * r * .12); ctx.lineTo(cx + Math.cos(a) * r * .8, cy + Math.sin(a) * r * .8); ctx.stroke();
      ctx.fillStyle = C.car; ctx.beginPath(); ctx.arc(cx, cy, r * .1, 0, 7); ctx.fill();
      ctx.lineCap = 'butt';
      ctx.textAlign = 'center'; ctx.textBaseline = 'middle'; ctx.fillStyle = C.paper;
      ctx.font = font(700, r * .36); ctx.fillText(String(Math.round(kmh)), cx, cy + r * .48);
      ctx.font = font(600, r * .2); ctx.fillStyle = 'rgba(247,248,243,.7)'; ctx.fillText('km/h', cx, cy + r * .78);
    }

    // The start and the end as a card of HTML over the canvas, with the Quiz's pills (quiz.css): crisp, centred, tappable
    // (Doc 04.10.2026: the canvas-drawn keys were "ein bisschen geklatscht an die Seite")
    const panel = document.createElement('div');
    panel.className = 'rl-card';
    panel.hidden = true;
    canvas.parentNode.appendChild(panel);
    panel.addEventListener('pointerup', ev => {
      const c = ev.target.closest('[data-car]');
      if (c) { choose(+c.dataset.car); return; }
      const b = ev.target.closest('[data-k]'); if (b) key(b.dataset.k);
    });
    // the car of one's own: chosen on the start card (◀ ▶ there, or a tap), kept on the device
    let mycar = 0;
    try { mycar = Math.min(Math.max(+localStorage.getItem('cp.rallye.car') || 0, 0), ART.cars.length - 1); } catch (e) { /* private window */ }
    function choose(i) {
      mycar = (i + ART.cars.length) % ART.cars.length;
      try { localStorage.setItem('cp.rallye.car', String(mycar)); } catch (e) { /* private window */ }
      tone(660, 50);
      card();
    }
    const esc = v => String(v).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
    const pill = (k, label, cls) => '<span class="qz-pill' + (cls ? ' ' + cls : '') + '" data-k="' + ({ Clear: 'CLEAR', '▲': 'UP' }[k] || k) + '"><b>' + k + '</b>' + esc(label) + '</span>';
    let board = null, draft = '';
    try { draft = localStorage.getItem('cp.rallye.name') || ''; } catch (e) { /* private window */ }
    function card(focusName) {
      const t = T();
      panel.hidden = state === 'run';
      if (state === 'ready') {
        panel.innerHTML = '<div class="qz-head rl-title">' + esc(t.title) + '</div>' +
          '<div class="rl-pick"><div class="rl-bhead">' + esc(t.pick) + '</div><div class="rl-cars">' + ART.cars.map((c, i) =>
            '<span class="rl-car' + (i === mycar ? ' on' : '') + '" data-car="' + i + '"><img src="rallye/' + c + '.webp" alt=""></span>').join('') + '</div></div>' +
          '<div class="qz-big">' + esc(t.lanes) + '<br>' + esc(t.gas) + '</div>' +
          '<div class="qz-how">' + esc(t.gate) + (best ? '<br>' + esc(t.best) + ' ' + best : '') + '</div>' +
          (op === 'mix' ? '<div class="rl-note">' + esc(t.levels) + '</div>' : '') + '<div class="qz-pills">' + pill('EXE', t.go, 'go') + '</div>';
      } else if (state === 'over') {
        const form = canSave(), b = board;
        panel.innerHTML = '<div class="qz-head lost">' + esc(t.over) + '</div><div class="qz-big rl-score">' + score() + ' ' + esc(t.points) + '</div>' +
          '<div class="qz-how' + (newBest ? ' rl-record' : '') + '">' + esc(newBest ? t.record : t.best + ' ' + best) + '</div>' +
          '<div class="rl-board"><div class="rl-bhead">' + esc(t.board) + (op === 'mix' ? '' : ' – ' + root.CPQuiz.opName(op, lang() === 'de')) + '</div>' +
          (form ? '<div class="rl-form"><input class="rl-name" maxlength="12" autocomplete="off" spellcheck="false" placeholder="' + esc(t.name) + '" value="' + esc(draft) + '"' + (b.busy ? ' disabled' : '') + '>' +
            '</div><div class="rl-note">' + esc(t.note) + '</div>' : '') +
          (b.mine ? '<div class="rl-ok">' + esc(t.saved(b.rank)) + '</div>' : '') +
          (op === 'mix' ? '<div class="rl-note">' + esc(t.demo) + '</div>' : '') +
          (b.err ? '<div class="rl-err">' + esc(b.err) + '</div>' : '') +
          (b.top === null ? (b.err ? '' : '<div class="rl-note">' + esc(t.loading) + '</div>') : b.top.length ? '<ol class="rl-list">' + b.top.map((e, i) =>
            '<li' + (e.id === b.mine ? ' class="me"' : '') + '><span class="rl-rank">' + (i + 1) + '.</span><span class="rl-who">' + esc(e.name) + '</span>' +
            (op === 'mix' ? '<span class="rl-op">' + root.CPQuiz.opText({ op: e.op }, lang() === 'de') + '</span>' : '') + '<span class="rl-pts">' + e.score + '</span></li>').join('') + '</ol>'
            : '<div class="rl-note">' + esc(t.empty) + '</div>') + '</div>' +
          '<div class="qz-pills">' + (form ? pill('EXE', t.save, 'go') + pill('▲', t.again) : pill('EXE', t.again, 'go')) + pill('Clear', t.end) + '</div>';
        const inp = panel.querySelector('.rl-name');
        if (inp) {
          inp.addEventListener('input', () => { draft = inp.value; });
          if (focusName && matchMedia('(pointer: fine)').matches) inp.focus();   // a mouse and keyboard: type at once
        }
      }
    }
    // a place in the top ten, not shown yet, not a show-mode ride (Option+R)
    const canSave = () => state === 'over' && op !== 'mix' && !cheated && board && board.top && !board.mine && score() > 0 &&
      (board.top.length < TOP || score() > board.top[board.top.length - 1].score);
    function save() {
      const name = draft.replace(/\s+/g, ' ').trim();
      const inp = panel.querySelector('.rl-name');
      if (!name) { if (inp) inp.focus(); return; }
      if (board.busy) return;
      board.busy = true; board.err = ''; card();
      const mine = board;
      scores({ action: 'add', name, score: score(), op, seconds: board.seconds }).then(j => {
        if (board !== mine) return;
        board.busy = false;
        if (j.status === 409) { board.top = j.top || board.top; board.err = j.error || ''; card(); return; }
        board.top = j.top; board.mine = j.id; board.rank = j.rank;
        try { localStorage.setItem('cp.rallye.name', name); } catch (e) { /* private window */ }
        tone(988, 90); setTimeout(() => tone(1319, 160), 90);
        card();
      }).catch(e => { if (board === mine) { board.busy = false; board.err = e.message; card(true); } });
    }

    function loop(now) {
      if (!alive) return;
      const dt = Math.min(.05, (now - (last || now)) / 1000);
      last = now;
      if (!document.hidden) { if (state === 'run') update(dt); fade(dt); }
      draw();
      raf = requestAnimationFrame(loop);
    }
    // info: for testing from the console (CPRallyeNow.info()) - the next bridge's right lane too
    const nextGate = () => { const g = objs.find(o => o.kind === 'gate' && !o.done); return g ? { right: g.answers.indexOf(g.task.r), ahead: Math.round((g.z - pos) / SEG) } : null; };
    // debug: set the evening, nitro or the level from the console to look at them - that ride then enters no high score
    function debug(o) {
      cheated = true;
      if ('dusk' in o) dusk = +o.dusk;
      if ('nitro' in o) nitro = +o.nitro;
      if ('level' in o) { level = +o.level; time = (level - 1) * 20; }
    }
    return { start, stop, key, hold, debug, info: () => ({ state, speed, boost, lane, level, lives, score: score(), dusk, nitro, streak, gate: nextGate() }) };
  }

  const CPRallye = { create, gateAnswers, obstacleRow, buildTrack, LANES };
  if (typeof module === 'object' && module.exports) module.exports = CPRallye;
  else root.CPRallye = CPRallye;
})(typeof self !== 'undefined' ? self : this);
