// generated by tools/pptx/html_deck.py - edit there, then: python3 tools/pptx/html_deck.py --shell

// time-aware greeting - the browser knows the real clock, a .pptx never does
(function(){
  var h = new Date().getHours();
  var t = h < 5 ? 'Good night!' : h < 12 ? 'Good morning!' :
          h < 18 ? 'Good afternoon!' : h < 22 ? 'Good evening!' : 'Good night!';
  var el = document.getElementById('greet-text');
  if (el) el.textContent = t;
})();

const deck = document.getElementById('deck');
const slides = [...document.querySelectorAll('.slide')];
let si = 0, step = 0;
slides.forEach((s, i) => {
  const p = s.querySelector('.pageno');
  if (p) p.textContent = (i + 1) + ' / ' + slides.length;
});

// keep the 960x540 stage as large as the window allows - phone, beamer, print
function fit(){
  const s = Math.min(innerWidth / 960, innerHeight / 540);
  deck.style.transform = 'scale(' + s + ')';
  dock();
}
// HUD buttons and Solita sit in the footer row, right behind the page number, flush with the end of the
// footer line (Doc, 16.09.2026: "mach die butts und Solita hinter / 24"). They keep a size a finger can
// hit, in screen pixels, so the page number moves left to make room for them - never off screen.
function dock(){
  const hud = document.getElementById('hud'), ask = document.getElementById('ask');
  if (!hud) return;
  const s = Math.min(innerWidth / 960, innerHeight / 540);
  const r = deck.getBoundingClientRect();           // the scaled slide on screen
  const btn = Math.round(Math.min(26, Math.max(18, 12 * s)));
  const av = Math.round(Math.min(46, Math.max(26, 24 * s)));
  document.documentElement.style.setProperty('--hudbtn', btn + 'px');
  document.documentElement.style.setProperty('--askav', av + 'px');
  const cy = r.top + 518 * s;                  // middle of the footer text
  let right = Math.max(8, Math.round(innerWidth - (r.right - 16 * s)));
  if (ask) {
    ask.style.right = right + 'px'; ask.style.bottom = 'auto'; ask.style.top = Math.round(cy - av / 2) + 'px';
    right += av + 8;
  }
  hud.style.right = right + 'px'; hud.style.bottom = 'auto'; hud.style.top = Math.round(cy - btn / 2) + 'px';
  const left = hud.getBoundingClientRect().left;
  deck.style.setProperty('--pnright', Math.max(16, (r.right - left + 12) / s) + 'px');
  const jump = document.getElementById('jump');     // the typed slide number floats above the dock
  if (jump) { jump.style.right = right + 'px'; jump.style.bottom = Math.round(innerHeight - cy + av / 2 + 8) + 'px'; }
}
addEventListener('resize', fit); fit();
addEventListener('load', dock);                      // the overview and play buttons join the HUD later

function groups(sl){
  return [...new Set([...sl.querySelectorAll('.step')].map(e => +e.dataset.g))].length;
}
function paint(){
  slides.forEach((s, i) => s.classList.toggle('on', i === si));
  const sl = slides[si];
  sl.querySelectorAll('.step').forEach(e => e.classList.toggle('on', +e.dataset.g < step));
  document.getElementById('bar').style.width = ((si + 1) / slides.length * 100) + '%';
}
function next(){
  if (step < groups(slides[si])) { step++; }
  else if (si < slides.length - 1) { si++; step = 0; }
  paint();
}
function prev(){
  if (step > 0) { step--; }
  else if (si > 0) { si--; step = groups(slides[si]); }
  paint();
}
addEventListener('keydown', e => {
  if (e.metaKey || e.ctrlKey || e.altKey) return;     // never eat Cmd-Shift-R
  const k = e.key;
  if (/^(Arrow|Page|Home|End| )/.test(k)) narr.stop();   // turning pages by hand pauses Solita
  if (k === 'ArrowRight' || k === 'ArrowDown' || k === ' ' || k === 'PageDown') { next(); e.preventDefault(); }
  else if (k === 'ArrowLeft' || k === 'ArrowUp' || k === 'PageUp') { prev(); e.preventDefault(); }
  else if (k === 'Home') { si = 0; step = 0; paint(); }
  else if (k === 'End') { si = slides.length - 1; step = groups(slides[si]); paint(); }
  else if (k === 'f' || k === 'F') { full(); }
});
addEventListener('click', e => {
  // links (lab bar, picture credits) open - they do not turn the page as well
  if (e.target.closest('#hud') || e.target.closest('a') || e.target.closest('.play-big')) return;
  narr.stop();                                       // a click turns the page by hand
  if (e.target.closest('.labbar button')) { next(); return; }
  next();
});   // clicks inside a lab stay in the lab - they never reach this document
// type the slide number, then Enter: 1 7 Enter jumps to slide 17 (Doc, 15.09.2026) - like
// PowerPoint the slide starts unbuilt; Esc or a 2.5 s pause drops the typed number
(function () {
  let buf = '', timer = 0;
  const box = document.createElement('div');
  box.id = 'jump';
  box.hidden = true;
  document.body.appendChild(box);
  const clear = function () { buf = ''; box.hidden = true; };
  addEventListener('keydown', function (e) {
    if (e.metaKey || e.ctrlKey || e.altKey) return;
    if (/^[0-9]$/.test(e.key)) {
      buf = (buf + e.key).replace(/^0+/, '').slice(-3);
      box.textContent = 'Folie ' + (buf || '0');
      box.hidden = false;
      clearTimeout(timer); timer = setTimeout(clear, 2500);
      e.preventDefault();
    } else if (e.key === 'Enter' && buf) {
      const n = parseInt(buf, 10);
      clear();
      if (n >= 1 && n <= slides.length) {
        if (typeof narr !== 'undefined') narr.stop();   // a jump pauses Solita like turning by hand
        si = n - 1; step = 0; paint();
      }
      e.preventDefault();
    } else if (e.key === 'Escape' && buf) { clear(); }
  });
})();
// overview of all slides: o (or the grid button bottom right) opens it, a click jumps there,
// Esc, o or a click beside the tiles closes it (Doc, 15.09.2026: "Uebersicht ueber alle Folien")
(function () {
  const ov = document.createElement('div');
  ov.id = 'overview';
  ov.hidden = true;
  document.body.appendChild(ov);
  const btn = document.createElement('button');
  btn.id = 'ovbtn';
  btn.type = 'button';
  btn.title = 'Übersicht aller Folien (o)';
  btn.setAttribute('aria-label', 'Übersicht aller Folien');
  btn.innerHTML = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true">'
    + '<rect x="2.5" y="2.5" width="8.5" height="8.5" rx="1.2"/><rect x="13" y="2.5" width="8.5" height="8.5" rx="1.2"/>'
    + '<rect x="2.5" y="13" width="8.5" height="8.5" rx="1.2"/><rect x="13" y="13" width="8.5" height="8.5" rx="1.2"/></svg>';
  const hudBox = document.getElementById('hud');   // bottom right, next to play and fullscreen
  if (hudBox) hudBox.insertBefore(btn, hudBox.firstChild); else document.body.appendChild(btn);
  let built = false;
  function close() { ov.hidden = true; }
  function build() {
    slides.forEach(function (s, i) {
      const cell = document.createElement('div');
      cell.className = 'ov-cell';
      const thumb = document.createElement('div');
      thumb.className = 'ov-thumb';
      const c = s.cloneNode(true);                     // a copy, fully built, without ids
      c.querySelectorAll('[id]').forEach(function (e) { e.removeAttribute('id'); });
      c.classList.add('on');
      thumb.appendChild(c);
      const num = document.createElement('span');
      num.className = 'ov-num';
      num.textContent = i + 1;
      cell.appendChild(thumb);
      cell.appendChild(num);
      cell.addEventListener('click', function (e) {
        e.stopPropagation();
        if (typeof narr !== 'undefined') narr.stop();
        si = i; step = 0; paint(); close();
      });
      ov.appendChild(cell);
    });
    built = true;
  }
  function scale() {
    ov.querySelectorAll('.ov-thumb').forEach(function (t) {
      t.firstChild.style.transform = 'scale(' + (t.clientWidth / 960) + ')';
    });
  }
  function open() {
    if (typeof narr !== 'undefined') narr.stop();
    if (!built) build();
    ov.hidden = false;
    [].forEach.call(ov.children, function (c, i) { c.classList.toggle('cur', i === si); });
    scale();
    if (ov.children[si]) ov.children[si].scrollIntoView({ block: 'center' });
  }
  btn.addEventListener('click', function (e) { e.stopPropagation(); if (ov.hidden) open(); else close(); });
  ov.addEventListener('click', function (e) { e.stopPropagation(); close(); });
  addEventListener('resize', function () { if (!ov.hidden) scale(); });
  addEventListener('keydown', function (e) {
    if (e.metaKey || e.ctrlKey || e.altKey) return;
    // this one listens in the capture phase, so a question typed to Solita would reach it first:
    // 'o' would open the overview mid-sentence. Nothing from inside #ask belongs to the deck.
    if (e.target && e.target.closest && e.target.closest('#ask')) return;
    if (e.key === 'o' || e.key === 'O') {
      if (ov.hidden) open(); else close();
      e.preventDefault(); e.stopImmediatePropagation(); return;
    }
    if (!ov.hidden) {                                  // nothing underneath moves meanwhile
      if (e.key === 'Escape') close();
      e.preventDefault(); e.stopImmediatePropagation();
    }
  }, true);
})();
// fullscreen toggle - the same corner-bracket icon as the SVP pill, in and out
const ICON_ENTER = '<path d="M8 3H5a2 2 0 0 0-2 2v3"/><path d="M16 3h3a2 2 0 0 1 2 2v3"/>'
  + '<path d="M8 21H5a2 2 0 0 1-2-2v-3"/><path d="M16 21h3a2 2 0 0 0 2-2v-3"/>';
const ICON_EXIT = '<path d="M3 8h3a2 2 0 0 0 2-2V3"/><path d="M21 8h-3a2 2 0 0 1-2-2V3"/>'
  + '<path d="M3 16h3a2 2 0 0 1 2 2v3"/><path d="M21 16h-3a2 2 0 0 0-2 2v3"/>';
const fullBtn = document.getElementById('full');
const fsOn = () => !!(document.fullscreenElement || document.webkitFullscreenElement);
function paintFull(){
  fullBtn.innerHTML = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" '
    + 'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'
    + (fsOn() ? ICON_EXIT : ICON_ENTER) + '</svg>';
  fullBtn.title = fsOn() ? 'Vollbild verlassen (Esc)' : 'Vollbild (f)';
}
function full(){
  const el = document.documentElement;
  if (fsOn()) (document.exitFullscreen || document.webkitExitFullscreen).call(document);
  else {
    const req = el.requestFullscreen || el.webkitRequestFullscreen;
    if (req) Promise.resolve(req.call(el)).catch(() => {});
  }
}
fullBtn.onclick = full;
document.addEventListener('fullscreenchange', paintFull);
document.addEventListener('webkitfullscreenchange', paintFull);
if (document.documentElement.requestFullscreen || document.documentElement.webkitRequestFullscreen) paintFull();
else fullBtn.hidden = true;   // no fullscreen API (iPhone Safari) - nothing to press

// #7 in the URL opens slide 7 fully built - handy for linking a single slide
function fromHash(){
  const n = parseInt(location.hash.slice(1), 10);
  if (n >= 1 && n <= slides.length) { si = n - 1; step = groups(slides[si]); paint(); }
}
addEventListener('hashchange', fromHash);

// formulas: KaTeX renders every $...$ the build script wrote
addEventListener('load', () => {
  if (!window.katex) return;
  document.querySelectorAll('.tex').forEach(el => {
    try { katex.render(el.dataset.tex, el, { throwOnError: false, displayMode: false }); }
    catch (err) { el.textContent = el.dataset.tex; }
  });
});
// Solita reads the deck (Doc, 15.09.2026: "NIEMALS Browserstimme! So wie beim DocPad!") - the
// clips come from tools/pptx/deck_audio.mjs with her DocPad voice, nothing is synthesised here.
// Part 0 of a slide is spoken when it appears, part k while click group k comes in, then on.
const narr = (function () {
  const api = { playing: false, stop: function () {} };
  let data = null;
  try { data = JSON.parse(document.getElementById('narration').textContent || 'null'); } catch (e) { }
  if (!data || !data.slides) return api;
  const btn = document.getElementById('play');
  const PLAY = '<path d="M6.5 5v14l11-7z" fill="currentColor"/>';
  const PAUSE = '<path d="M7 5h3.5v14H7zM13.5 5H17v14h-3.5z" fill="currentColor"/>';
  const pad = n => String(n).padStart(2, '0');
  const parts = s => (data.slides[s] || []).length;
  let audio = null, aSlide = -1, part = 0;
  let wait = 0;                                       // pending pause after a clip or before the next slide
  const holds = data.hold || [];
  let held = -1;                                      // slide where Solita waits for a click
  const big = document.createElement('button');
  big.type = 'button';
  big.className = 'play-big';
  const label = document.createElement('div');
  label.className = 'play-big-label';
  label.textContent = 'Solita erklärt';
  const home = document.querySelector('.slide.title') || slides[0];   // title slide, in the orbit ring
  home.appendChild(big);
  home.appendChild(label);
  btn.hidden = false;
  function show() {
    const icon = '<svg viewBox="0 0 24 24" aria-hidden="true">' + (api.playing ? PAUSE : PLAY) + '</svg>';
    const t = api.playing ? 'Pause (p)' : held >= 0 ? 'Weiter mit Klick (p)' : 'Solita erklärt (p)';
    [btn, big].forEach(b => { b.innerHTML = icon; b.title = t; b.setAttribute('aria-label', t); });
  }
  function run() {
    if (!api.playing) return;
    if (part >= parts(si)) {                          // slide done: everything in, then on
      step = groups(slides[si]); paint();
      if (si >= slides.length - 1) { api.playing = false; audio = null; show(); return; }
      // say(hold=True): e.g. before a solution - the next slide comes only on a click
      if (holds.indexOf(si) >= 0) { api.playing = false; audio = null; held = si; show(); return; }
      // Doc 16.09.2026 "zu schnell, ein wenig mehr Pausen": the finished slide stands a moment longer
      wait = setTimeout(function () { if (!api.playing) return; si++; step = 0; part = 0; paint(); run(); }, 1600);
      return;
    }
    if (part > 0) { step = Math.min(part, groups(slides[si])); paint(); }
    aSlide = si;
    audio = new Audio('audio/' + data.deck + '/s' + pad(si) + '-' + pad(part) + '.mp3');
    audio.onended = function () { part++; wait = setTimeout(run, part < parts(si) ? 900 : 0); };
    audio.onerror = function () { part++; run(); };   // a missing clip must not hang the talk
    audio.play().catch(function () { api.playing = false; show(); });
  }
  function resume(n) {                                // go on talking from the top of slide n
    clearTimeout(wait);
    held = -1; api.playing = true; si = n; step = 0; part = 0; audio = null; show(); paint(); run();
  }
  function toggle() {
    clearTimeout(wait);
    if (!api.playing && held >= 0 && si === held && si < slides.length - 1) { resume(si + 1); return; }
    held = -1;
    if (api.playing) { api.playing = false; if (audio) audio.pause(); show(); return; }
    api.playing = true; show();
    if (audio && aSlide === si && audio.paused && !audio.ended && audio.currentTime > 0) { audio.play(); return; }
    part = step; audio = null; run();                 // start where the page stands
  }
  api.stop = function () {
    clearTimeout(wait);
    if (held >= 0) {
      // waiting at a hold: the click that turns to the next slide lets Solita go on there
      // (stop runs before the page handler's next(), so look once that has happened)
      const h = held; held = -1; show();
      setTimeout(function () { if (!api.playing && si === h + 1) resume(si); }, 0);
      return;
    }
    if (!api.playing) return;
    api.playing = false; if (audio) audio.pause(); audio = null; show();
  };
  // stop the click here: toggle redraws the icon, and the page's click handler would then no
  // longer see the (detached) target inside #hud - it turned the page and paused Solita again
  btn.onclick = function (e) { e.stopPropagation(); toggle(); };
  big.onclick = function (e) { e.stopPropagation(); toggle(); };
  addEventListener('keydown', function (e) {
    if ((e.key === 'p' || e.key === 'P') && !e.metaKey && !e.ctrlKey && !e.altKey) toggle();
  });
  show();
  return api;
})();

paint();
fromHash();

// Ask Solita about the slide on screen: Claude Haiku answers from the deck's own text, her DocPad
// voice reads it out (Doc, 16.09.2026: "bau mal mit Haiku (solita nur voice)"). The API keys live in
// the Supabase edge functions, never here (Rule 21) - the shared password gates the proxy and is
// remembered per device in localStorage 'dev_access', the same key solita.html uses.
(function () {
  const box = document.getElementById('ask');
  if (!box) return;
  const AI_URL = 'https://fyfhxzyymmurlaenmzse.supabase.co/functions/v1/claude';
  const TTS_URL = 'https://fyfhxzyymmurlaenmzse.supabase.co/functions/v1/tts';
  const MODEL = 'claude-haiku-4-5';        // ~0.3 ct per question; the voice costs far more than the answer
  const VOICE = 'de-DE-Studio-C';          // Solita's DocPad voice - NEVER the browser voice (Doc)
  const SYS = 'Du bist Solita, die Tutorin in Doc Alvers Mathe-Labor. Du hilfst Schülerinnen und '
    + 'Schülern der Klassen 11 bis 13 am Beruflichen Gymnasium und an der Fachoberschule. '
    + 'Du bekommst eine Übersicht der Präsentation und die Folie, auf der die Klasse gerade steht. '
    + 'Antworte auf Deutsch, kurz und klar: höchstens vier Sätze, gesprochene Sprache - die Antwort wird '
    + 'vorgelesen. Formeln in LaTeX zwischen Dollarzeichen. Stütze dich zuerst auf die Folien. '
    + 'Hintergrundwissen zum Thema - Personen, Geschichte, Anwendungen, verwandte Begriffe - darfst du '
    + 'ergänzen, wenn du dir sicher bist; sonst sag kurz, dass du es nicht genau weißt. Kurze Nachfragen '
    + 'wie "und woher kam der?" beziehen sich auf das bisherige Gespräch. Sprich nie über deinen Kontext, '
    + 'die Präsentation als Quelle oder darüber, ob eine Frage zum Thema passt - antworte einfach. Nur wenn '
    + 'eine Frage gar nichts mit dem Unterricht zu tun hat, lenk in einem Satz freundlich zur Folie zurück. '
    + 'Lob die Frage nicht ("Das ist eine gute Frage!" und Ähnliches) - nur wenn sie wirklich '
    + 'außergewöhnlich klug ist, darfst du das einmal kurz sagen. Keine Emojis, keine Aufzählungen.';
  // Doc, 16.09.2026: "war der Engländer?" after a question about Efron came back as "passt nicht zum
  // Thema, ich kenne keinen Kontext". Two causes: every question went out alone, without the talk
  // before it, and the prompt forbade anything not on the slides. Now the last HIST_MAX exchanges
  // travel along (plain text, no slide context - that only rides with the new question).
  const HIST_MAX = 4;
  const hist = [];

  // What a question REALLY costs (worked out 16.09.2026, after Doc asked why nothing ever turns up on
  // the Google bill): Claude is billed from the first token - no free tier - while Google grants a free
  // quota of characters per voice type per CALENDAR MONTH, and a lesson never gets near it. The counter
  // therefore keeps two different things apart: euros for Claude, characters for the voice, and it turns
  // characters into euros only for what runs OVER the monthly quota.
  // ttsFree/ttsUsd are list values: Google's pricing table is built by JS and cannot be read from here.
  // Third-party sources say 30 $ per 1M, the older note in supabase/functions/tts says 160 $ - the higher
  // one is used on purpose, so the counter warns early rather than late. The truth is in Cloud Billing
  // (console.cloud.google.com/billing/reports, Service = Cloud Text-to-Speech API). Doc's account carries
  // a 10 EUR/month budget alert - a mail, not a tap that closes.
  const RATE = { in: 1, out: 5, cacheRead: 0.1, cacheWrite: 1.25, eur: 0.92,
                 ttsUsd: 160, ttsFree: 1e6 };

  const panel = document.getElementById('ask-panel');
  const out = document.getElementById('ask-out');
  const input = document.getElementById('ask-in');
  const send = document.getElementById('ask-send');
  const label = box.querySelector('label');
  const micBtn = document.getElementById('ask-mic');
  const ttsBtn = document.getElementById('ask-tts');
  const costEl = document.getElementById('ask-cost');
  let audio = null, busy = false, ear = null;

  // What THIS question cost - not a running total (Doc, 16.09.2026: the sum belongs in the 08:00
  // mail, where it covers every device). Claude is real money from the first token; the voice is
  // characters against Google's monthly free quota, so it shows as characters, with the list price
  // it WOULD cost only in the tooltip.
  let last = null;
  function money(eur) {
    if (eur >= 1) return eur.toFixed(2).replace('.', ',') + ' \u20ac';
    const ct = eur * 100;
    return (ct < 1 ? ct.toFixed(2) : ct.toFixed(1)).replace('.', ',') + ' ct';
  }
  function showCost() {
    if (!last) { costEl.textContent = ''; costEl.title = 'Kosten der letzten Frage'; return; }
    costEl.textContent = money(last.claude);         // voice characters only in the tooltip (Doc, 16.09.2026)
    costEl.title = 'Diese Frage\n'
      + 'Claude (Haiku): ' + money(last.claude) + ' - ' + last.tin + ' Token rein, '
      + last.tout + ' raus, wird ab dem ersten Token berechnet\n'
      + (last.chars
          ? 'Stimme: ' + last.chars + ' Zeichen - frei im Monatskontingent, zum Listenpreis waere es '
            + money(last.chars / 1e6 * RATE.ttsUsd * RATE.eur)
          : 'Stimme: aus')
      + '\nWartezeit: Claude ' + secs(last.msAi) + (last.msVoice ? ' + Stimme ' + secs(last.msVoice) : '');
  }
  function secs(ms) { return ms ? (ms / 1000).toFixed(1).replace('.', ',') + ' s' : '-'; }
  function addClaude(usage, ms) {
    const u = usage || {};
    last = {
      claude: ((u.input_tokens || 0) * RATE.in
             + (u.cache_read_input_tokens || 0) * RATE.in * RATE.cacheRead
             + (u.cache_creation_input_tokens || 0) * RATE.in * RATE.cacheWrite
             + (u.output_tokens || 0) * RATE.out) / 1e6 * RATE.eur,
      tin: (u.input_tokens || 0) + (u.cache_read_input_tokens || 0),
      tout: u.output_tokens || 0,
      chars: 0,
      msAi: ms, msVoice: 0,
    };
    showCost();
  }
  function addVoice(chars, ms) { if (last) { last.chars = chars; last.msVoice = ms; showCost(); } }
  // Reading aloud on/off. Same localStorage key as solita.html, so switching her quiet holds here
  // too - and with it off, no TTS request goes out at all (the voice is 97 % of what a question costs).
  const TTS_KEY = 'solita_tts';
  let ttsOn = true;
  try { ttsOn = localStorage.getItem(TTS_KEY) !== '0'; } catch (e) { }
  const SPK_ON = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" '
    + 'stroke-linecap="round" stroke-linejoin="round"><path d="M11 5 6 9H3v6h3l5 4z"/>'
    + '<path d="M15.5 8.5a5 5 0 0 1 0 7"/><path d="M18.5 5.5a9 9 0 0 1 0 13"/></svg>';
  const SPK_OFF = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" '
    + 'stroke-linecap="round" stroke-linejoin="round"><path d="M11 5 6 9H3v6h3l5 4z"/>'
    + '<path d="m16 9 5 6"/><path d="m21 9-5 6"/></svg>';
  function showTts() {
    ttsBtn.innerHTML = ttsOn ? SPK_ON : SPK_OFF;
    ttsBtn.classList.toggle('off', !ttsOn);
    const t = ttsOn ? 'Solita liest vor' : 'Solita liest NICHT vor (keine Stimm-Kosten)';
    ttsBtn.title = t; ttsBtn.setAttribute('aria-label', t);
  }
  ttsBtn.onclick = function () {
    ttsOn = !ttsOn;
    try { localStorage.setItem(TTS_KEY, ttsOn ? '1' : '0'); } catch (e) { }
    if (!ttsOn) stopAudio();
    showTts();
  };
  showTts();

  costEl.onclick = function () { last = null; showCost(); };
  showCost();

  // Keys and clicks inside the panel stay there: typing a question must not turn pages, open the
  // overview ('o') or pause Solita ('p'). Measured 16.09.2026: a capture listener on window is the
  // wrong tool - it kills the event before the button's own handler sees it, yet window's own bubble
  // listeners (page keys, slide jump, overview) still fire. Stopping on the way up from #ask does
  // both right: handlers inside #ask run, nothing reaches the deck.
  box.addEventListener('keydown', function (e) { e.stopPropagation(); });
  box.addEventListener('click', function (e) { e.stopPropagation(); });

  function pwd() { try { return localStorage.getItem('dev_access') || ''; } catch (e) { return ''; } }
  // Every call goes out as a CORS "simple request": no custom headers, the body is plain text (both
  // functions read it with req.json() anyway) and the password rides in the body, which the claude
  // function accepts as well as x-app-pass. Custom headers (apikey, Authorization, x-app-pass) made
  // the browser send an OPTIONS preflight before EVERY call - measured in the Supabase logs on
  // 16.09.2026, those preflights took 4.6-13.3 s from Doc's Chrome, 62 % of the whole wait. The
  // gateway does not need the anon key: both functions run with --no-verify-jwt, and the tts guard
  // accepts the browser's Origin header instead.
  function post(url, body, signal) {
    return fetch(url, { method: 'POST', body: JSON.stringify(body), signal: signal });
  }
  // Wake both functions while the question is still being typed, at no cost: an empty tts call is
  // refused before Google is asked, a ping only checks the password. At most once a minute.
  let warmAt = 0;
  function warm() {
    if (Date.now() - warmAt < 60000) return;
    warmAt = Date.now();
    post(TTS_URL, {}).catch(function () { });
    if (pwd()) post(AI_URL, { ping: true, pass: pwd() }).catch(function () { });
  }
  function askPassword() {          // no password yet: the same field asks for it once, then remembers
    label.textContent = 'Passwort — wird auf diesem Gerät gemerkt';
    label.hidden = false;
    input.setAttribute('aria-label', 'Passwort');
    input.type = 'password'; input.value = ''; input.placeholder = '';
    input.setAttribute('autocomplete', 'current-password');
    send.textContent = 'OK';
    micBtn.hidden = true; ttsBtn.hidden = true;
  }
  function askQuestion() {
    label.hidden = true;                            // a question needs no label (Doc, 16.09.2026: "weg")
    input.setAttribute('aria-label', 'Deine Frage an Solita');   // the field still has a name (Doc's label rule)
    input.type = 'text'; input.value = ''; input.placeholder = 'Warum zwei Drittel?';
    input.setAttribute('autocomplete', 'off');
    send.textContent = '?';
    micBtn.hidden = !(window.SpeechRecognition || window.webkitSpeechRecognition);
    ttsBtn.hidden = false;
  }
  function say(html, cls) {
    const p = document.createElement('div');
    if (cls) p.className = cls;
    p.innerHTML = html;
    out.appendChild(p); out.scrollTop = out.scrollHeight;
    return p;
  }

  // the deck is its own source: slide text with the TeX put back in - minus the footer and page
  // number, which every slide repeats (13 % of the old context was "Nicht verzagen, ..." 24 times)
  function slideText(s) {
    const c = s.cloneNode(true);
    c.querySelectorAll('.foot, .pageno').forEach(function (e) { e.remove(); });
    c.querySelectorAll('[data-tex]').forEach(function (e) { e.textContent = '$' + e.dataset.tex + '$'; });
    return (c.textContent || '').replace(/\s+/g, ' ').trim();
  }
  let SUMMARY = {}, NARR = null;
  try { SUMMARY = JSON.parse(document.getElementById('summary').textContent || '{}') || {}; } catch (e) { }
  try { NARR = JSON.parse(document.getElementById('narration').textContent || 'null'); } catch (e) { }
  function overviewLine(i) {                        // a deck built without summaries still gets a line
    if (SUMMARY[String(i)]) return SUMMARY[String(i)];
    const h = slides[i].querySelector('h1, h2, h3');
    return h ? h.textContent.replace(/\s+/g, ' ').trim() : slideText(slides[i]).slice(0, 90);
  }

  // Compact context (Doc, 16.09.2026): one summary line per slide, the slide on screen in full, and
  // any slide the question names ("Folie 15", "F15", "Seite 15") in full too. Measured before: the
  // whole deck in full was ~3,500 tokens a question.
  // Slides behind a hold - a solution - stay OUT until the class has reached them, and Claude is told
  // not to work the task out: otherwise it hands over the answer while the class is still on it.
  function context(q) {
    const ahead = ((NARR && NARR.hold) || []).filter(function (h) { return h >= si; });
    const last = ahead.length ? Math.min.apply(null, ahead) : slides.length - 1;
    const lines = ['Deck: ' + document.title, 'Übersicht, eine Zeile je Folie:'];
    for (let i = 0; i <= last; i++) lines.push('F' + (i + 1) + ': ' + overviewLine(i));
    const full = [si];
    String(q).replace(/\b(?:folie|seite|slide|f)\s*(\d{1,3})\b/gi, function (m, n) {
      const i = +n - 1;
      if (i >= 0 && i <= last && full.indexOf(i) < 0) full.push(i);
      return m;
    });
    full.forEach(function (i) {
      lines.push('', (i === si ? 'Die Klasse steht auf Folie ' + (i + 1)
                               : 'Folie ' + (i + 1) + ', nach der gefragt wird') + ' - voller Inhalt:');
      lines.push(slideText(slides[i]));
      const spoken = NARR && NARR.slides && NARR.slides[String(i)];
      if (spoken && spoken.length) lines.push('Solita erklärt dazu: ' + spoken.join(' '));
    });
    if (ahead.length) {
      lines.push('', 'Wichtig: Die Lösung zu Folie ' + (last + 1) + ' hat die Klasse noch nicht gesehen. '
        + 'Rechne diese Aufgabe nicht vor und nenne kein Ergebnis - gib höchstens einen Tipp.');
    }
    return lines.join('\n');
  }
  window.askSolitaContext = context;   // debug: askSolitaContext('F15?') shows exactly what goes out

  function render(el, text) {       // formulas the model wrote in $...$ come out as real maths
    el.textContent = '';
    String(text).split(/(\$[^$\n]+\$)/).forEach(function (part) {
      if (/^\$[^$\n]+\$$/.test(part)) {
        const span = document.createElement('span');
        try { katex.render(part.slice(1, -1), span, { throwOnError: false, displayMode: false }); }
        catch (e) { span.textContent = part; }
        el.appendChild(span);
      } else if (part) {                          // one span per word, so her voice can light it up
        part.split(/(\s+)/).forEach(function (tok) {
          if (!tok) return;
          if (/^\s+$/.test(tok)) { el.appendChild(document.createTextNode(tok)); return; }
          const w = document.createElement('span');
          w.className = 'ask-w'; w.textContent = tok;
          el.appendChild(w);
        });
      }
    });
  }

  // Karaoke (Doc, 16.09.2026): the word Solita is saying lights up. Google returns no word timestamps
  // for Studio voices - they do not support SSML <mark> - so the times are ESTIMATED: syllables per
  // word, a pause after commas and sentence ends, spread over the length of the audio. Measured on
  // 16.09.2026 against Studio-C syntheses of the answer cut off after every word: mean error 0.13 s,
  // worst 0.24 s, on an answer the weights were NOT tuned on. Letters instead of syllables were twice
  // as far off, and anchoring on the pauses found in the audio made it worse, not better.
  // lead/tail: the silence Google puts before and after the speech (measured 0.10 s and 0.09 s).
  const KARA = { lead: 0.10, tail: 0.09, base: 0.3, sentence: 1.5, comma: 0.6 };
  function syllables(w) {
    const v = w.toLowerCase().match(/[aeiouyäöü]+/g);
    if (v) return v.length;
    const d = w.replace(/\D/g, '');
    return d.length * 1.5;                           // a bare number: roughly one and a half per digit
  }
  function karaoke(el, a) {
    const items = [];
    let pos = 0;
    el.querySelectorAll('.ask-w').forEach(function (sp) {
      const w = sp.textContent.replace(/[*_`#>]/g, '');   // what speak() strips is not spoken either
      const n = syllables(w);
      if (n) { items.push({ sp: sp, s: pos }); pos += n + KARA.base; }
      if (/[.!?]["')\]]*$/.test(w)) pos += KARA.sentence;
      else if (/[,;:]["')\]]*$/.test(w)) pos += KARA.comma;
    });
    if (!items.length) return;
    const last = items[items.length - 1];
    const total = last.s + syllables(last.sp.textContent) + KARA.base;
    let on = null;
    function mark(sp) {
      if (sp === on) return;
      if (on) on.classList.remove('on');
      on = sp;
      if (!sp) return;
      sp.classList.add('on');
      const r = sp.getBoundingClientRect(), o = out.getBoundingClientRect();   // keep her word in view
      if (r.bottom > o.bottom - 4) out.scrollTop += r.bottom - o.bottom + 24;
      else if (r.top < o.top + 4) out.scrollTop -= o.top - r.top + 24;
    }
    function frame() {
      if (audio !== a || a.paused) { mark(null); return; }   // stopped, closed or finished
      if (isFinite(a.duration) && a.duration > 0) {
        const u = (a.currentTime - KARA.lead) / Math.max(0.1, a.duration - KARA.lead - KARA.tail) * total;
        let i = -1;
        while (i + 1 < items.length && items[i + 1].s <= u) i++;
        mark(i >= 0 ? items[i].sp : null);
      }
      requestAnimationFrame(frame);
    }
    a.addEventListener('playing', function () { requestAnimationFrame(frame); });
  }

  // Solita's own voice via the tts edge function. NO browser-voice fallback (Doc: "NIEMALS
  // Browserstimme") - if the cloud voice fails, the answer just stays on screen.
  // show() puts the answer on screen only once her voice has arrived (Doc, 16.09.2026: "den Text erst
  // zeigen, wenn die audiodaten da sind"), so reading and hearing start together. Speaker off, nothing
  // to say, no voice or a voice that hangs: the answer shows anyway.
  const TTS_WAIT = 20000;                            // ms - a hanging voice must not hide the answer
  function speak(text, show) {
    let shown = false, el = null;
    function once() { if (!shown) { shown = true; el = show(); } }
    const clean = String(text)
      .replace(/\$\$[\s\S]*?\$\$/g, ' ').replace(/\$[^$\n]*?\$/g, ' ')   // maths is shown, not read
      .replace(/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}️‍]/gu, '')
      .replace(/[*_`#>]/g, '')
      .replace(/\s+/g, ' ').trim();
    if (!ttsOn || !clean) { once(); return; }        // speaker off: no request, no cost
    const ctl = window.AbortController ? new AbortController() : null;
    const timer = setTimeout(function () { if (ctl) ctl.abort(); }, TTS_WAIT);
    const t0 = Date.now();
    // no password here: the tts function has no password gate - never send it where it is not needed
    post(TTS_URL, { text: clean.slice(0, 4800), voice: VOICE, languageCode: 'de-DE', speakingRate: 1.0 },
         ctl ? ctl.signal : undefined)
      .then(function (r) { return r.json(); })
      .then(function (j) {
        clearTimeout(timer);
        if (!j || !j.audioContent) throw new Error('keine Stimme');
        addVoice(clean.length, Date.now() - t0);     // Google bills it even if it is not played
        once();
        if (!ttsOn || panel.hidden) return;          // switched off or closed while she was fetching
        stopAudio();
        audio = new Audio('data:audio/mp3;base64,' + j.audioContent);
        if (el) karaoke(el, audio);
        audio.play().catch(function () { });
      })
      .catch(function () {
        clearTimeout(timer);
        once();
        say('Solitas Stimme war gerade nicht erreichbar.', 'ask-err');
      });
  }
  function stopAudio() { if (audio) { try { audio.pause(); } catch (e) { } audio = null; } }

  function submit() {
    const v = input.value.trim();
    if (!v || busy) return;
    if (!pwd()) {                                   // first use on this device: verify and remember
      busy = true; send.disabled = true;
      post(AI_URL, { ping: true, pass: v })
        .then(function (r) {
          busy = false; send.disabled = false;
          if (!r.ok) { say('Passwort stimmt nicht.', 'ask-err'); input.value = ''; return; }
          try { localStorage.setItem('dev_access', v); } catch (e) { }
          askQuestion(); input.focus();
        })
        .catch(function () { busy = false; send.disabled = false; say('Kein Netz.', 'ask-err'); });
      return;
    }
    busy = true; send.disabled = true;
    if (ear && ear.active) ear.stop();               // nothing may land in the field behind the answer
    input.value = '';
    ready();
    say('<span class="ask-q">' + v.replace(/[<&]/g, function (c) { return c === '<' ? '&lt;' : '&amp;'; }) + '</span>');
    // the wave runs while Claude thinks AND while her voice is fetched - it gives way to the answer
    const wait = say('<span class="ask-wave" role="status" aria-label="Solita denkt nach">'
      + '<i></i><i></i><i></i><i></i><i></i><i></i><i></i></span>');
    const t0 = Date.now();
    post(AI_URL, { pass: pwd(), model: MODEL, max_tokens: 600,
      messages: [{ role: 'system', content: SYS }]
        .concat(hist.reduce(function (m, h) {
          return m.concat({ role: 'user', content: 'Frage der Klasse: ' + h.q },
                          { role: 'assistant', content: h.a });
        }, []))
        .concat({ role: 'user', content: context(v) + '\n\nFrage der Klasse: ' + v }) })
      .then(function (r) { return r.json().then(function (j) { return { ok: r.ok, j: j }; }); })
      .then(function (res) {
        const text = res.ok && res.j && res.j.choices && res.j.choices[0]
          && res.j.choices[0].message && res.j.choices[0].message.content;
        if (!text) {
          busy = false; send.disabled = false;
          wait.className = 'ask-err';
          wait.textContent = (res.j && res.j.error) ? String(res.j.error) : 'Das hat nicht geklappt.';
          return;
        }
        addClaude(res.j.usage, Date.now() - t0);
        hist.push({ q: v, a: text });
        if (hist.length > HIST_MAX) hist.shift();
        speak(text, function () {
          busy = false; send.disabled = false;
          render(wait, text);
          out.scrollTop = out.scrollHeight;
          input.value = ''; input.focus();           // done - empty line for the next question
          return wait;                               // karaoke lights up the words in here
        });
      })
      .catch(function () {
        busy = false; send.disabled = false;
        wait.className = 'ask-err'; wait.textContent = 'Kein Netz.';
      });
  }

  // Speaking the question: the shared engine from js/solita-listen.js (it survives mid-sentence
  // pauses and Android's cumulative results). Recognised text lands in the field - sending stays a
  // deliberate press, so a misheard question never costs money on its own.
  micBtn.innerHTML = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" '
    + 'stroke-linecap="round"><path d="M12 3a3 3 0 0 0-3 3v6a3 3 0 0 0 6 0V6a3 3 0 0 0-3-3z"/>'
    + '<path d="M5 11a7 7 0 0 0 14 0"/><path d="M12 18v3"/></svg>';
  if (!(window.SpeechRecognition || window.webkitSpeechRecognition)) micBtn.hidden = true;
  micBtn.onclick = function () {
    if (ear && ear.active) { ear.stop(); return; }
    if (!window.SolitaListen) { say('Spracheingabe ist hier nicht geladen.', 'ask-err'); return; }
    stopAudio();                                    // otherwise the mic hears Solita herself
    if (!ear) ear = window.SolitaListen({
      lang: 'de-DE',
      onState: function (st) { micBtn.classList.toggle('on', st === 'listening'); },
      onPartial: function (t) { input.value = t; ready(); },
      onFinal: function (t) { input.value = t; micBtn.classList.remove('on'); input.focus(); ready(); }
    });
    ear.start();
  };

  function open() {
    if (typeof narr !== 'undefined') narr.stop();   // asking pauses the talk, like turning a page
    panel.hidden = false;
    if (!pwd()) askPassword(); else askQuestion();
    input.focus();
    warm();
  }
  function close() { panel.hidden = true; stopAudio(); }

  document.getElementById('ask-btn').onclick = function () {
    this.classList.remove('invite');                 // found her - no more inviting on this page
    if (panel.hidden) open(); else close();
  };
  document.getElementById('ask-close').onclick = close;
  send.onclick = submit;
  // a question in the field makes the button breathe (not while Solita is busy, not for the password)
  function ready() { send.classList.toggle('ready', !busy && input.type === 'text' && input.value.trim() !== ''); }
  input.addEventListener('input', ready);
  input.addEventListener('keydown', function (e) {
    if (e.key === 'Enter') { e.preventDefault(); submit(); }
    else if (e.key === 'Escape') { e.preventDefault(); close(); }
  });
})();
