// DOCPAD service worker (generated by docpad/tools/pack_web.mjs): serves the files the password page decrypted into
// the Cache Storage, under ./app/ - with byte ranges, which Safari needs for audio.
// Opening the app it asks the server's password page for the current version; a newer one sends the device back there,
// which opens it with the remembered key (Doc 15.09.: an iPad kept an old version - without Cmd-Shift-R a reload only
// served the old cache again). Offline or slow: the version on the device opens as it is.
// A file of the list not on the device yet (Solita's voice: fetched when first played, Doc 08.10.2026) comes from the
// bucket, decrypted with the remembered key; once the app has started the rest follows quietly, so it plays offline too.
self.addEventListener('install', () => self.skipWaiting());
self.addEventListener('activate', e => e.waitUntil(self.clients.claim()));
const SCOPE = self.registration.scope, LOADER = new URL('../', SCOPE).href, STORE = 'https://fyfhxzyymmurlaenmzse.supabase.co/storage/v1/object/public/docpad/';
const fileUrl = h => SCOPE + '__f/' + h, META_URL = SCOPE + '__meta';
// "DPF1" | iv 12 | AES-GCM ciphertext -> the file's bytes, gunzipped where the list says z
async function unseal(key, bin, z) {
  if (String.fromCharCode(...bin.subarray(0, 4)) !== 'DPF1') throw new Error('Datei beschädigt');
  let plain;
  try { plain = await crypto.subtle.decrypt({ name: 'AES-GCM', iv: bin.subarray(4, 16) }, key, bin.subarray(16)); }
  catch (e) { const x = new Error('Schlüssel passt nicht'); x.key = true; throw x; }
  return z ? new Uint8Array(await new Response(new Blob([plain]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer()) : new Uint8Array(plain);
}
// the key remembered on this device (IndexedDB "docpad", store "keys": 'data'; 'base' = PBKDF2 key before 17.09.)
function idb(mode, fn) {
  return new Promise((res, rej) => {
    const rq = indexedDB.open('docpad', 1);
    rq.onupgradeneeded = () => rq.result.createObjectStore('keys');
    rq.onerror = () => rej(rq.error);
    rq.onsuccess = () => {
      const db = rq.result, tx = db.transaction('keys', mode), r = fn(tx.objectStore('keys'));
      tx.oncomplete = () => { db.close(); res(r.result); };
      tx.onerror = tx.onabort = () => { db.close(); rej(tx.error); };
    };
  });
}
const loadKey = name => idb('readonly', s => s.get(name)).catch(() => null);
// the cache "docpad-files" holds every file under its name, "docpad-meta" the list of the version on this device
const FILES = 'docpad-files', META = 'docpad-meta';
let bounced = '', meta = null;                           // bounced: one detour per new version, so never a loop
async function latest() {                                // VERSION of the password page on the server, '' if unknown
  const ctl = new AbortController(), t = setTimeout(() => ctl.abort(), 2500);
  try {
    const res = await fetch(LOADER + 'index.html', { cache: 'no-store', signal: ctl.signal });
    const m = res.ok && /const VERSION = '([0-9a-f]+)'/.exec(await res.text());
    return m ? m[1] : '';
  } catch (e) { return ''; } finally { clearTimeout(t); }
}
async function current(fresh) {                          // {v, files: path -> entry} of the version on this device
  if (meta && !fresh) return meta;
  const r = await caches.open(META).then(c => c.match(META_URL)).catch(() => null), j = r && await r.json().catch(() => null);
  meta = j && { v: j.v, files: new Map(j.files.map(f => [f.p, f])) };
  return meta;
}
const loading = new Map();                               // name -> its download, so a file is fetched once however often asked for
function fetchIn(f) {                                    // a file of the list from the bucket into the cache
  if (!loading.has(f.h)) loading.set(f.h, (async () => {
    const c = await caches.open(FILES);
    if (await c.match(fileUrl(f.h))) return;
    const key = await loadKey('data');
    if (!key) throw new Error('no key on this device');
    const res = await fetch(STORE + 'f/' + f.h + '.bin');
    if (!res.ok) throw new Error('bucket ' + res.status);
    await c.put(fileUrl(f.h), new Response(await unseal(key, new Uint8Array(await res.arrayBuffer()), f.z), { headers: { 'Content-Type': f.t } }));
  })().finally(() => loading.delete(f.h)));
  return loading.get(f.h);
}
let filling = null;
function fillIn() {                                      // what the device does not hold yet, a few at a time, after the app's start
  return filling || (filling = (async () => {
    await new Promise(r => setTimeout(r, 3000));
    const m = await current();
    if (!m) return;
    const have = new Set((await (await caches.open(FILES)).keys()).map(r => r.url)), todo = new Map();
    for (const f of m.files.values()) if (!have.has(fileUrl(f.h))) todo.set(f.h, f);
    const all = [...todo.values()];
    let i = 0;
    await Promise.all([0, 1, 2, 3].map(async () => { while (i < all.length) await fetchIn(all[i++]).catch(() => {}); }));
  })().finally(() => { filling = null; }));
}
async function serve(req, url, nav) {
  const m = await current(nav);                          // read anew when the app opens: the password page may have set up a new version
  if (nav) {
    const v = await latest();
    // ?v= is a fresh URL, so a password page still in the HTTP cache (GitHub Pages: 10 min) cannot answer
    if (v && v !== bounced && (!m || m.v !== v)) { bounced = v; return Response.redirect(LOADER + '?v=' + v, 302); }
  }
  const path = url.pathname.endsWith('/') ? url.pathname + 'docpad.html' : url.pathname;   // the calculator (web/index.html only forwards)
  let p = path.slice(new URL(SCOPE).pathname.length);
  try { p = decodeURIComponent(p); } catch (e) { /* as it is */ }
  const f = m && m.files.get(p), c = await caches.open(FILES);
  let hit = f ? await c.match(fileUrl(f.h)) : await caches.match(url.origin + path);   // not in the list: what the app keeps itself
  if (!hit && f) { await fetchIn(f).catch(() => {}); hit = await c.match(fileUrl(f.h)); }
  if (!hit) return new Response('DOCPAD: ' + path + ' not found - please open the page again', { status: 404 });
  const range = req.headers.get('range');
  if (!range) return hit;
  const buf = await hit.arrayBuffer(), r = /bytes=(\d*)-(\d*)/.exec(range) || [];
  const start = r[1] ? +r[1] : 0, end = Math.min(r[2] ? +r[2] : buf.byteLength - 1, buf.byteLength - 1);
  return new Response(buf.slice(start, end + 1), { status: 206, headers: { 'Content-Type': hit.headers.get('Content-Type'),
    'Content-Range': 'bytes ' + start + '-' + end + '/' + buf.byteLength, 'Content-Length': String(end - start + 1), 'Accept-Ranges': 'bytes' } });
}
self.addEventListener('fetch', e => {
  const url = new URL(e.request.url);
  if (url.origin !== location.origin || !url.pathname.startsWith(new URL(SCOPE).pathname)) return;
  const nav = e.request.mode === 'navigate' && e.request.destination === 'document';   // opening the app, not its iframes
  const answer = serve(e.request, url, nav);
  e.respondWith(answer);
  if (nav) e.waitUntil(answer.then(r => r.status === 302 || fillIn()).catch(() => {}));
});
