// DOCPAD service worker (generated by docpad/tools/pack_web.mjs): serves the files the password page decrypted into
// the Cache Storage, under ./app/ - with byte ranges, which Safari needs for audio.
// Opening the app it asks the server's password page for the current bundle; a newer one sends the device back there,
// which opens it with the remembered key (Doc 15.09.: an iPad kept an old version - without Cmd-Shift-R a reload only
// served the old cache again). Offline or slow: the unlocked bundle opens as it is.
self.addEventListener('install', () => self.skipWaiting());
self.addEventListener('activate', e => e.waitUntil(self.clients.claim()));
const LOADER = new URL('../', self.registration.scope).href;
let bounced = '';                                        // one detour per new bundle, so never a loop
async function latest() {                                // VERSION of the password page on the server, '' if unknown
  const ctl = new AbortController(), t = setTimeout(() => ctl.abort(), 2500);
  try {
    const res = await fetch(LOADER + 'index.html', { cache: 'no-store', signal: ctl.signal });
    const m = res.ok && /const VERSION = '([0-9a-f]+)'/.exec(await res.text());
    return m ? m[1] : '';
  } catch (e) { return ''; } finally { clearTimeout(t); }
}
self.addEventListener('fetch', e => {
  const url = new URL(e.request.url);
  if (url.origin !== location.origin || !url.pathname.startsWith(new URL(self.registration.scope).pathname)) return;
  e.respondWith((async () => {
    if (e.request.mode === 'navigate' && e.request.destination === 'document') {   // opening the app, not its iframes
      const v = await latest();
      // ?v= is a fresh URL, so a password page still in the HTTP cache (GitHub Pages: 10 min) cannot answer
      if (v && v !== bounced && !(await caches.has('docpad-' + v))) { bounced = v; return Response.redirect(LOADER + '?v=' + v, 302); }
    }
    const path = url.pathname.endsWith('/') ? url.pathname + 'index.html' : url.pathname;
    const hit = await caches.match(url.origin + path);
    if (!hit) return new Response('DOCPAD: ' + path + ' not found - please open the page again', { status: 404 });
    const range = e.request.headers.get('range');
    if (!range) return hit;
    const buf = await hit.arrayBuffer(), m = /bytes=(\d*)-(\d*)/.exec(range) || [];
    const start = m[1] ? +m[1] : 0, end = Math.min(m[2] ? +m[2] : buf.byteLength - 1, buf.byteLength - 1);
    return new Response(buf.slice(start, end + 1), { status: 206, headers: { 'Content-Type': hit.headers.get('Content-Type'),
      'Content-Range': 'bytes ' + start + '-' + end + '/' + buf.byteLength, 'Content-Length': String(end - start + 1), 'Accept-Ranges': 'bytes' } });
  })());
});
