// DOCPAD service worker (generated by docpad/tools/pack_web.mjs): serves the files the password page decrypted into
// the Cache Storage, under ./app/ - with byte ranges, which Safari needs for audio.
self.addEventListener('install', () => self.skipWaiting());
self.addEventListener('activate', e => e.waitUntil(self.clients.claim()));
self.addEventListener('fetch', e => {
  const url = new URL(e.request.url);
  if (url.origin !== location.origin || !url.pathname.startsWith(new URL(self.registration.scope).pathname)) return;
  e.respondWith((async () => {
    const path = url.pathname.endsWith('/') ? url.pathname + 'index.html' : url.pathname;
    const hit = await caches.match(url.origin + path);
    if (!hit) return new Response('DOCPAD: ' + path + ' not found - please open the page again', { status: 404 });
    const range = e.request.headers.get('range');
    if (!range) return hit;
    const buf = await hit.arrayBuffer(), m = /bytes=(\d*)-(\d*)/.exec(range) || [];
    const start = m[1] ? +m[1] : 0, end = Math.min(m[2] ? +m[2] : buf.byteLength - 1, buf.byteLength - 1);
    return new Response(buf.slice(start, end + 1), { status: 206, headers: { 'Content-Type': hit.headers.get('Content-Type'),
      'Content-Range': 'bytes ' + start + '-' + end + '/' + buf.byteLength, 'Content-Length': String(end - start + 1), 'Accept-Ranges': 'bytes' } });
  })());
});
