#!/usr/bin/env python3
"""Weekly practice sheets (20 tasks) for BGY Informatik, Jahrgangsstufe 11.

Uebungsblatt, not a test: no "Abgeben" button, every solution readable right
away (submit=False, solutions='always') - same mode as the Mathe-11 sheets.
The page markup, scoring and the teacher dashboard live in js/quiz-engine.js;
this generator only carries the questions.

    python3 tools/build_inf11_aufgaben.py

Question tuple: (text, correct, [3 wrong], [solution steps])
"""
import hashlib, json, os, random

HERE = os.path.dirname(os.path.abspath(__file__))
HTML = os.path.join(os.path.dirname(HERE), "HTML")
GEN = "tools/build_inf11_aufgaben.py"

INF11 = {
    "qid": "inf11", "file": "inf11test",
    "subtitle": "Berufliches Gymnasium · Jahrgangsstufe 11",
    "dash": "BGY · Klasse 11",
    "back": "svp/informatik/inf11.html",
}

TEMPLATE = """<!DOCTYPE html>
<html lang="de">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Aufgaben: %(topic)s &mdash; Doc Alvers Mathe-Labor</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@500;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css">
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js"></script>
<link rel="stylesheet" href="js/quiz.css">
    <link rel="icon" type="image/svg+xml" href="resources/favicon.svg">
    <link rel="icon" type="image/png" sizes="256x256" href="resources/favicon.png">
</head>
<body>
<!-- Page markup, scoring, statistics and the teacher dashboard live in
     js/quiz-engine.js — this file only carries the questions.
     Generated by %(gen)s - edit the questions there. -->
<script>
window.QUIZ = %(json)s;
</script>
<script src="js/quiz-collapse.js"></script>
<script src="js/quiz-engine.js"></script>
</body>
</html>
"""


def build(slug, nr, kw, lb, topic, blurb, qs, course=INF11):
    qid = f"{course['qid']}-w{nr:02d}-{slug}"
    # Deal each letter five times and shuffle that deal deterministically from
    # the sheet id: unbiased per question AND never a sheet without a D.
    rnd = random.Random(qid)
    slots = [i % 4 for i in range(len(qs))]
    rnd.shuffle(slots)
    questions = []
    for i, (q, right, wrong, steps) in enumerate(qs, 1):
        assert len(wrong) == 3 and len({right, *wrong}) == 4, (qid, i)
        assert "</script>" not in (q + right + "".join(wrong) + "".join(steps)), (qid, i)
        opts = list(wrong)
        opts.insert(slots[i - 1], right)
        questions.append({"q": q, "opts": opts, "steps": steps, "solution": slots[i - 1]})
    quiz = {
        "id": qid, "version": "v1",
        "submit": False,          # Uebungsblatt der Woche: kein Abgeben
        "solutions": "always",    # Loesung pro Aufgabe sofort aufklappbar
        "title": f"Aufgaben · {topic}",
        "subtitle": f"{course['subtitle']} · Woche {nr} ({lb}) · {len(qs)} Aufgaben: "
                    f"{blurb} · genau eine Antwort pro Aufgabe",
        "dashSub": f"{course['dash']} · Woche {nr} · Live-Auswertung: anonyme Einzelscores "
                   f"+ Gruppenleistung pro Aufgabe",
        "back": course["back"],
        "questions": questions,
    }
    path = os.path.join(HTML, f"{course['file']}-{slug}.html")
    with open(path, "w") as f:
        f.write(TEMPLATE % {"topic": topic, "gen": GEN,
                            "json": json.dumps(quiz, ensure_ascii=False, indent=2)})
    return path, [q["solution"] for q in questions]


# Week 4 / KW 37, LB 1 (Ustd. 3-4/6) - week numbers follow the LIVE plan in
# Supabase, which runs one week ahead of the PLAN array in inf11.html. The four Wissenschaftsbereiche and their
# contents follow the Saechsischer Lehrplan BGY Informatik (2020), LB 1:
#   theoretisch  - Loesbarkeit und Komplexitaet, Sprachen und Automaten
#   technisch    - Hardware und Betriebssystem
#   praktisch    - Software Engineering
#   angewandt    - informatische Methoden in informatikfremden Gebieten
BILDUNGSINHALT = [
 # ---------------------------------------------- 1-7: informatikfremde Gebiete
 ("In welchem Wissenschaftsbereich der Informatik steht der „Einsatz informatischer Methoden "
  "in informatikfremden Gebieten“?",
  "Angewandte Informatik",
  ["Theoretische Informatik", "Technische Informatik", "Praktische Informatik"],
  ["„Informatikfremd“ heißt: das Problem kommt aus einem anderen Fach — Medizin, Physik, Sprache.",
   "Die angewandte Informatik ist der Bereich, der die Methoden der anderen drei dorthin trägt."]),

 ("Ein Computertomograf misst nur, wie stark Röntgenstrahlen aus vielen Richtungen geschwächt "
  "werden. Wie entsteht daraus das Schnittbild?",
  "Ein Rechenverfahren rekonstruiert das Bild aus den vielen Projektionen",
  ["Der Detektor fotografiert die Schnittebene direkt",
   "Ein Kontrastmittel färbt die Schnittebene ein",
   "Ein Magnetfeld richtet die Schnittebene aus"],
  ["Gemessen werden Summen entlang von Strahlen, nicht Bildpunkte.",
   "Aus den Projektionen wird das Bild berechnet (Radon-Transformation, gefilterte Rückprojektion) "
   "— ohne Informatik gäbe es kein CT-Bild."]),

 ("Wofür wurde das World Wide Web ursprünglich entwickelt?",
  "Damit Physikerinnen und Physiker am CERN ihre Dokumente austauschen können",
  ["Als Werbeplattform für Softwarefirmen",
   "Als Ersatz für das Telefonnetz der Universitäten",
   "Als Steuerungssystem für Teilchenbeschleuniger"],
  ["Tim Berners-Lee schrieb den Vorschlag 1989 am CERN, einem Physiklabor.",
   "Ein Musterfall für angewandte Informatik: Das Problem kam aus der Physik, "
   "die Lösung veränderte die ganze Welt."]),

 ("Was macht ein Sequenzalignment in der Bioinformatik?",
  "Es richtet zwei Zeichenketten so aneinander aus, dass möglichst viele Stellen übereinstimmen",
  ["Es misst die Masse eines Proteins",
   "Es färbt Zellkerne für das Mikroskop ein",
   "Es sortiert Patientendaten nach Geburtsdatum"],
  ["DNA ist für den Rechner eine Zeichenkette aus A, C, G und T.",
   "Damit wird aus einer biologischen Frage ein Zeichenketten-Problem der Informatik."]),

 ("Ein Programm zerlegt einen Satz zuerst in seine Wörter und Satzzeichen. "
  "Wie heißt dieser Schritt in der Computerlinguistik?",
  "Tokenisierung",
  ["Kompilierung", "Normalisierung", "Indizierung"],
  ["Ein Token ist die kleinste Einheit, mit der weitergerechnet wird.",
   "Erst danach folgen Wortarten-Bestimmung und Satzbau-Analyse."]),

 ("Das Zipfsche Gesetz beschreibt eine Beobachtung über Sprache. Welche?",
  "Wenige Wörter kommen sehr häufig vor, sehr viele Wörter nur selten",
  ["Jede Sprache hat gleich viele Vokale wie Konsonanten",
   "Sätze werden im Lauf der Sprachgeschichte immer länger",
   "Jedes Wort hat in jeder Sprache genau eine Übersetzung"],
  ["Zählt man Wörter in einem Text und ordnet sie nach Häufigkeit, fällt die Kurve steil ab.",
   "Solche Statistiken sind die Grundlage von Suchmaschinen und Sprachmodellen."]),

 ("Warum nennt man die Computersimulation oft die „dritte Säule“ der Naturwissenschaft?",
  "Weil sie neben Theorie und Experiment tritt und Fälle untersucht, die man nicht messen kann",
  ["Weil sie immer genauer ist als ein Experiment",
   "Weil sie Theorie und Experiment überflüssig macht",
   "Weil sie erst als drittes Fach an der Universität eingeführt wurde"],
  ["Ein Klima über 100 Jahre oder eine Sternexplosion lässt sich nicht im Labor nachstellen.",
   "Die Simulation ersetzt die beiden anderen Säulen nicht, sie ergänzt sie."]),

 # ------------------------------------- 8-14: Zuordnung zu den Wissenschaftsbereichen
 ("Zu welchem Wissenschaftsbereich gehören nach dem Lehrplan Hardware und Betriebssystem?",
  "Technische Informatik",
  ["Praktische Informatik", "Theoretische Informatik", "Angewandte Informatik"],
  ["Der Lehrplan nennt unter „Technische Informatik“ ausdrücklich Hardware und Betriebssystem.",
   "Aufgepasst: Viele Lehrbücher zählen Betriebssysteme zur praktischen Informatik. "
   "In dieser Klasse gilt die Zuordnung des Lehrplans."]),

 ("Zu welchem Wissenschaftsbereich gehört Software Engineering?",
  "Praktische Informatik",
  ["Technische Informatik", "Theoretische Informatik", "Angewandte Informatik"],
  ["Software Engineering fragt: Wie baut man große Programme planvoll und wartbar?",
   "Die praktische Informatik ist der Bereich des Herstellens von Software."]),

 ("„Sprachen und Automaten“ sowie „Probleme der Lösbarkeit und Komplexität“ — welcher Bereich?",
  "Theoretische Informatik",
  ["Praktische Informatik", "Technische Informatik", "Angewandte Informatik"],
  ["Hier wird bewiesen, nicht gebaut: Was ist überhaupt berechenbar, und wie teuer ist es?",
   "Die Ergebnisse gelten unabhängig von jedem konkreten Rechner."]),

 ("Ein Team entwirft den Schaltplan eines Prozessors. Welcher Bereich?",
  "Technische Informatik",
  ["Praktische Informatik", "Theoretische Informatik", "Angewandte Informatik"],
  ["Die Frage lautet: Wie ist der Rechner selbst gebaut?",
   "Technische Informatik steht an der Grenze zur Elektrotechnik."]),

 ("Ein Team plant für ein Krankenhaus eine Software zur Terminvergabe: Anforderungen, "
  "Zeitplan, Tests, Wartung. Welcher Bereich beschreibt diese Arbeit?",
  "Praktische Informatik (Software Engineering)",
  ["Technische Informatik (Hardware)",
   "Theoretische Informatik (Berechenbarkeit)",
   "Gar keiner — das ist reine Medizin"],
  ["Gefragt ist nicht das Krankenhaus, sondern die Art der Tätigkeit: planvoll Software bauen.",
   "Erst wenn medizinische Fachfragen die Methode bestimmen, wird daraus angewandte Informatik."]),

 ("Warum ist ein und dasselbe Projekt oft mehreren Wissenschaftsbereichen zuzuordnen?",
  "Weil ein reales Projekt Anteile aus mehreren Bereichen enthält und die Grenzen fließend sind",
  ["Weil die Bereiche in jedem Bundesland anders heißen",
   "Weil sich die Bereiche jedes Jahr ändern",
   "Weil nur Fachleute die Bereiche unterscheiden dürfen"],
  ["Eine Wetter-App braucht Modelle (theoretisch), Server (technisch), Code (praktisch) "
   "und Meteorologie (angewandt).",
   "Bei der Zuordnung zählt der Schwerpunkt der Frage — und die Begründung."]),

 ("Welche der folgenden Bezeichnungen ist keine der üblichen „Bindestrich-Informatiken“?",
  "Komplexitäts-Informatik",
  ["Medizinische Informatik", "Wirtschaftsinformatik", "Geoinformatik"],
  ["Bindestrich-Informatiken benennen ein Anwendungsfeld: Medizin, Wirtschaft, Geografie, Recht.",
   "Komplexität ist kein Anwendungsfeld, sondern ein Thema der theoretischen Informatik."]),

 # --------------------------------- 15-20: Bildungsinhalt, Beurteilen, Mini-Vortrag
 ("Was ist gemeint, wenn man Informatik als „Medium anderer Wissenschaftszweige“ bezeichnet?",
  "Andere Fächer benutzen informatische Methoden als Werkzeug, um ihre eigenen Fragen zu klären",
  ["Informatik berichtet in den Medien über andere Fächer",
   "Andere Fächer werden durch die Informatik ersetzt",
   "Informatik ist ein Unterrichtsfach wie jedes andere"],
  ["Medium heißt hier Mittel, nicht Presse.",
   "Die Frage bleibt die der Medizin oder der Physik — nur der Weg zur Antwort führt über den Rechner."]),

 ("Was unterscheidet angewandte Informatik davon, einfach ein fertiges Programm zu benutzen?",
  "In der angewandten Informatik werden die Methoden für das fremde Fach ausgewählt, angepasst "
  "und beurteilt",
  ["Angewandte Informatik benutzt ausschließlich selbst geschriebene Programme",
   "Angewandte Informatik kommt ohne Computer aus",
   "Es gibt keinen Unterschied"],
  ["Wer eine Tabellenkalkulation bedient, wendet an — aber gestaltet keine Methode.",
   "Angewandte Informatik heißt: das Problem modellieren, ein Verfahren wählen und "
   "sein Ergebnis kritisch prüfen."]),

 ("Bei der Stilometrie werden Texte automatisch ausgewertet, um die Verfasserin oder den "
  "Verfasser zu bestimmen. Worauf stützt sich das Verfahren vor allem?",
  "Auf messbare Merkmale wie Wortlängen und die Häufigkeit unauffälliger Funktionswörter",
  ["Auf die Handschrift im Original",
   "Auf das Erscheinungsjahr des Buches",
   "Auf die Meinung der Literaturwissenschaft"],
  ["Gerade unbewusste Kleinigkeiten wie „und“, „aber“, „doch“ verraten den Stil.",
   "Ein schönes Beispiel dafür, wie Informatik einer geisteswissenschaftlichen Frage dient."]),

 ("Ein Röntgenbild wird digitalisiert. Welche zwei Schritte gehören dazu?",
  "Abtasten in einem Raster und Quantisieren der Helligkeitswerte",
  ["Vergrößern und Ausdrucken",
   "Verschlüsseln und Komprimieren",
   "Übersetzen und Formatieren"],
  ["Abtasten legt fest, wie fein das Raster ist (Bildpunkte).",
   "Quantisieren legt fest, wie viele Helligkeitsstufen jeder Punkt bekommt."]),

 ("Warum reicht es für eine gute Beurteilung nicht, ein Beispiel nur einem Bereich zuzuordnen?",
  "Weil zur Zuordnung eine Begründung gehört, die den Schwerpunkt des Beispiels benennt",
  ["Weil man immer alle vier Bereiche nennen muss",
   "Weil Zuordnungen grundsätzlich Geschmackssache sind",
   "Weil nur die Länge der Antwort zählt"],
  ["Der Operator „zuordnen“ verlangt die Entscheidung, „begründen“ verlangt den Grund.",
   "Zwei Sätze genügen: Was ist die Kernfrage, und welcher Bereich beantwortet sie?"]),

 ("Ihr haltet zu zweit einen Mini-Vortrag über ein informatikfremdes Anwendungsgebiet. "
  "Was gehört auf jeden Fall hinein?",
  "Das fremde Fachproblem, die eingesetzte informatische Methode und die Zuordnung zu einem Bereich",
  ["Eine vollständige Biografie der beteiligten Forscherinnen und Forscher",
   "Der Quelltext des benutzten Programms",
   "Eine Liste aller Fachbegriffe ohne Erklärung"],
  ["Erst die Frage aus dem fremden Fach, dann der informatische Weg, dann die Einordnung.",
   "Und immer die Quelle nennen — Kurzrecherche heißt nicht raten."]),
]


if __name__ == "__main__":
    path, sol = build("bildungsinhalt", 4, 37, "LB 1",
                      "Informatik als Bildungsinhalt und Medium anderer Wissenschaftszweige",
                      "informatische Methoden in Physik, Medizin und Sprache; Zuordnung zu den "
                      "vier Wissenschaftsbereichen",
                      BILDUNGSINHALT)
    print(os.path.basename(path), len(BILDUNGSINHALT), "Aufgaben, Lösungen:",
          "".join("ABCD"[s] for s in sol))
