#!/usr/bin/env python3
"""Weekly practice sheets (20 tasks) for BGY Informatik, Jahrgangsstufe 11.

Uebungsblatt, not a test - but it keeps its submit button, labelled
"Auswertung", so the class can see its own score (solutions='always')
- same mode as the Mathe-11 sheets.
The page markup, scoring and the teacher dashboard live in js/quiz-engine.js;
this generator only carries the questions.

    python3 tools/build_inf11_aufgaben.py

Question tuple: (text, correct, [3 wrong], [solution steps])
"""
import hashlib, json, os, random

HERE = os.path.dirname(os.path.abspath(__file__))
HTML = os.path.join(os.path.dirname(HERE), "HTML")
GEN = "tools/build_inf11_aufgaben.py"

INF11 = {
    "qid": "inf11", "file": "inf11test",
    "subtitle": "Berufliches Gymnasium · Jahrgangsstufe 11",
    "dash": "BGY · Klasse 11",
    "back": "svp/informatik/inf11.html",
}

TEMPLATE = """<!DOCTYPE html>
<html lang="de">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Aufgaben: %(topic)s &mdash; Doc Alvers Mathe-Labor</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@500;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css">
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js"></script>
<link rel="stylesheet" href="js/quiz.css">
    <link rel="icon" type="image/svg+xml" href="resources/favicon.svg">
    <link rel="icon" type="image/png" sizes="256x256" href="resources/favicon.png">
</head>
<body>
<!-- Page markup, scoring, statistics and the teacher dashboard live in
     js/quiz-engine.js — this file only carries the questions.
     Generated by %(gen)s - edit the questions there. -->
<script>
window.QUIZ = %(json)s;
</script>
<script src="js/quiz-collapse.js"></script>
<script src="js/quiz-engine.js"></script>
</body>
</html>
"""


def build(slug, nr, kw, lb, topic, blurb, qs, course=INF11):
    qid = f"{course['qid']}-w{nr:02d}-{slug}"
    # Deal each letter five times and shuffle that deal deterministically from
    # the sheet id: unbiased per question AND never a sheet without a D.
    rnd = random.Random(qid)
    slots = [i % 4 for i in range(len(qs))]
    rnd.shuffle(slots)
    questions = []
    for i, (q, right, wrong, steps) in enumerate(qs, 1):
        assert len(wrong) == 3 and len({right, *wrong}) == 4, (qid, i)
        assert "</script>" not in (q + right + "".join(wrong) + "".join(steps)), (qid, i)
        opts = list(wrong)
        opts.insert(slots[i - 1], right)
        questions.append({"q": q, "opts": opts, "steps": steps, "solution": slots[i - 1]})
    quiz = {
        "id": qid, "version": "v1",
        "submitLabel": "Auswertung",  # Uebungsblatt: der Knopf heisst Auswertung
        "solutions": "always",    # Loesung pro Aufgabe sofort aufklappbar
        "title": f"Aufgaben · {topic}",
        "subtitle": f"{course['subtitle']} · Woche {nr} ({lb}) · {len(qs)} Aufgaben: "
                    f"{blurb} · genau eine Antwort pro Aufgabe",
        "dashSub": f"{course['dash']} · Woche {nr} · Live-Auswertung: anonyme Einzelscores "
                   f"+ Gruppenleistung pro Aufgabe",
        "back": course["back"],
        "questions": questions,
    }
    path = os.path.join(HTML, f"{course['file']}-{slug}.html")
    with open(path, "w") as f:
        f.write(TEMPLATE % {"topic": topic, "gen": GEN,
                            "json": json.dumps(quiz, ensure_ascii=False, indent=2)})
    return path, [q["solution"] for q in questions]


# Week 4 / KW 37, LB 1 (Ustd. 3-4/6) - week numbers follow the LIVE plan in
# Supabase, which runs one week ahead of the PLAN array in inf11.html. The four Wissenschaftsbereiche and their
# contents follow the Saechsischer Lehrplan BGY Informatik (2020), LB 1:
#   theoretisch  - Loesbarkeit und Komplexitaet, Sprachen und Automaten
#   technisch    - Hardware und Betriebssystem
#   praktisch    - Software Engineering
#   angewandt    - informatische Methoden in informatikfremden Gebieten
BILDUNGSINHALT = [
 # ---------------------------------------------- 1-7: informatikfremde Gebiete
 ("In welchem Wissenschaftsbereich der Informatik steht der „Einsatz informatischer Methoden "
  "in informatikfremden Gebieten“?",
  "Angewandte Informatik",
  ["Theoretische Informatik", "Technische Informatik", "Praktische Informatik"],
  ["„Informatikfremd“ heißt: das Problem kommt aus einem anderen Fach — Medizin, Physik, Sprache.",
   "Die angewandte Informatik ist der Bereich, der die Methoden der anderen drei dorthin trägt."]),

 ("Ein Computertomograf misst nur, wie stark Röntgenstrahlen aus vielen Richtungen geschwächt "
  "werden. Wie entsteht daraus das Schnittbild?",
  "Ein Rechenverfahren rekonstruiert das Bild aus den vielen Projektionen",
  ["Der Detektor fotografiert die Schnittebene direkt",
   "Ein Kontrastmittel färbt die Schnittebene ein",
   "Ein Magnetfeld richtet die Schnittebene aus"],
  ["Gemessen werden Summen entlang von Strahlen, nicht Bildpunkte.",
   "Aus den Projektionen wird das Bild berechnet (Radon-Transformation, gefilterte Rückprojektion) "
   "— ohne Informatik gäbe es kein CT-Bild."]),

 ("Wofür wurde das World Wide Web ursprünglich entwickelt?",
  "Damit Physikerinnen und Physiker am CERN ihre Dokumente austauschen können",
  ["Als Werbeplattform für Softwarefirmen",
   "Als Ersatz für das Telefonnetz der Universitäten",
   "Als Steuerungssystem für Teilchenbeschleuniger"],
  ["Tim Berners-Lee schrieb den Vorschlag 1989 am CERN, einem Physiklabor.",
   "Ein Musterfall für angewandte Informatik: Das Problem kam aus der Physik, "
   "die Lösung veränderte die ganze Welt."]),

 ("Was macht ein Sequenzalignment in der Bioinformatik?",
  "Es richtet zwei Zeichenketten so aneinander aus, dass möglichst viele Stellen übereinstimmen",
  ["Es misst die Masse eines Proteins",
   "Es färbt Zellkerne für das Mikroskop ein",
   "Es sortiert Patientendaten nach Geburtsdatum"],
  ["DNA ist für den Rechner eine Zeichenkette aus A, C, G und T.",
   "Damit wird aus einer biologischen Frage ein Zeichenketten-Problem der Informatik."]),

 ("Ein Programm zerlegt einen Satz zuerst in seine Wörter und Satzzeichen. "
  "Wie heißt dieser Schritt in der Computerlinguistik?",
  "Tokenisierung",
  ["Kompilierung", "Normalisierung", "Indizierung"],
  ["Ein Token ist die kleinste Einheit, mit der weitergerechnet wird.",
   "Erst danach folgen Wortarten-Bestimmung und Satzbau-Analyse."]),

 ("Das Zipfsche Gesetz beschreibt eine Beobachtung über Sprache. Welche?",
  "Wenige Wörter kommen sehr häufig vor, sehr viele Wörter nur selten",
  ["Jede Sprache hat gleich viele Vokale wie Konsonanten",
   "Sätze werden im Lauf der Sprachgeschichte immer länger",
   "Jedes Wort hat in jeder Sprache genau eine Übersetzung"],
  ["Zählt man Wörter in einem Text und ordnet sie nach Häufigkeit, fällt die Kurve steil ab.",
   "Solche Statistiken sind die Grundlage von Suchmaschinen und Sprachmodellen."]),

 ("Warum nennt man die Computersimulation oft die „dritte Säule“ der Naturwissenschaft?",
  "Weil sie neben Theorie und Experiment tritt und Fälle untersucht, die man nicht messen kann",
  ["Weil sie immer genauer ist als ein Experiment",
   "Weil sie Theorie und Experiment überflüssig macht",
   "Weil sie erst als drittes Fach an der Universität eingeführt wurde"],
  ["Ein Klima über 100 Jahre oder eine Sternexplosion lässt sich nicht im Labor nachstellen.",
   "Die Simulation ersetzt die beiden anderen Säulen nicht, sie ergänzt sie."]),

 # ------------------------------------- 8-14: Zuordnung zu den Wissenschaftsbereichen
 ("Zu welchem Wissenschaftsbereich gehören nach dem Lehrplan Hardware und Betriebssystem?",
  "Technische Informatik",
  ["Praktische Informatik", "Theoretische Informatik", "Angewandte Informatik"],
  ["Der Lehrplan nennt unter „Technische Informatik“ ausdrücklich Hardware und Betriebssystem.",
   "Aufgepasst: Viele Lehrbücher zählen Betriebssysteme zur praktischen Informatik. "
   "In dieser Klasse gilt die Zuordnung des Lehrplans."]),

 ("Zu welchem Wissenschaftsbereich gehört Software Engineering?",
  "Praktische Informatik",
  ["Technische Informatik", "Theoretische Informatik", "Angewandte Informatik"],
  ["Software Engineering fragt: Wie baut man große Programme planvoll und wartbar?",
   "Die praktische Informatik ist der Bereich des Herstellens von Software."]),

 ("„Sprachen und Automaten“ sowie „Probleme der Lösbarkeit und Komplexität“ — welcher Bereich?",
  "Theoretische Informatik",
  ["Praktische Informatik", "Technische Informatik", "Angewandte Informatik"],
  ["Hier wird bewiesen, nicht gebaut: Was ist überhaupt berechenbar, und wie teuer ist es?",
   "Die Ergebnisse gelten unabhängig von jedem konkreten Rechner."]),

 ("Ein Team entwirft den Schaltplan eines Prozessors. Welcher Bereich?",
  "Technische Informatik",
  ["Praktische Informatik", "Theoretische Informatik", "Angewandte Informatik"],
  ["Die Frage lautet: Wie ist der Rechner selbst gebaut?",
   "Technische Informatik steht an der Grenze zur Elektrotechnik."]),

 ("Ein Team plant für ein Krankenhaus eine Software zur Terminvergabe: Anforderungen, "
  "Zeitplan, Tests, Wartung. Welcher Bereich beschreibt diese Arbeit?",
  "Praktische Informatik (Software Engineering)",
  ["Technische Informatik (Hardware)",
   "Theoretische Informatik (Berechenbarkeit)",
   "Gar keiner — das ist reine Medizin"],
  ["Gefragt ist nicht das Krankenhaus, sondern die Art der Tätigkeit: planvoll Software bauen.",
   "Erst wenn medizinische Fachfragen die Methode bestimmen, wird daraus angewandte Informatik."]),

 ("Warum ist ein und dasselbe Projekt oft mehreren Wissenschaftsbereichen zuzuordnen?",
  "Weil ein reales Projekt Anteile aus mehreren Bereichen enthält und die Grenzen fließend sind",
  ["Weil die Bereiche in jedem Bundesland anders heißen",
   "Weil sich die Bereiche jedes Jahr ändern",
   "Weil nur Fachleute die Bereiche unterscheiden dürfen"],
  ["Eine Wetter-App braucht Modelle (theoretisch), Server (technisch), Code (praktisch) "
   "und Meteorologie (angewandt).",
   "Bei der Zuordnung zählt der Schwerpunkt der Frage — und die Begründung."]),

 ("Welche der folgenden Bezeichnungen ist keine der üblichen „Bindestrich-Informatiken“?",
  "Komplexitäts-Informatik",
  ["Medizinische Informatik", "Wirtschaftsinformatik", "Geoinformatik"],
  ["Bindestrich-Informatiken benennen ein Anwendungsfeld: Medizin, Wirtschaft, Geografie, Recht.",
   "Komplexität ist kein Anwendungsfeld, sondern ein Thema der theoretischen Informatik."]),

 # --------------------------------- 15-20: Bildungsinhalt, Beurteilen, Mini-Vortrag
 ("Was ist gemeint, wenn man Informatik als „Medium anderer Wissenschaftszweige“ bezeichnet?",
  "Andere Fächer benutzen informatische Methoden als Werkzeug, um ihre eigenen Fragen zu klären",
  ["Informatik berichtet in den Medien über andere Fächer",
   "Andere Fächer werden durch die Informatik ersetzt",
   "Informatik ist ein Unterrichtsfach wie jedes andere"],
  ["Medium heißt hier Mittel, nicht Presse.",
   "Die Frage bleibt die der Medizin oder der Physik — nur der Weg zur Antwort führt über den Rechner."]),

 ("Was unterscheidet angewandte Informatik davon, einfach ein fertiges Programm zu benutzen?",
  "In der angewandten Informatik werden die Methoden für das fremde Fach ausgewählt, angepasst "
  "und beurteilt",
  ["Angewandte Informatik benutzt ausschließlich selbst geschriebene Programme",
   "Angewandte Informatik kommt ohne Computer aus",
   "Es gibt keinen Unterschied"],
  ["Wer eine Tabellenkalkulation bedient, wendet an — aber gestaltet keine Methode.",
   "Angewandte Informatik heißt: das Problem modellieren, ein Verfahren wählen und "
   "sein Ergebnis kritisch prüfen."]),

 ("Bei der Stilometrie werden Texte automatisch ausgewertet, um die Verfasserin oder den "
  "Verfasser zu bestimmen. Worauf stützt sich das Verfahren vor allem?",
  "Auf messbare Merkmale wie Wortlängen und die Häufigkeit unauffälliger Funktionswörter",
  ["Auf die Handschrift im Original",
   "Auf das Erscheinungsjahr des Buches",
   "Auf die Meinung der Literaturwissenschaft"],
  ["Gerade unbewusste Kleinigkeiten wie „und“, „aber“, „doch“ verraten den Stil.",
   "Ein schönes Beispiel dafür, wie Informatik einer geisteswissenschaftlichen Frage dient."]),

 ("Ein Röntgenbild wird digitalisiert. Welche zwei Schritte gehören dazu?",
  "Abtasten in einem Raster und Quantisieren der Helligkeitswerte",
  ["Vergrößern und Ausdrucken",
   "Verschlüsseln und Komprimieren",
   "Übersetzen und Formatieren"],
  ["Abtasten legt fest, wie fein das Raster ist (Bildpunkte).",
   "Quantisieren legt fest, wie viele Helligkeitsstufen jeder Punkt bekommt."]),

 ("Warum reicht es für eine gute Beurteilung nicht, ein Beispiel nur einem Bereich zuzuordnen?",
  "Weil zur Zuordnung eine Begründung gehört, die den Schwerpunkt des Beispiels benennt",
  ["Weil man immer alle vier Bereiche nennen muss",
   "Weil Zuordnungen grundsätzlich Geschmackssache sind",
   "Weil nur die Länge der Antwort zählt"],
  ["Der Operator „zuordnen“ verlangt die Entscheidung, „begründen“ verlangt den Grund.",
   "Zwei Sätze genügen: Was ist die Kernfrage, und welcher Bereich beantwortet sie?"]),

 ("Ihr haltet zu zweit einen Mini-Vortrag über ein informatikfremdes Anwendungsgebiet. "
  "Was gehört auf jeden Fall hinein?",
  "Das fremde Fachproblem, die eingesetzte informatische Methode und die Zuordnung zu einem Bereich",
  ["Eine vollständige Biografie der beteiligten Forscherinnen und Forscher",
   "Der Quelltext des benutzten Programms",
   "Eine Liste aller Fachbegriffe ohne Erklärung"],
  ["Erst die Frage aus dem fremden Fach, dann der informatische Weg, dann die Einordnung.",
   "Und immer die Quelle nennen — Kurzrecherche heißt nicht raten."]),
]


# ---------------------------------------------------------------------------
# KW 39 - zum Deck decks/ai-begriffe.html ("Die Begriffe, die 2026 zaehlen").
# Zwanzig Aufgaben (Doc 22.09.2026: "mach bitte da noch 10 Fragen dazu"):
# 1-10 zu LLM, Token, Kontextfenster, Halluzination, Prompt, Prompt/Context
# Engineering, RAG, Tool Use, Agent; 11-20 zum Unterbau und zum Rand des Decks -
# Neuron, Gewichte, Schichten, Deep Learning, Training, Fenstergroesse,
# Prompt-Technik, Embedding, MCP, Agenten-Risiko. Jede Antwort steht woertlich
# auf einer Folie des Decks (Doc: Fragen aus dem eigenen Material).
AI_BEGRIFFE = [
 ("Ein großes Sprachmodell (LLM) hat im Kern genau eine Aufgabe. Welche?",
  "Es sagt das nächste Token voraus",
  ["Es schlägt die Antwort in einer Datenbank nach",
   "Es sucht den passenden Satz aus seinem Trainingstext heraus",
   "Es prüft den Text auf Rechtschreibung und Grammatik"],
  ["Ein LLM ist generativ: es erzeugt Text, es sucht ihn nicht heraus.",
   "Das Gelernte steckt in Milliarden Gewichten — es gibt kein Nachschlagewerk darin."]),

 ("Warum kommt auf dieselbe Frage nicht jedes Mal dieselbe Antwort?",
  "Weil die Ausgabe aus Wahrscheinlichkeiten gewürfelt wird",
  ["Weil das Modell zwischendurch dazulernt",
   "Weil die Frage jedes Mal anders verstanden wird",
   "Weil jede Antwort neu aus dem Internet geholt wird"],
  ["Das Modell berechnet für jedes nächste Token Wahrscheinlichkeiten.",
   "Aus dieser Verteilung wird gezogen — deshalb zwei Läufe, zwei Formulierungen."]),

 ("Faustregel Deutsch: 1 Wort entspricht etwa 1,5 bis 2 Token. Mit wie vielen Token rechnest du bei 100 Wörtern?",
  "mit etwa 150 bis 200 Token",
  ["mit genau 100 Token", "mit etwa 50 Token", "mit etwa 1 000 Token"],
  ["Ein Token ist ein Wort, ein Wortteil oder ein Zeichen — deutsche Wörter zerfallen oft in mehrere.",
   "100 Wörter · 1,5 bis 2 = 150 bis 200 Token. In Token wird gemessen: Eingabe, Ausgabe, Preis und Limit."]),

 ("Was passiert, wenn das Kontextfenster voll ist?",
  "Das Älteste fällt heraus — das Modell vergisst es",
  ["Der Rest wird auf der Festplatte gespeichert",
   "Die Antwort wird automatisch kürzer",
   "Das Modell fragt nach, was es behalten soll"],
  ["Das Kontextfenster ist ein Arbeitsspeicher, keine Festplatte.",
   "Darin steckt alles: Systemanweisung, Verlauf, Anhänge und die Antwort selbst."]),

 ("Du hast gestern eine Stunde mit einem Chatbot gearbeitet und öffnest heute ein neues Gespräch. Was weiß er noch?",
  "nichts — jeder Start beginnt bei null",
  ["alles, er hat das Gespräch gespeichert",
   "nur die letzte Frage von gestern",
   "so viel, wie in sein Kontextfenster passt"],
  ["Zwischen zwei Chats bleibt nichts im Modell zurück.",
   "Was er wissen soll, muss wieder ins Fenster — als Anhang, Verlauf oder Anweisung."]),

 ("Ein Modell nennt eine Quelle, die es gar nicht gibt. Wie heißt das, und woran liegt es?",
  "Halluzination — es sagt das wahrscheinlichste Wort voraus, nicht das wahre",
  ["Ein Übertragungsfehler — die Quelle ging beim Senden verloren",
   "Ein Tokenizer-Fehler — die Quelle wurde falsch zerlegt",
   "Ein veralteter Trainingsstand — die Quelle war früher richtig"],
  ["Eine erfundene Quelle klingt plausibel, weil plausible Wortfolgen wahrscheinlich sind.",
   "Das Modell hat keine „weiß ich nicht“-Taste: Zuversicht ist kein Wahrheitsmaß.",
   "Gegenmittel: Beleg mitgeben und nachprüfen — nie umgekehrt."]),

 ("Wofür ist der System-Prompt da?",
  "Er setzt Rolle und Regeln für das ganze Gespräch",
  ["Er enthält die konkrete Aufgabe dieser einen Frage",
   "Er meldet dem Modell den Stand der Technik",
   "Er speichert die Antworten für das nächste Gespräch"],
  ["System-Prompt: Rolle und Regeln. User-Prompt: die konkrete Aufgabe.",
   "Der Prompt ist das Programm — nur in natürlicher Sprache geschrieben."]),

 ("Worin unterscheiden sich Prompt Engineering und Context Engineering?",
  "Prompt Engineering formuliert die einzelne Anweisung, Context Engineering füllt das ganze Kontextfenster",
  ["Prompt Engineering ist für Text, Context Engineering für Bilder",
   "Prompt Engineering macht der Mensch, Context Engineering das Modell",
   "Prompt Engineering ist die alte Bezeichnung für dasselbe Vorgehen"],
  ["Prompt Engineering fragt: Wie formuliere ich? — Handwerk am Satz.",
   "Context Engineering fragt: Was weiß das Modell gerade? — und ebenso: Was muss raus?",
   "Sobald Agenten arbeiten, reicht der schöne Satz nicht mehr."]),

 ("Was geschieht bei RAG, bevor das Modell antwortet?",
  "Es wird gesucht, und die Fundstellen wandern in den Prompt",
  ["Das Modell wird mit den neuen Texten nachtrainiert",
   "Die Frage wird in mehrere Teilfragen zerlegt",
   "Das Kontextfenster wird vorübergehend vergrößert"],
  ["RAG heißt Retrieval-Augmented Generation: erst suchen, dann antworten.",
   "Die Antwort kommt aus mitgeliefertem Text — deshalb aktuell, prüfbar und mit Quelle.",
   "Gesucht wird über Embeddings nach Ähnlichkeit, nicht nach genauem Wortlaut."]),

 ("Ein Agent soll eine Datei lesen. Was tut das Modell selbst?",
  "Es schreibt den Werkzeugaufruf; ausgeführt wird er vom Programm",
  ["Es liest die Datei direkt von der Festplatte",
   "Es schickt die Datei an den Hersteller",
   "Es beschreibt in Worten, wie man die Datei öffnet"],
  ["Tool Use (Function Calling): das Modell erzeugt den Aufruf, nicht die Antwort.",
   "Das Programm führt aus, und das Ergebnis geht zurück ins Kontextfenster.",
   "Ein Agent ist Modell + Werkzeuge + Schleife + Ziel — agentisch heißt: die Reihenfolge steht nicht vorher fest."]),

 # --- Kapitel 01: was unter der Sprache rechnet -----------------------------
 ("Was tut ein einzelnes künstliches Neuron mit seinen Eingängen?",
  "Es multipliziert jeden Eingang mit seinem Gewicht und addiert alles",
  ["Es vergleicht sie mit gespeicherten Beispielen",
   "Es sucht den größten Eingang heraus und gibt ihn weiter",
   "Es übersetzt sie in Wörter"],
  ["Jeder Eingang ist eine Zahl, jedes Gewicht sagt, wie stark er zählt.",
   "Multiplizieren und addieren — mehr passiert nicht; die Aktivierung entscheidet dann, wie stark es weitergibt.",
   "Ein einzelnes Neuron kann fast nichts. Viele zusammen sehr viel."]),

 ("Wo steckt nach dem Training das, was ein Netz gelernt hat?",
  "ausschließlich in den Gewichten",
  ["in einer Datenbank neben dem Netz",
   "in den Trainingstexten, die gespeichert bleiben",
   "in der Aktivierungsfunktion"],
  ["Trainieren heißt: alle Gewichte ein kleines Stück in die bessere Richtung rücken.",
   "Danach sind die Beispiele weg — geblieben sind Milliarden Zahlen.",
   "Deshalb kann ein Modell nichts „nachschlagen“, was nicht im Fenster steht."]),

 ("Wozu liegen zwischen Eingabe- und Ausgabeschicht die verdeckten Schichten?",
  "Sie bauen Merkmale auf: erst Kanten, später Augen, noch später Gesichter",
  ["Sie speichern die Trainingsdaten für später",
   "Sie korrigieren Rechtschreibfehler in der Eingabe",
   "Sie machen das Netz schneller"],
  ["Die Eingabeschicht nimmt die Rohdaten, die Ausgabeschicht gibt das Ergebnis.",
   "Dazwischen wird aus Einfachem Zusammengesetztes — Schicht für Schicht.",
   "Jede Verbindung ist ein Gewicht, bei großen Modellen Milliarden."]),

 ("Was heißt „Deep Learning“?",
  "Lernen mit vielen Schichten hintereinander",
  ["Lernen mit besonders vielen Beispielen",
   "Lernen ohne menschliche Hilfe",
   "Lernen, das tiefer geht als Auswendiglernen"],
  ["„Deep“ meint die Tiefe des Netzes, nicht die Tiefe des Verstehens.",
   "Mehr Schichten heißt: mehr Stufen, auf denen Merkmale entstehen."]),

 ("Wie lernt ein neuronales Netz aus einem Fehler?",
  "Es rät, misst den Fehler und rückt alle Gewichte ein kleines Stück in die bessere Richtung",
  ["Es merkt sich das falsche Beispiel und schlägt es später nach",
   "Es fügt eine neue Schicht hinzu, bis der Fehler verschwindet",
   "Es fragt beim Menschen nach der richtigen Antwort"],
  ["Dieses Rückwärtslaufen des Fehlers durchs Netz heißt Backpropagation.",
   "Ein Schritt bringt fast nichts — millionenfach wiederholt bleibt der Fehler klein.",
   "Programmiert wird dabei nichts: das Netz wird an Beispielen trainiert."]),

 # --- Kapitel 02 bis 04: Fenster, Prompt, Werkzeuge -------------------------
 ("Warum ist ein größeres Kontextfenster nicht automatisch besser?",
  "Weil die Mitte schlechter beachtet wird und jedes Token neu kostet",
  ["Weil das Modell dann langsamer dazulernt",
   "Weil große Fenster die Antwort automatisch kürzen",
   "Weil der Tokenizer ab einer Größe ungenau wird"],
  ["Von 2 000 Token (2020) auf 200 000 bis 1 000 000 (2026) — Platz ist genug da.",
   "Aber: was in der Mitte liegt, wird schlechter beachtet als Anfang und Ende.",
   "Und jedes Token im Fenster kostet bei jeder einzelnen Anfrage neu — Ballast muss raus."]),

 ("„Antworte als Tabelle“ — welche Technik des Prompt Engineering ist das?",
  "Format vorgeben",
  ["Rolle setzen", "Beispiele zeigen", "Schritt für Schritt"],
  ["Format vorgeben macht die Ausgabe weiterverwertbar statt nur lesbar.",
   "Rolle setzen wäre „Du bist Fachlehrer für Informatik“, Beispiele zeigen hieße: zwei gelöste Fälle voranstellen.",
   "Der Prompt ist das Programm — nur in natürlicher Sprache geschrieben."]),

 ("Was ist ein Embedding?",
  "Text als Zahlenvektor, der sich mit anderem Text vergleichen lässt",
  ["Ein Bild, das in den Prompt eingebettet wird",
   "Ein Modell, das in ein Programm eingebaut ist",
   "Ein Stück Text, das fest im Kontextfenster bleibt"],
  ["RAG sucht nicht nach genauem Wortlaut, sondern nach Ähnlichkeit.",
   "Dafür werden Texte in Vektoren übersetzt; nah beieinander heißt inhaltlich ähnlich.",
   "Die Fundstellen wandern danach in den Prompt — das Modell liest sie dort."]),

 ("Wofür steht MCP im Zusammenhang mit Werkzeugen?",
  "für einen offenen Standard, über den Werkzeuge sich beim Modell anmelden",
  ["für die Schleife, in der ein Agent arbeitet",
   "für das Protokoll, mit dem Modelle untereinander reden",
   "für die Berechtigungsstufe eines Agenten"],
  ["Model Context Protocol, seit 2024 — ein Werkzeug meldet sich an und ist benutzbar.",
   "Tool Use heißt: das Modell schreibt den Aufruf, das Programm führt ihn aus.",
   "Das Ergebnis geht zurück ins Kontextfenster, dort liest das Modell es."]),

 ("Worin liegt bei einem Agenten das eigentliche Risiko?",
  "in den Berechtigungen, die er bekommt",
  ["im Modell, das zu wenig weiß",
   "in der Länge des System-Prompts",
   "in der Zahl der Werkzeuge, die angemeldet sind"],
  ["Ein Agent handelt mehrere Schritte ohne Rückfrage — Fehler multiplizieren sich dabei.",
   "Gefährlich wird nicht das Denken, sondern das Dürfen: löschen, senden, bezahlen.",
   "Deshalb Human in the Loop an den teuren Stellen — und prüfbar bleibt nur, was protokolliert wird."]),
]


if __name__ == "__main__":
    for slug, nr, kw, lb, topic, blurb, qs in [
        ("bildungsinhalt", 4, 37, "LB 1",
         "Informatik als Bildungsinhalt und Medium anderer Wissenschaftszweige",
         "informatische Methoden in Physik, Medizin und Sprache; Zuordnung zu den "
         "vier Wissenschaftsbereichen", BILDUNGSINHALT),
        ("ai-begriffe", 6, 39, "LB 2",
         "Die Begriffe der künstlichen Intelligenz",
         "LLM, Token, Kontextfenster, Halluzination, Prompt, Context Engineering, RAG, "
         "Tool Use und Agent — zum Foliensatz decks/ai-begriffe.html", AI_BEGRIFFE),
    ]:
        path, sol = build(slug, nr, kw, lb, topic, blurb, qs)
        print(os.path.basename(path), len(qs), "Aufgaben, Lösungen:",
              "".join("ABCD"[x] for x in sol))
