#!/usr/bin/env python3
"""Weekly 10-question essentials quizzes for FOS 12, weeks 11-32 (LB 2, OOP, LB 3A).

Same engine and layout as tools/build_infotest12.py (LB 1) - that module holds the
template and the build() function, this one only carries the questions.
"""
import os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_infotest12 import build

# (slug, week nr, KW, topic, questions) - question: (text, correct, [3 wrong], [2 steps])
QUIZZES = [
 ("grundbegriffe", 11, 46, "Programmiersprachen: Grundbegriffe", [
  ("Was ist ein Algorithmus?",
   "Eine eindeutige, endliche Beschreibung eines Lösungsweges",
   ["Ein Programm in einer bestimmten Sprache", "Eine Rechenmaschine", "Ein Datentyp für Zahlen"],
   ["Der Algorithmus ist die Idee, das Programm die Aufschrift.", "Kochrezepte sind Algorithmen ohne Computer."]),
  ("Welche Eigenschaft verletzt die Anweisung 'nimm etwas Salz'?",
   "Eindeutigkeit",
   ["Endlichkeit", "Allgemeingültigkeit", "Determiniertheit"],
   ["'Etwas' lässt sich verschieden lesen.", "Jeder Schritt muss genau einen Sinn haben."]),
  ("Welche Eigenschaft verletzt 'zähle bis unendlich'?",
   "Endlichkeit",
   ["Eindeutigkeit", "Ausführbarkeit", "Determiniertheit"],
   ["Ein Algorithmus muss nach endlich vielen Schritten enden.", "Sonst ist es kein Algorithmus, sondern eine Endlosschleife."]),
  ("Was bedeutet Syntax?",
   "Die Regeln, welche Zeichenfolgen überhaupt erlaubt sind",
   ["Die Bedeutung einer Anweisung", "Die Geschwindigkeit eines Programms", "Der Speicherbedarf"],
   ["Syntax = Form, vergleichbar mit Rechtschreibung und Grammatik.", "Ein Syntaxfehler verhindert schon den Start."]),
  ("Was bedeutet Semantik?",
   "Die Bedeutung einer syntaktisch korrekten Anweisung",
   ["Die Schreibweise von Befehlen", "Die Einrückung im Quelltext", "Der Zeichensatz der Datei"],
   ["Der Rechner tut, was dasteht, nicht was gemeint war.", "Semantische Fehler laufen mit falschem Ergebnis durch."]),
  ("Ein Programm läuft, liefert aber ein falsches Ergebnis. Welche Fehlerart?",
   "Logikfehler",
   ["Syntaxfehler", "Laufzeitfehler", "Zeichensatzfehler"],
   ["Kein Absturz, keine Meldung - nur ein falsches Ergebnis.", "Nur ein Testfall mit bekanntem Sollwert deckt ihn auf."]),
  ("Wann meldet sich ein Syntaxfehler?",
   "Vor dem Start, beim Uebersetzen bzw. Einlesen",
   ["Erst wenn die Zeile erreicht wird", "Nie, er fällt nur beim Testen auf", "Nach dem Programmende"],
   ["Der Uebersetzer prüft die Form, bevor etwas läuft.", "Deshalb ist er die harmloseste Fehlerart."]),
  ("Was macht ein Interpreter?",
   "Er liest und führt das Programm Zeile für Zeile aus",
   ["Er erzeugt eine ausführbare Datei", "Er übersetzt einmal komplett in Maschinencode", "Er prüft nur die Rechtschreibung"],
   ["Python ist eine Interpretersprache.", "Deshalb fällt ein Fehler erst auf, wenn die Zeile erreicht wird."]),
  ("Welche Reihenfolge stimmt, von maschinennah nach menschennah?",
   "Maschinencode, Assembler, Hochsprache",
   ["Hochsprache, Maschinencode, Assembler", "Assembler, Maschinencode, Hochsprache", "Hochsprache, Assembler, Maschinencode"],
   ["Unten steht die CPU, oben der Mensch.", "Jede Ebene nach oben ist bequemer und weiter weg von der Hardware."]),
  ("Woher stammt das Wort Algorithmus?",
   "Vom Namen des Gelehrten al-Chwarizmi",
   ["Vom griechischen Wort für Rechnen", "Von der Firma Algol", "Vom lateinischen algor für Kälte"],
   ["Al-Chwarizmi wirkte um 825 in Bagdad.", "Sein Buch lehrte das Rechnen mit indischen Ziffern."]),
 ]),
 ("struktogramm", 12, 47, "Struktogramm, PAP und GRAFCET", [
  ("Wie viele Ein- und Ausgänge hat ein Struktogramm?",
   "Genau einen Eingang oben und einen Ausgang unten",
   ["Beliebig viele, je nach Sprungzielen", "Zwei Eingänge und einen Ausgang", "Keinen festgelegten"],
   ["Deshalb sind Sprünge unmöglich.", "Daraus entsteht automatisch strukturierter Code."]),
  ("Woran erkennt man im Struktogramm eine Auswahl?",
   "An einem Kasten mit Dreieck und den Zweigen ja und nein",
   ["An einem Rahmen an der linken Seite", "An doppelten Seitenstrichen", "An einer Raute"],
   ["Links steht ja, rechts nein.", "Die Raute gehört zum PAP, nicht zum Struktogramm."]),
  ("Woran erkennt man eine Wiederholung im Struktogramm?",
   "An einem Rahmen, der den wiederholten Teil umschliesst",
   ["An einem Dreieck im Kasten", "An einem Pfeil nach oben", "An einem Parallelogramm"],
   ["Bedingung oben = kopfgesteuert, unten = fußgesteuert.", "Der Rahmen zeigt genau, was wiederholt wird."]),
  ("Welche Form hat die Verzweigung im Programmablaufplan?",
   "Eine Raute",
   ["Ein Rechteck", "Ein Parallelogramm", "Ein Kreis"],
   ["DIN 66001 legt die Symbole fest.", "Die Raute hat genau zwei beschriftete Ausgänge."]),
  ("Welches PAP-Symbol steht für eine Ein- oder Ausgabe?",
   "Das Parallelogramm",
   ["Das Rechteck", "Die Raute", "Das Rechteck mit runden Enden"],
   ["Rechteck = Operation, Raute = Verzweigung.", "Runde Enden markieren Anfang und Ende."]),
  ("Was ist der wichtigste Unterschied zwischen Struktogramm und PAP?",
   "Der PAP erlaubt Sprünge, das Struktogramm nicht",
   ["Der PAP kann keine Schleifen darstellen", "Das Struktogramm braucht immer eine Raute", "Der PAP ist immer kleiner"],
   ["Im PAP zeigt ein Pfeil nach oben die Schleife.", "Im Struktogramm ist der Rahmen die Schleife."]),
  ("Wofür wird GRAFCET vor allem eingesetzt?",
   "Für Ablaufsteuerungen in der Automatisierungstechnik",
   ["Für Datenbankentwürfe", "Für Webseiten-Layouts", "Für die Notenberechnung"],
   ["Normiert in DIN EN 60848.", "Es beschreibt Zustände über die Zeit, nicht eine Rechnung."]),
  ("Was bedeutet in GRAFCET der Querstrich zwischen zwei Schritten?",
   "Eine Transition mit Weiterschaltbedingung",
   ["Eine Aktion", "Das Ende des Ablaufs", "Einen Kommentar"],
   ["Erst wenn die Bedingung wahr ist, wird weitergeschaltet.", "Der Doppelrahmen markiert den Anfangsschritt."]),
  ("Warum zeichnet man überhaupt, bevor man programmiert?",
   "Weil das Diagramm sprachunabhängig den Ablauf klärt",
   ["Weil der Compiler es verlangt", "Weil Python sonst nicht startet", "Weil Diagramme schneller laufen"],
   ["Aus demselben Bild wird Python, Java oder eine SPS.", "Fehler im Entwurf sind billiger als Fehler im Code."]),
  ("Wer erfand das Struktogramm?",
   "Nassi und Shneiderman, 1972",
   ["Dijkstra, 1968", "Böhm und Jacopini, 1966", "Berners-Lee, 1989"],
   ["Es war eine Antwort auf den GOTO-Wildwuchs.", "Deshalb heisst es auch Nassi-Shneiderman-Diagramm."]),
 ]),
 ("datentypen", 13, 48, "Programmierumgebung und Datentypen", [
  ("Welchen Typ liefert input() in Python immer?",
   "str, also Text",
   ["int", "float", "den passenden Typ automatisch"],
   ["Auch wenn 42 eingetippt wird, kommt '42' an.", "Zum Rechnen muss man int() oder float() benutzen."]),
  ("Was ergibt 7 // 2 in Python?",
   "3",
   ["3.5", "1", "4"],
   ["// ist die ganzzahlige Division.", "7 / 2 wäre 3.5, 7 % 2 wäre 1."]),
  ("Was ergibt 7 % 2?",
   "1",
   ["3", "3.5", "0"],
   ["% liefert den Rest der Division.", "Damit prüft man gerade/ungerade und Vielfache."]),
  ("Welcher Datentyp passt für eine Schülernummer?",
   "int",
   ["float", "str", "bool"],
   ["Ganze Zahl, mit der gerechnet oder sortiert wird.", "Als Text würde '10' vor '9' einsortiert."]),
  ("Warum ist 0.1 + 0.2 == 0.3 in Python False?",
   "Weil Kommazahlen binär gespeichert werden und nicht exakt passen",
   ["Weil Python falsch rechnet", "Weil == nur für Ganzzahlen gilt", "Weil 0.3 kein gültiger Wert ist"],
   ["Float ist eine Näherung, kein exakter Bruch.", "Deshalb rechnet man mit Geld in ganzen Cent."]),
  ("Was bewirkt der Ausdruck '2' + '3' in Python?",
   "Er ergibt den Text '23'",
   ["Er ergibt 5", "Er ergibt einen Fehler", "Er ergibt 2.3"],
   ["Bei Texten verknüpft + die Zeichenketten.", "Zum Rechnen müssen beide erst int() werden."]),
  ("Welche Schreibweise ist ein gültiger Variablenname?",
   "anzahl_schueler",
   ["2note", "anzahl schueler", "class"],
   ["Buchstaben, Ziffern und Unterstrich, nicht am Anfang eine Ziffer.", "Schlüsselwörter wie class sind gesperrt."]),
  ("Welcher strukturierte Typ ist geordnet und veränderbar?",
   "Die Liste",
   ["Das Tupel", "Die Menge", "Das Dictionary"],
   ["Tupel sind unveränderlich, Mengen ungeordnet.", "Dictionaries ordnen Schlüssel einem Wert zu."]),
  ("Wie greift man auf das erste Element der Liste noten zu?",
   "noten[0]",
   ["noten[1]", "noten(0)", "noten.first"],
   ["Der Index beginnt bei 0.", "noten[-1] liefert das letzte Element."]),
  ("Was bedeutet die Einrückung in Python?",
   "Sie bildet den Block und ist Teil der Syntax",
   ["Sie ist reine Geschmackssache", "Sie ist nur ein Kommentar", "Sie beschleunigt das Programm"],
   ["Nach einem Doppelpunkt folgt immer ein eingerückter Block.", "Falsche Einrückung ist ein Syntaxfehler."]),
 ]),
 ("folge", 14, 49, "Grundstruktur Folge / Sequenz", [
  ("Wofür steht EVA?",
   "Eingabe, Verarbeitung, Ausgabe",
   ["Ergebnis, Variable, Ausdruck", "Einlesen, Vergleichen, Abbrechen", "Entwurf, Version, Ausführung"],
   ["Der Grundbauplan fast jedes kleinen Programms.", "Erst alles einlesen, dann rechnen, dann ausgeben."]),
  ("Was besagt der Satz von Böhm und Jacopini?",
   "Folge, Auswahl und Wiederholung genügen für jeden Algorithmus",
   ["Jedes Programm braucht mindestens eine Schleife", "Jeder Algorithmus lässt sich beschleunigen", "Jede Sprache braucht einen Compiler"],
   ["Veröffentlicht 1966.", "Das ist die Grundlage der strukturierten Programmierung."]),
  ("Was bedeutet x = x + 1 in einem Programm?",
   "Rechte Seite ausrechnen und das Ergebnis in x speichern",
   ["Eine Gleichung, die nie stimmt", "Ein Vergleich zweier Werte", "Ein Syntaxfehler"],
   ["Das Gleichheitszeichen weist zu, es behauptet nichts.", "Zum Vergleichen dient =="]),
  ("Welche Reihenfolge ist bei einer Folge entscheidend?",
   "Erst der Wert, dann die Rechnung damit",
   ["Erst die Ausgabe, dann die Eingabe", "Die Reihenfolge ist egal", "Erst die Verarbeitung, dann die Eingabe"],
   ["Mit einer Variablen ohne Wert kann man nicht rechnen.", "Deshalb steht die Eingabe immer oben."]),
  ("Wie gibt man in Python eine Zahl auf zwei Nachkommastellen formatiert aus?",
   "print(f'{wert:.2f}')",
   ["print(wert.2)", "print(round(wert))", "print(wert, 2)"],
   ["Der f-String erlaubt Formatangaben nach dem Doppelpunkt.", "round(wert, 2) rundet, formatiert aber nicht die Ausgabe."]),
  ("Was ergibt 2 ** 10 in Python?",
   "1024",
   ["20", "100", "12"],
   ["** ist die Potenz.", "2 hoch 10 ist 1024."]),
  ("Warum schreibt man Testfälle VOR dem Programmieren auf?",
   "Weil man sonst nicht merkt, dass etwas Falsches herauskommt",
   ["Weil der Interpreter das verlangt", "Weil Testfälle den Code beschleunigen", "Weil sie den Quelltext ersetzen"],
   ["Ohne Sollwert ist jedes Ergebnis plausibel.", "Immer ein normaler Fall, ein Randfall und ein Unsinn-Fall."]),
  ("Welcher Testfall gehört unbedingt zu einem Ohm-Rechner R = U / I?",
   "I = 0",
   ["U = 12 und I = 2", "U = 230 und I = 0.5", "U = 100 und I = 10"],
   ["Division durch 0 ist der Randfall.", "Ein Absturz ist die schlechteste mögliche Antwort."]),
  ("Wie wird 'Eingabe: x' aus dem Struktogramm in Python geschrieben?",
   "x = float(input('...'))",
   ["print(x)", "x == input()", "input(x)"],
   ["Einlesen und umwandeln in einer Zeile.", "Ohne Umwandlung wäre x Text."]),
  ("Welcher Operator liefert die Sekunden-Restminuten bei einer Zeitumrechnung?",
   "%",
   ["//", "/", "**"],
   ["// liefert die vollen Einheiten, % den Rest.", "Zusammen ergeben sie Stunden, Minuten, Sekunden."]),
 ]),
 ("selektion", 15, 50, "Grundstruktur Auswahl / Selektion", [
  ("Was unterscheidet = von == in Python?",
   "= weist zu, == vergleicht",
   ["= vergleicht, == weist zu", "Beide vergleichen", "Beide weisen zu"],
   ["Ein Gleichheitszeichen speichert einen Wert.", "Zwei Gleichheitszeichen liefern True oder False."]),
  ("Wann ist A and B wahr?",
   "Nur wenn A und B beide wahr sind",
   ["Wenn mindestens eines wahr ist", "Wenn genau eines wahr ist", "Immer"],
   ["and verlangt beides.", "or genügt schon eines."]),
  ("Wie schreibt man 'punkte liegt zwischen 50 und 60'?",
   "punkte >= 50 and punkte <= 60",
   ["punkte >= 50 or punkte <= 60", "punkte = 50 bis 60", "50 and 60 in punkte"],
   ["Zwei Bedingungen mit and verknüpfen.", "In Python geht auch 50 <= punkte <= 60."]),
  ("Wie viele Zweige einer if/elif/else-Kette werden ausgeführt?",
   "Genau einer",
   ["Alle, deren Bedingung wahr ist", "Immer zwei", "Keiner, wenn kein else da ist"],
   ["Python nimmt den ersten passenden Zweig.", "Danach wird der Rest übersprungen."]),
  ("Warum ordnet man einen Notenschlüssel vom höchsten Wert abwärts?",
   "Weil der erste passende Zweig genommen wird",
   ["Weil Python nur aufsteigend prüft", "Weil sonst ein Syntaxfehler entsteht", "Weil else immer oben stehen muss"],
   ["Stünde 30 oben, wäre jede Punktzahl darüber eine 5.", "Vom Strengsten zum Lockersten ordnen."]),
  ("Was ist ein Zaunpfahlfehler?",
   "Ein Fehler um genau eins an einer Grenze",
   ["Ein Fehler in der Einrückung", "Ein fehlender Doppelpunkt", "Ein falscher Datentyp"],
   ["Typisch: > statt >= oder ein Durchlauf zu viel.", "Deshalb immer die Grenzwerte testen."]),
  ("Welche Werte sollte man beim Notenschlüssel mit Grenze 50 testen?",
   "49.9, 50.0 und 50.1",
   ["Nur 0 und 100", "Nur 50", "Nur Werte in der Mitte"],
   ["Direkt darunter, genau darauf, direkt darüber.", "Genau dort sitzen die meisten Logikfehler."]),
  ("Was bewirkt not in einer Bedingung?",
   "Es kehrt den Wahrheitswert um",
   ["Es prüft auf Ungleichheit von Zahlen", "Es beendet das Programm", "Es verknüpft zwei Bedingungen"],
   ["not True ist False.", "not mitglied ist wahr, wenn mitglied falsch ist."]),
  ("Was passiert bei einer einseitigen Auswahl ohne else?",
   "Ist die Bedingung falsch, passiert einfach nichts",
   ["Es gibt einen Fehler", "Der if-Block läuft trotzdem", "Das Programm bricht ab"],
   ["else ist optional.", "Danach geht es normal weiter."]),
  ("Was bedeutet Kurzschlussauswertung bei and?",
   "Ist der linke Teil falsch, wird der rechte nicht mehr geprüft",
   ["Beide Teile werden immer geprüft", "Der rechte Teil wird zuerst geprüft", "Die Bedingung wird zweimal geprüft"],
   ["Das Ergebnis steht dann schon fest.", "Man nutzt es, um vorher auf Null oder Leere zu prüfen."]),
 ]),
 ("zyklus", 16, 51, "Grundstruktur Wiederholung / Zyklus", [
  ("Wann nimmt man eine Zählschleife (for)?",
   "Wenn die Anzahl der Durchläufe vorher bekannt ist",
   ["Wenn die Anzahl unbekannt ist", "Wenn keine Bedingung nötig ist", "Wenn das Programm abstürzen soll"],
   ["for zählt, while prüft.", "Bei unbekannter Anzahl nimmt man while."]),
  ("Wie viele Durchläufe macht for i in range(5)?",
   "5",
   ["4", "6", "0"],
   ["range(5) liefert 0, 1, 2, 3, 4.", "Der Startwert gehört dazu, der Endwert nicht."]),
  ("Welche Zahlen erzeugt range(1, 6)?",
   "1, 2, 3, 4, 5",
   ["1, 2, 3, 4, 5, 6", "0, 1, 2, 3, 4, 5", "1, 6"],
   ["Start inklusive, Ende exklusive.", "Genau hier entsteht der Zaunpfahlfehler."]),
  ("Was erzeugt eine Endlosschleife?",
   "Eine Bedingung, die im Rumpf nie falsch wird",
   ["Ein fehlender Doppelpunkt", "Eine zu grosse Zahl in range", "Eine Liste ohne Elemente"],
   ["Im Rumpf muss sich etwas verändern.", "Sonst hilft nur Strg+C."]),
  ("Was gehört vor jede Summierschleife?",
   "summe = 0",
   ["summe = 1", "print(summe)", "return summe"],
   ["Ohne Initialisierung gibt es die Variable beim ersten Durchlauf nicht.", "Bei einem Produkt wäre die 1 richtig."]),
  ("Warum darf man beim Suchen des Maximums nicht mit 0 starten?",
   "Weil bei lauter negativen Zahlen 0 das falsche Ergebnis wäre",
   ["Weil 0 kein gültiger Datentyp ist", "Weil Python bei 0 abbricht", "Weil das Maximum immer positiv ist"],
   ["Besser mit dem ersten Element der Liste starten.", "Dann stimmt es für alle Zahlenbereiche."]),
  ("Was bedeutet 'kopfgesteuert' bei einer Schleife?",
   "Die Bedingung wird vor jedem Durchlauf geprüft",
   ["Die Bedingung wird nach jedem Durchlauf geprüft", "Die Schleife läuft immer genau einmal", "Die Schleife hat keine Bedingung"],
   ["Der Rumpf läuft also eventuell null Mal.", "Fußgesteuert liefe er mindestens einmal."]),
  ("Welches Muster passt zu 'Wie viele Einsen sind in der Liste?'",
   "Zähler",
   ["Summierer", "Extremwert", "Sucher"],
   ["anzahl = 0 vorher, anzahl = anzahl + 1 im Rumpf.", "Der Summierer addiert Werte, nicht Vorkommen."]),
  ("Was macht for note in noten?",
   "Es durchläuft alle Elemente der Liste noten",
   ["Es zählt von 0 bis noten", "Es sortiert die Liste", "Es sucht die Note 1"],
   ["Kein Index nötig, note ist direkt der Wert.", "Für den Index gibt es range(len(noten))."]),
  ("Was berechnet: solange a >= b, ziehe b von a ab?",
   "Den Rest der Division a durch b",
   ["Das Produkt a mal b", "Die Summe a plus b", "Den größten gemeinsamen Teiler"],
   ["Wiederholtes Abziehen ist Division mit Rest.", "Uebrig bleibt a % b."]),
 ]),
 ("uebung", 17, 52, "Programmierübung zum Jahresausklang", [
  ("Was ergibt '*' * 5 in Python?",
   "*****",
   ["25", "'*5'", "einen Fehler"],
   ["Text mal Zahl wiederholt die Zeichenkette.", "Damit lassen sich Muster wie ein Tannenbaum zeichnen."]),
  ("Welche Bedingung prüft bei FizzBuzz auf 'FizzBuzz'?",
   "i % 3 == 0 and i % 5 == 0",
   ["i % 3 == 0 or i % 5 == 0", "i % 15 != 0", "i / 3 == 0 and i / 5 == 0"],
   ["Beide Teilbarkeiten müssen gelten.", "Diese Bedingung muss zuerst geprüft werden."]),
  ("Warum steht die FizzBuzz-Bedingung für 3 und 5 ganz oben?",
   "Weil sonst schon der Zweig für 3 zuschlägt",
   ["Weil Python nur die erste Zeile liest", "Weil 15 keine Zahl ist", "Weil else immer zuletzt kommt"],
   ["Der erste passende Zweig gewinnt.", "Die Reihenfolge ist hier die eigentliche Aufgabe."]),
  ("In einer Schleife steht summe = note statt summe = summe + note. Was passiert?",
   "Die Summe enthält am Ende nur den letzten Wert",
   ["Das Programm stürzt ab", "Die Summe wird verdoppelt", "Es gibt einen Syntaxfehler"],
   ["Jede Zuweisung überschreibt den alten Inhalt.", "Ein Logikfehler, der schweigend falsch rechnet."]),
  ("Welche Fehlerart ist 'durch 6 statt durch 5 geteilt'?",
   "Logikfehler",
   ["Syntaxfehler", "Laufzeitfehler", "Zeichensatzfehler"],
   ["Das Programm läuft und liefert Unsinn.", "Nur ein Testfall mit bekanntem Ergebnis findet ihn."]),
  ("Was ist der erste Schritt beim Fehlersuchen?",
   "Die Fehlermeldung lesen, besonders die letzte Zeile",
   ["Den Code neu schreiben", "Den Rechner neu starten", "Alle Kommentare entfernen"],
   ["Die letzte Zeile sagt, was los ist.", "Die vorletzte sagt meistens, wo."]),
  ("Wie prüft man, ob eine Zahl gerade ist?",
   "zahl % 2 == 0",
   ["zahl // 2 == 0", "zahl / 2 == 0", "zahl ** 2 == 0"],
   ["Der Rest bei Division durch 2 ist 0.", "Modulo ist das Werkzeug für Teilbarkeit."]),
  ("Was macht ein Debugger?",
   "Er hält das Programm an und zeigt die Werte der Variablen",
   ["Er korrigiert Fehler automatisch", "Er übersetzt in Maschinencode", "Er entfernt Kommentare"],
   ["Schritt für Schritt durch das Programm gehen.", "Er beantwortet die Frage: warum tut es das?"]),
  ("Was fehlt in: sekunden = 5; while sekunden > 0: print(sekunden)?",
   "Die Verringerung von sekunden im Rumpf",
   ["Ein else-Zweig", "Ein Doppelpunkt hinter print", "Die Umwandlung mit int()"],
   ["Ohne Veränderung bleibt die Bedingung ewig wahr.", "Das ist die klassische Endlosschleife."]),
  ("Wie bricht man ein Programm in der Konsole ab?",
   "Mit Strg+C",
   ["Mit der Leertaste", "Mit F5", "Mit Strg+S"],
   ["Strg+C beendet den laufenden Prozess.", "Bei Endlosschleifen die Rettung."]),
 ]),
 ("modularisierung", 18, 1, "Modularisierung und Funktionen", [
  ("Wie heißt der Wert in der Definition einer Funktion?",
   "Parameter",
   ["Argument", "Rückgabewert", "Attribut"],
   ["Parameter steht in der Definition.", "Argument ist der echte Wert beim Aufruf."]),
  ("Wie heißt der Wert, der beim Aufruf übergeben wird?",
   "Argument",
   ["Parameter", "Rückgabewert", "Konstante"],
   ["Beim Aufruf mittelwert(noten) ist noten das Argument.", "Die häufigste Verwechslung in der Klausur."]),
  ("Was liefert eine Funktion ohne return zurück?",
   "None",
   ["0", "Einen leeren Text", "Einen Fehler"],
   ["Sie tut etwas, liefert aber keinen Wert.", "Deshalb print() nicht mit return verwechseln."]),
  ("Was bewirkt return in der Mitte einer Funktion?",
   "Die Funktion endet sofort, der Rest läuft nicht mehr",
   ["Es macht eine Zwischenausgabe", "Es startet die Funktion neu", "Es ist ein Syntaxfehler"],
   ["return beendet den Aufruf.", "Nützlich für Sonderfälle am Anfang."]),
  ("Was bedeutet, dass eine Variable lokal ist?",
   "Sie existiert nur während des Funktionsaufrufs",
   ["Sie gilt im ganzen Programm", "Sie kann nicht verändert werden", "Sie ist immer eine Zahl"],
   ["Außerhalb ist sie unbekannt.", "Das ist ein Vorteil: keine Namenskollisionen."]),
  ("Wie sollte eine Funktion Werte bekommen und liefern?",
   "Über Parameter hinein, über return hinaus",
   ["Über globale Variablen", "Über print und input", "Über Kommentare"],
   ["So bleibt sie eine Black Box ohne Nebenwirkungen.", "Damit ist sie einzeln testbar."]),
  ("Wie erkennt man, dass eine Funktion zu viel tut?",
   "Ihr Name enthält ein und",
   ["Sie hat einen Parameter", "Sie hat ein return", "Sie ist eingerückt"],
   ["Eine Funktion, eine Aufgabe.", "einlesen_und_auswerten sind zwei Funktionen."]),
  ("Was bewirkt def note(punkte, maximum=60)?",
   "maximum ist optional und ist 60, wenn nichts übergeben wird",
   ["maximum muss immer angegeben werden", "maximum ist eine globale Variable", "Es ist ein Syntaxfehler"],
   ["Standardwerte stehen in der Definition.", "note(47) und note(47, 50) sind beide gültig."]),
  ("Welches Symbol hat der Unterprogrammaufruf im Struktogramm?",
   "Ein Kasten mit doppelten Seitenstrichen",
   ["Ein Kasten mit Dreieck", "Eine Raute", "Ein Rahmen an der linken Seite"],
   ["DIN 66261 legt das fest.", "Der Inhalt steht in einem eigenen Struktogramm."]),
  ("Warum zerlegt man ein Programm in Funktionen?",
   "Weil jeder Teil einzeln verständlich, testbar und wiederverwendbar wird",
   ["Weil Python sonst zu langsam ist", "Weil der Compiler es verlangt", "Weil Funktionen weniger Speicher brauchen"],
   ["Teile und herrsche.", "Ein Fehler steckt dann in einer Funktion, nicht in 300 Zeilen."]),
 ]),
 ("komplexuebung", 19, 2, "Problemlösungsstrategie und Codereview", [
  ("Welche Phase folgt direkt auf die Analyse?",
   "Der Entwurf",
   ["Die Implementierung", "Der Test", "Die Dokumentation"],
   ["Problem verstehen, Analyse, Entwurf, Implementierung, Test, Dokumentation.", "Der Entwurf liefert das Struktogramm."]),
  ("Welche Phase wird am häufigsten übersprungen?",
   "Die Analyse",
   ["Die Implementierung", "Der Test", "Das Problem verstehen"],
   ["Man tippt lieber sofort los.", "Genau diese Phase spart später die meiste Zeit."]),
  ("Warum rechnet man beim Getränkeautomaten in Cent statt in Euro?",
   "Weil Kommazahlen nicht exakt gespeichert werden",
   ["Weil Cent kürzer zu tippen ist", "Weil Python keine Kommazahlen kennt", "Weil Automaten nur Cent kennen"],
   ["0.1 + 0.2 ist nicht genau 0.3.", "Mit int in Cent stimmt die Kasse."]),
  ("Wie berechnet man die Anzahl der 2-Euro-Stücke im Wechselgeld?",
   "rest // 200",
   ["rest % 200", "rest / 200", "rest ** 200"],
   ["// liefert die Anzahl ganzer Einheiten.", "% liefert danach den verbleibenden Rest."]),
  ("Wie heißt das Verfahren, immer die größte passende Münze zu nehmen?",
   "Gieriges Verfahren (greedy)",
   ["Rekursion", "Binäre Suche", "Normalisierung"],
   ["Es entscheidet in jedem Schritt lokal am besten.", "Beim Euro liefert es tatsächlich die kleinste Münzzahl."]),
  ("Warum ist ein gieriges Verfahren nicht immer optimal?",
   "Weil eine lokal beste Wahl global schlechter sein kann",
   ["Weil es zu langsam ist", "Weil es zu viel Speicher braucht", "Weil es nur mit Euro funktioniert"],
   ["Mit Münzen 1, 3, 4 ist 6 = 3 + 3 besser als 4 + 1 + 1.", "Oft richtig ist nicht bewiesen richtig."]),
  ("Was gehört in ein Testprotokoll?",
   "Testfall, erwartetes Ergebnis, beobachtetes Ergebnis",
   ["Nur die gefundenen Fehler", "Der komplette Quelltext", "Die Namen aller Teammitglieder"],
   ["Erwartet und beobachtet müssen nebeneinander stehen.", "Sonst weiß man nicht, ob es stimmt."]),
  ("Was ist die wichtigste Regel beim Codereview?",
   "Über den Code reden, nicht über die Person",
   ["Nur Fehler nennen, kein Lob", "Immer sofort selbst umschreiben", "Nichts aufschreiben"],
   ["Fragen statt urteilen.", "Als Autor zuhören, nicht verteidigen."]),
  ("Wozu dient die while-Schleife im Automatenprogramm?",
   "Sie kassiert so lange, bis genug Geld eingeworfen ist",
   ["Sie zählt die Getränkesorten", "Sie berechnet das Wechselgeld", "Sie prüft die Rechtschreibung"],
   ["Die Anzahl der Münzen ist vorher unbekannt.", "Deshalb while und nicht for."]),
  ("Was ist Rubber Duck Debugging?",
   "Den eigenen Code laut erklären, um den Fehler zu finden",
   ["Fehler mit einem Zufallsgenerator suchen", "Den Code an eine KI schicken", "Das Programm mehrfach neu starten"],
   ["Beim Erklären fällt die Lücke selbst auf.", "Ein Mitschüler tut es genauso gut wie die Ente."]),
 ]),
 ("oop1", 20, 3, "OOP I: Klasse, Objekt, Attribut, Methode", [
  ("Was ist eine Klasse?",
   "Der Bauplan, nach dem Objekte erzeugt werden",
   ["Ein einzelnes Ding mit eigenen Werten", "Eine Eigenschaft eines Objekts", "Eine Funktion ohne Parameter"],
   ["Die Klasse beschreibt, was alle Dinge dieser Art haben.", "Objekte sind die gebauten Exemplare."]),
  ("Was ist ein Objekt?",
   "Eine konkrete Instanz einer Klasse mit eigenen Werten",
   ["Der Bauplan", "Eine Methode", "Ein Datentyp wie int"],
   ["a1 = Auto('Fiat', 3) erzeugt ein Objekt.", "Jedes Objekt hat eigene Attributwerte."]),
  ("Wie heißt eine Eigenschaft eines Objekts?",
   "Attribut",
   ["Methode", "Parameter", "Instanz"],
   ["Attribute sind die Daten des Objekts.", "Methoden sind seine Fähigkeiten."]),
  ("Welche Methode läuft automatisch beim Erzeugen eines Objekts?",
   "__init__",
   ["__main__", "start()", "new()"],
   ["Der Konstruktor legt die Attribute an.", "Er wird nie direkt aufgerufen."]),
  ("Wofür steht self in einer Methode?",
   "Für das Objekt, auf dem die Methode aufgerufen wurde",
   ["Für die Klasse selbst", "Für den Rückgabewert", "Für eine globale Variable"],
   ["self unterscheidet a1 von a2.", "In Java heißt es this."]),
  ("Wie ruft man die Methode beschleunigen des Objekts a1 auf?",
   "a1.beschleunigen(50)",
   ["beschleunigen(a1, 50)", "Auto.beschleunigen(50)", "a1->beschleunigen(50)"],
   ["Punktschreibweise: Objekt, Punkt, Methode.", "Das nennt man auch eine Botschaft senden."]),
  ("Welche drei Fächer hat eine Klasse im UML-Diagramm?",
   "Name, Attribute, Methoden",
   ["Name, Objekte, Beziehungen", "Attribute, Schlüssel, Fremdschlüssel", "Eingabe, Verarbeitung, Ausgabe"],
   ["Von oben nach unten.", "Das Diagramm ist sprachunabhängig."]),
  ("Wie findet man beim Modellieren die Klassen?",
   "An den Substantiven im Aufgabentext",
   ["An den Verben", "An den Zahlen", "An den Adjektiven"],
   ["Substantive werden Klassen oder Attribute.", "Verben werden Methoden."]),
  ("Was ist der Unterschied zwischen prozeduraler und objektorientierter Sicht?",
   "OOP fasst Daten und Verhalten in einer Klasse zusammen",
   ["OOP kennt keine Schleifen", "Prozedural gibt es keine Variablen", "OOP ist immer schneller"],
   ["Prozedural liegen Daten und Funktionen getrennt.", "Objekte wissen etwas und können etwas."]),
  ("Welche Sprache gilt als erste objektorientierte Sprache?",
   "Simula 67",
   ["Python", "C", "HTML"],
   ["Entwickelt in Oslo, für Simulationen.", "Smalltalk machte die Idee 1972 populär."]),
 ]),
 ("oop2", 21, 4, "OOP II: Vererbung, Kapselung, Polymorphie", [
  ("Was bedeutet Vererbung?",
   "Eine Unterklasse übernimmt Attribute und Methoden der Oberklasse",
   ["Zwei Klassen tauschen ihre Daten", "Ein Objekt kopiert ein anderes", "Eine Methode ruft sich selbst auf"],
   ["Das Gemeinsame steht nur einmal in der Oberklasse.", "Die Unterklasse ergänzt oder überschreibt."]),
  ("Welcher Test entscheidet, ob Vererbung passt?",
   "Der ist-ein-Test",
   ["Der hat-ein-Test", "Der Grenzwerttest", "Der Modulo-Test"],
   ["Ein Schüler ist eine Person.", "Ein Auto hat einen Motor, ist aber keiner."]),
  ("Wozu dient super().__init__(...)?",
   "Es ruft den Konstruktor der Oberklasse auf",
   ["Es erzeugt ein neues Objekt", "Es löscht die Oberklasse", "Es überschreibt eine Methode"],
   ["So werden die geerbten Attribute gesetzt.", "Danach ergänzt die Unterklasse ihre eigenen."]),
  ("Was heißt Überschreiben einer Methode?",
   "Die Unterklasse definiert eine geerbte Methode neu",
   ["Die Methode wird gelöscht", "Die Methode bekommt mehr Parameter", "Die Methode wird zur Klassenmethode"],
   ["Beim Aufruf gewinnt die Fassung der Unterklasse.", "Python sucht erst unten, dann oben."]),
  ("Was bedeutet Kapselung?",
   "Daten sind geschützt und nur über Methoden zugänglich",
   ["Alle Attribute sind öffentlich", "Klassen werden ineinander verschachtelt", "Objekte werden gelöscht"],
   ["Die Methoden kennen die Regeln.", "In Python markiert ein Unterstrich das Nichtöffentliche."]),
  ("Warum ist ein direkt beschreibbares Attribut kontostand problematisch?",
   "Weil jede Prüfung im abheben() dann umgangen werden kann",
   ["Weil Python das verbietet", "Weil es zu viel Speicher braucht", "Weil es nur ganze Zahlen zulässt"],
   ["konto.kontostand = 1000000 wäre möglich.", "Die Klasse muss ihre Regeln selbst durchsetzen."]),
  ("Was bedeutet Polymorphie?",
   "Derselbe Aufruf führt je nach Objekt zu anderem Verhalten",
   ["Eine Klasse hat mehrere Konstruktoren", "Ein Objekt hat viele Attribute", "Eine Methode hat viele Parameter"],
   ["Die Schleife kennt die Klassen nicht.", "Jedes Objekt entscheidet selbst, welche Methode läuft."]),
  ("Was ist der praktische Gewinn der Polymorphie?",
   "Neue Klassen laufen mit, ohne dass bestehender Code geändert wird",
   ["Das Programm wird schneller", "Man braucht keine Schleifen mehr", "Man spart Speicher"],
   ["Erweitern ohne Ändern.", "Voraussetzung ist eine gemeinsame Schnittstelle."]),
  ("Wann lohnt sich OOP besonders?",
   "Wenn es viele gleichartige Dinge mit eigenem Zustand gibt",
   ["Bei einem 30-Zeilen-Programm", "Bei einer einzelnen Berechnung", "Wenn keine Daten gespeichert werden"],
   ["Für einen einfachen Ablauf genügen Funktionen.", "Ehrliche Einschätzung gehört zur Bewertung."]),
  ("Wie heißen die vier Säulen der OOP?",
   "Abstraktion, Kapselung, Vererbung, Polymorphie",
   ["Folge, Auswahl, Wiederholung, Sprung", "Eingabe, Verarbeitung, Ausgabe, Test", "Klasse, Objekt, Attribut, Methode"],
   ["Die vier Prinzipien, nicht die vier Grundbegriffe.", "In der Klausur: nennen, erklären, am Beispiel zeigen."]),
 ]),
 ("wiederholung2", 22, 5, "Wiederholung LB 2 und OOP", [
  ("a = 12, b = 5. Solange a >= b: a = a - b. Was steht am Ende in a?",
   "2",
   ["7", "0", "5"],
   ["12, dann 7, dann 2 - dann ist 2 < 5.", "Das Ergebnis ist 12 % 5."]),
  ("Was berechnet wiederholtes Abziehen von b von a?",
   "Den Rest der Division a durch b",
   ["Das Produkt", "Den größten gemeinsamen Teiler", "Die Summe"],
   ["Genau das macht der Modulo-Operator.", "So rechnen Prozessoren die Division tatsächlich."]),
  ("Wie heißt das Durchspielen eines Algorithmus von Hand mit Wertetabelle?",
   "Trace oder Handsimulation",
   ["Debugging", "Kompilieren", "Refactoring"],
   ["Eine Spalte je Variable, eine Zeile je Durchlauf.", "Nie im Kopf rechnen, immer aufschreiben."]),
  ("Eine Funktion beginnt mit groesste = 0 und sucht das Maximum. Welcher Fall geht schief?",
   "Wenn alle Werte negativ sind",
   ["Wenn alle Werte positiv sind", "Wenn die Liste sortiert ist", "Wenn die Liste genau ein Element hat"],
   ["Dann bleibt 0 stehen und ist falsch.", "Besser mit werte[0] starten."]),
  ("Eine Funktion gibt das Ergebnis mit print aus statt mit return. Was ist die Folge?",
   "Der Aufrufer erhält None",
   ["Das Programm stürzt ab", "Das Ergebnis wird verdoppelt", "Es ist ein Syntaxfehler"],
   ["print zeigt an, return liefert zurück.", "ergebnis = funktion() ist dann None."]),
  ("Welcher Operator prüft in Python auf Gleichheit?",
   "==",
   ["=", ":=", "!="],
   ["= weist zu, == vergleicht.", "!= prüft auf Ungleichheit."]),
  ("Was verlangt der Operator bewerten in einer Klausuraufgabe?",
   "Kriterien nennen, abwägen und begründet entscheiden",
   ["Nur Stichworte aufschreiben", "Den Quelltext abschreiben", "Eine Zeichnung anfertigen"],
   ["Bewerten liegt im Anforderungsbereich III.", "Nennen käme ohne Begründung aus."]),
  ("Welche Schleife nimmt man, wenn die Anzahl der Durchläufe unbekannt ist?",
   "while",
   ["for mit range", "for über eine Liste", "eine verschachtelte for-Schleife"],
   ["while prüft eine Bedingung.", "for zählt eine vorher bekannte Anzahl."]),
  ("Was ist beim Umschreiben von for nach while zu beachten?",
   "Die Laufvariable muss initialisiert und im Rumpf erhöht werden",
   ["Man braucht ein else", "Die Bedingung muss immer wahr sein", "Es ist nicht möglich"],
   ["Sonst entsteht eine Endlosschleife.", "Die Testfälle müssen weiter dasselbe liefern."]),
  ("Was gehört bei einer OOP-Aufgabe zum Begriff erklären dazu?",
   "Eine eigene Formulierung und ein Beispiel",
   ["Nur das Fachwort nennen", "Nur den Code hinschreiben", "Nur ein Diagramm zeichnen"],
   ["Erklären liegt im Anforderungsbereich II.", "Ohne Beispiel fehlen Punkte."]),
 ]),
 ("projekt", 23, 8, "Projekt Webtechnologie: Kickoff", [
  ("Welche Phase steht am Anfang eines Projekts?",
   "Die Planung: Team, Termine, Ressourcen, Thema",
   ["Die Implementierung", "Der Test", "Die Präsentation"],
   ["Ohne Plan verteilt sich die Arbeit von selbst - schlecht.", "Rollen und Termine werden schriftlich festgehalten."]),
  ("Was gehört in ein Projekttagebuch?",
   "Datum, Ziel, Ergebnis, Probleme, nächster Schritt",
   ["Nur der fertige Quelltext", "Nur die Namen der Teammitglieder", "Nur die Note am Ende"],
   ["Pro Stunde ein Absatz genügt.", "Es ist der Beleg für den Prozess und wird bewertet."]),
  ("Welches Kriterium spricht für ein gutes Projektthema?",
   "Es hat Daten, die sich in Tabellen fassen lassen",
   ["Es ist möglichst groß", "Es braucht echte personenbezogene Daten", "Es ist noch nie umgesetzt worden"],
   ["Ohne Daten gibt es keine Datenbankanbindung.", "Erfundene Testdaten reichen völlig."]),
  ("Warum arbeitet man im Projekt mit erfundenen Testdaten?",
   "Weil echte personenbezogene Daten dem Datenschutz unterliegen",
   ["Weil erfundene Daten schneller laden", "Weil die Datenbank sonst zu groß wird", "Weil HTML keine Namen darstellen kann"],
   ["Was nicht gespeichert wird, kann nicht verloren gehen.", "Datenminimierung ist die einfachste Schutzmaßnahme."]),
  ("Welche Rolle kümmert sich um Testfälle und Quellenliste?",
   "Qualität und Test",
   ["Projektleitung", "Design und Inhalt", "Technik und Daten"],
   ["Jede Rolle liefert ein sichtbares Ergebnis.", "Rollen bedeuten Zuständigkeit, nicht Alleinarbeit."]),
  ("Wie viele Unterrichtsstunden umfasst der Lernbereich 3A?",
   "20",
   ["10", "15", "30"],
   ["Verteilt auf die Wochen 23 bis 32.", "LB 1 und LB 2 hatten je 15 Stunden."]),
  ("Warum ist eine feste Ordnerstruktur im Team wichtig?",
   "Damit sich niemand gegenseitig Dateien überschreibt",
   ["Weil der Browser das verlangt", "Weil sonst das CSS nicht lädt", "Weil Ordner Speicher sparen"],
   ["Ein gemeinsamer Ordner, feste Dateinamen.", "Keine Versionen namens endgueltig_final_2."]),
  ("Was ist ein Meilenstein?",
   "Ein überprüfbares Zwischenergebnis zu einem festen Termin",
   ["Der letzte Tag des Projekts", "Ein besonders schwerer Fehler", "Eine Besprechung ohne Ergebnis"],
   ["Jede Woche hat ein Ergebnis.", "So merkt man rechtzeitig, wenn es klemmt."]),
  ("Wer erfand 1989 das World Wide Web?",
   "Tim Berners-Lee",
   ["Bill Gates", "Alan Turing", "Ada Lovelace"],
   ["Er arbeitete am CERN in Genf.", "Sein Chef notierte: vage, aber spannend."]),
  ("Warum gehört das Web niemandem?",
   "Weil Berners-Lee bewusst auf ein Patent verzichtete",
   ["Weil das CERN es verboten hat", "Weil es niemand entwickeln wollte", "Weil Patente damals unbekannt waren"],
   ["Die Technik wurde 1993 gemeinfrei gestellt.", "Deshalb konnte sich das Web frei ausbreiten."]),
 ]),
 ("html", 24, 9, "HTML: Elemente einer Auszeichnungssprache", [
  ("Was beschreibt HTML?",
   "Die Struktur eines Dokuments",
   ["Das Aussehen einer Seite", "Das Verhalten bei Klicks", "Die Datenbankabfragen"],
   ["HTML ist eine Auszeichnungssprache, keine Programmiersprache.", "Das Aussehen macht CSS, das Verhalten JavaScript."]),
  ("Welche Zeile muss ganz oben in jedem HTML-Dokument stehen?",
   "Der Doctype für HTML5",
   ["Das title-Element", "Das body-Element", "Die CSS-Verlinkung"],
   ["Er sagt dem Browser, welche HTML-Fassung gilt.", "Erst danach folgt das html-Element."]),
  ("Wozu dient das Attribut charset im meta-Element?",
   "Es legt den Zeichensatz fest, damit Umlaute richtig erscheinen",
   ["Es legt die Schriftart fest", "Es setzt die Sprache der Seite", "Es lädt das Stylesheet"],
   ["Ohne UTF-8 werden Umlaute zu Kauderwelsch.", "Die Sprache setzt das Attribut lang."]),
  ("Was gehört in den Kopfbereich einer Seite?",
   "Angaben über die Seite wie Titel, Zeichensatz und Stylesheet",
   ["Der sichtbare Inhalt", "Die Navigation", "Die Fußzeile"],
   ["Der Kopf ist unsichtbar, aber nicht unwichtig.", "Der sichtbare Inhalt steht im body."]),
  ("Wie viele Überschriften erster Ordnung sollte eine Seite haben?",
   "Genau eine",
   ["Beliebig viele", "Mindestens drei", "Keine"],
   ["Die h1 benennt das Thema der Seite.", "Darunter gliedern h2 und h3."]),
  ("Warum ist das Attribut alt bei einem Bild Pflicht?",
   "Damit auch Menschen ohne Bildanzeige den Inhalt erfassen",
   ["Damit das Bild schneller lädt", "Damit das Bild zentriert wird", "Damit der Browser das Format erkennt"],
   ["Screenreader lesen den alt-Text vor.", "Er beschreibt das Bild, nicht den Dateinamen."]),
  ("Wofür sind Tabellen in HTML gedacht?",
   "Für echte tabellarische Daten",
   ["Für das Seitenlayout", "Für Navigationsmenüs", "Für Bildergalerien"],
   ["Layout gehört ins CSS.", "Tabellenlayouts brechen auf dem Handy zusammen."]),
  ("Welche semantischen Elemente gliedern eine Seite?",
   "header, nav, main, footer",
   ["div, span, br, hr", "table, tr, td, th", "html, head, title, meta"],
   ["Sie sagen, welche Rolle ein Bereich hat.", "Screenreader und Suchmaschinen nutzen das."]),
  ("Was prüft der Validator des W3C?",
   "Ob das HTML den Regeln entspricht",
   ["Ob die Seite schön aussieht", "Ob die Datenbank erreichbar ist", "Ob die Ladezeit kurz ist"],
   ["Browser reparieren fehlerhaftes HTML still.", "Der Validator zeigt, was wirklich falsch ist."]),
  ("Was bedeutet die Verschachtelungsregel bei HTML-Elementen?",
   "Zuletzt geöffnet wird zuerst geschlossen",
   ["Elemente dürfen sich überkreuzen", "Endtags sind optional", "Attribute stehen im Endtag"],
   ["Sonst entsteht ein unklarer Baum.", "Der Baum heißt DOM."]),
 ]),
 ("css", 25, 10, "CSS: Trennung von Inhalt und Layout", [
  ("Warum bindet man CSS als externe Datei ein?",
   "Weil eine Änderung dann auf allen Seiten wirkt",
   ["Weil der Browser es sonst nicht lädt", "Weil interne Stile verboten sind", "Weil externe Dateien schneller sind als HTML"],
   ["Eine Datei, alle Seiten.", "So sehen alle Seiten garantiert gleich aus."]),
  ("Wie lautet der Aufbau einer CSS-Regel?",
   "Selektor, geschweifte Klammern, Eigenschaft und Wert",
   ["Eigenschaft, Selektor, Wert", "Wert, Klammer, Selektor", "Selektor, Semikolon, Klasse"],
   ["h1 { color: blue; }", "Jede Deklaration endet mit einem Semikolon."]),
  ("Welcher Selektor trifft alle Elemente mit class gleich karte?",
   ".karte",
   ["#karte", "karte", "*karte"],
   ["Der Punkt steht für eine Klasse.", "Die Raute steht für eine id."]),
  ("Worin unterscheiden sich class und id?",
   "Eine class darf mehrfach vorkommen, eine id nur einmal",
   ["Eine id darf mehrfach vorkommen", "class gilt nur für Text", "id funktioniert nur in JavaScript"],
   ["Im Projekt arbeitet man vor allem mit Klassen.", "ids eignen sich für Sprungziele."]),
  ("Welche Schicht des Box-Modells liegt ganz außen?",
   "margin",
   ["padding", "border", "content"],
   ["Von innen nach außen: content, padding, border, margin.", "Der margin ist immer durchsichtig."]),
  ("Was bewirkt box-sizing gleich border-box?",
   "Die Angabe width umfasst Inhalt, padding und border",
   ["Die Box bekommt automatisch einen Rahmen", "Der margin wird verdoppelt", "Die Box wird zentriert"],
   ["Ohne diese Angabe wird die Box breiter als gedacht.", "Deshalb setzt man es meist global."]),
  ("Was gewinnt bei gleicher Spezifität?",
   "Die später notierte Regel",
   ["Die zuerst notierte Regel", "Die kürzere Regel", "Immer die id-Regel"],
   ["Die Kaskade entscheidet.", "id schlägt Klasse, Klasse schlägt Element."]),
  ("Wozu dient eine Medienabfrage?",
   "Regeln nur für bestimmte Bildschirmbreiten gelten zu lassen",
   ["Bilder in mehreren Größen zu speichern", "Videos einzubinden", "Schriften zu laden"],
   ["max-width 700px trifft schmale Bildschirme.", "So entsteht ein responsives Layout."]),
  ("Wie viele Schriftarten sollte eine Seite höchstens verwenden?",
   "Zwei",
   ["Fünf", "Eine pro Seite", "So viele wie möglich"],
   ["Eine für Überschriften, eine für den Fließtext.", "Mehr wirkt unruhig."]),
  ("Welcher Kontrast zwischen Text und Hintergrund gilt als Mindestwert?",
   "4,5 zu 1",
   ["1,5 zu 1", "2 zu 1", "10 zu 1"],
   ["Sonst ist die Seite nicht barrierefrei.", "Es gibt Prüfwerkzeuge dafür im Browser."]),
 ]),
 ("http", 26, 11, "HTTP und dynamische Webanwendungen", [
  ("Wer stellt bei HTTP die Anfrage?",
   "Der Client, also der Browser",
   ["Der Server", "Die Datenbank", "Das Betriebssystem"],
   ["Der Server antwortet nur.", "Von sich aus schickt er nichts."]),
  ("Was bedeutet, dass HTTP zustandslos ist?",
   "Der Server erinnert sich nicht an frühere Anfragen",
   ["Der Server speichert alle Anfragen dauerhaft", "Die Verbindung bleibt immer offen", "Es gibt keine Fehlermeldungen"],
   ["Jede Anfrage steht für sich.", "Für Warenkörbe braucht es Sessions und Cookies."]),
  ("Wofür verwendet man die Methode POST?",
   "Zum Senden von Daten, etwa aus einem Formular",
   ["Zum Abholen einer Seite", "Zum Löschen einer Tabelle", "Zum Ändern der Schriftgröße"],
   ["GET holt, POST schickt.", "Passwörter niemals per GET, sie stünden in der URL."]),
  ("Was bedeutet der Statuscode 404?",
   "Nicht gefunden",
   ["Alles in Ordnung", "Zugriff verboten", "Serverfehler"],
   ["4xx sind Fehler auf Seiten des Clients.", "5xx sind Fehler des Servers."]),
  ("Was bedeutet ein Statuscode, der mit 5 beginnt?",
   "Ein Fehler auf dem Server",
   ["Alles in Ordnung", "Eine Umleitung", "Ein Fehler des Clients"],
   ["500 ist der klassische Serverfehler.", "2xx gut, 3xx umgeleitet, 4xx Client, 5xx Server."]),
  ("Welche Sprache läuft clientseitig im Browser?",
   "JavaScript",
   ["PHP", "SQL", "Python auf dem Server"],
   ["Der Nutzer sieht den Quelltext.", "Serverseitig laufen PHP, Python oder Java."]),
  ("Warum genügt eine Prüfung der Eingabe im Browser nicht?",
   "Weil der Client alles verändern kann, was er sieht",
   ["Weil JavaScript zu langsam ist", "Weil der Browser keine Zahlen prüfen kann", "Weil HTML keine Formulare kennt"],
   ["Die echte Prüfung passiert auf dem Server.", "Browserprüfung ist reiner Komfort."]),
  ("Was sieht der Browser von serverseitigem PHP-Code?",
   "Nur das erzeugte HTML",
   ["Den kompletten PHP-Quelltext", "Die Datenbankstruktur", "Das Serverpasswort"],
   ["PHP läuft und verschwindet.", "Deshalb dürfen Geheimnisse nur serverseitig liegen."]),
  ("In welchem Reiter der Entwicklertools sieht man Anfragen und Statuscodes?",
   "Netzwerk",
   ["Elemente", "Konsole", "Anwendung"],
   ["Vorher die Seite neu laden.", "Jede Anfrage zeigt Methode, Status und Größe."]),
  ("Wofür steht HTTPS?",
   "Für eine verschlüsselte HTTP-Verbindung",
   ["Für einen schnelleren Server", "Für eine Seite mit Datenbank", "Für ein besonderes Dateiformat"],
   ["Es schützt gegen Mitlesen und Verändern.", "Heute ist es der Standard."]),
 ]),
 ("dbanbindung", 27, 12, "Datenbankanbindung planen", [
  ("Womit beginnt die Planung der Datenbankanbindung?",
   "Mit dem ER-Modell des Projektthemas",
   ["Mit dem Schreiben der PHP-Seiten", "Mit der Wahl der Schriftart", "Mit dem Hochladen auf den Server"],
   ["Erst modellieren, dann überführen, dann anbinden.", "Ein Modellfehler kostet später das Zehnfache."]),
  ("Was wird bei der Überführung aus einer 1:n-Beziehung?",
   "Ein Fremdschlüssel in der Tabelle auf der n-Seite",
   ["Eine eigene Tabelle", "Ein zusammengesetzter Primärschlüssel", "Ein neues Attribut in beiden Tabellen"],
   ["Der Fremdschlüssel zeigt auf die 1-Seite.", "Eine eigene Tabelle braucht nur n:m."]),
  ("Was wird bei der Überführung aus einer n:m-Beziehung?",
   "Eine eigene Tabelle mit zwei Fremdschlüsseln",
   ["Ein Fremdschlüssel in einer der beiden Tabellen", "Gar nichts", "Ein zusätzliches Attribut"],
   ["Die neue Tabelle trägt beide Schlüssel.", "Beziehungsattribute finden nur dort Platz."]),
  ("Wo gehört ein Beziehungsattribut wie Menge hin?",
   "In die Tabelle, die aus der n:m-Beziehung entstanden ist",
   ["In beide beteiligten Tabellen", "In eine der beiden Tabellen", "In keine Tabelle"],
   ["Es gehört zum Paar, nicht zu einem der beiden Dinge.", "Sonst entsteht Redundanz."]),
  ("Welche SQL-Anweisung legt eine Tabelle an?",
   "CREATE TABLE",
   ["INSERT INTO", "SELECT", "UPDATE"],
   ["Erst die Struktur, dann die Daten.", "INSERT trägt einzelne Datensätze ein."]),
  ("Wozu dient ein JOIN?",
   "Er verbindet Tabellen über ihre Schlüssel",
   ["Er löscht doppelte Zeilen", "Er sortiert das Ergebnis", "Er legt eine neue Tabelle an"],
   ["Er setzt zusammen, was die Normalisierung getrennt hat.", "Verbunden wird über Fremd- und Primärschlüssel."]),
  ("Warum benutzt man in einer Abfrage einen Platzhalter statt des Wertes?",
   "Damit Nutzereingaben nie Teil des SQL-Befehls werden",
   ["Weil die Abfrage sonst zu lang wird", "Weil SQL keine Texte kennt", "Weil das schneller lädt"],
   ["Das ist der Schutz gegen SQL-Injection.", "Der Befehl steht fest, bevor der Wert eintrifft."]),
  ("Was gehört in den Anbindungsplan?",
   "Je Seite: was sie zeigt, welche Tabellen und welche Abfrage",
   ["Nur die Namen der Teammitglieder", "Der komplette HTML-Quelltext", "Die Farbpalette"],
   ["Er sagt genau, was zu programmieren ist.", "Er ist das Planungsergebnis der Woche."]),
  ("Warum speichert man berechenbare Werte wie eine Summe besser nicht?",
   "Weil sie sonst bei jeder Änderung nachgepflegt werden müssten",
   ["Weil SQL nicht rechnen kann", "Weil Zahlen zu viel Speicher brauchen", "Weil das verboten ist"],
   ["Redundanz führt zu Anomalien.", "Berechnen ist billiger als konsistent halten."]),
  ("Welches Ergebnis liefert diese Woche die Dokumentation?",
   "Problemanalyse, Datenmodell, Schema und Anbindungsplan",
   ["Nur ein Screenshot der Startseite", "Nur die Farbpalette", "Nur die Aufgabenliste"],
   ["Diese Teile werden im Bereich Prozess bewertet.", "In Fachsprache formuliert."]),
 ]),
 ("umsetzung1", 28, 14, "Umsetzung I: Implementierung", [
  ("Welcher Meilenstein gilt für diese Woche?",
   "Mindestens eine Seite zeigt echte Datensätze aus der Datenbank",
   ["Das Projekt ist vollständig fertig", "Die Präsentation ist geprobt", "Die Farbpalette steht fest"],
   ["Erst wenn ein Weg durchläuft, ist der Rest Fleiß.", "Fachbegriff: Walking Skeleton."]),
  ("Wie heißt die Einstiegsdatei einer Website üblicherweise?",
   "index.html",
   ["start.html", "home.php", "main.htm"],
   ["Server liefern sie automatisch aus.", "Sie liegt ganz oben im Projektordner."]),
  ("Warum sollten Dateinamen klein und ohne Umlaute sein?",
   "Weil Server bei Groß- und Kleinschreibung strenger sind als Windows",
   ["Weil der Browser sonst abstürzt", "Weil HTML keine Großbuchstaben kennt", "Weil das schneller lädt"],
   ["Lokal geht es, auf dem Server nicht mehr.", "Auch Leerzeichen vermeiden."]),
  ("Wozu lagert man Kopf und Fuß in eigene Dateien aus?",
   "Damit die Navigation nur einmal gepflegt werden muss",
   ["Damit die Seiten schneller laden", "Weil HTML das verlangt", "Damit CSS überflüssig wird"],
   ["Dasselbe Prinzip wie eine gemeinsame CSS-Datei.", "Eine Änderung wirkt auf allen Seiten."]),
  ("Welche Methode gehört zu einem Formular, das Daten speichert?",
   "post",
   ["get", "put", "head"],
   ["GET holt, POST schickt.", "Bei GET stünden die Werte in der URL."]),
  ("Wozu dient htmlspecialchars bei der Ausgabe?",
   "Es macht Sonderzeichen unschädlich, statt sie ausführen zu lassen",
   ["Es kürzt zu langen Text", "Es übersetzt Umlaute", "Es sortiert die Ausgabe"],
   ["Schutz gegen Cross-Site-Scripting.", "Aus einer spitzen Klammer wird eine Zeichenfolge."]),
  ("Die Seite bleibt weiß und zeigt nichts. Was prüft man zuerst?",
   "Ob eine Fehlermeldung unterdrückt wird",
   ["Ob der Monitor an ist", "Ob die Schriftfarbe stimmt", "Ob das Bild zu groß ist"],
   ["Fehlermeldungen einschalten oder ins Log sehen.", "Eine weiße Seite ist fast immer ein Serverfehler."]),
  ("Der PHP-Code erscheint im Browser als Text. Woran liegt es?",
   "Die Datei heißt .html oder wird nicht über den Server aufgerufen",
   ["Der Browser ist zu alt", "Das CSS fehlt", "Die Datenbank ist leer"],
   ["PHP läuft nur auf dem Server.", "Die Datei muss auf .php enden."]),
  ("Was bedeutet die Meldung no such table?",
   "Die Datenbankdatei oder die Tabelle wird nicht gefunden",
   ["Das Passwort ist falsch", "Die Tabelle ist leer", "Die Abfrage ist zu lang"],
   ["Meist stimmt der relative Pfad nicht.", "Erst die Abfrage im DBMS testen."]),
  ("Wann gilt eine Aufgabe im Projekt als erledigt?",
   "Wenn sie läuft, getestet, sauber, im Teamordner und dokumentiert ist",
   ["Wenn sie auf einem Rechner läuft", "Wenn der Code geschrieben ist", "Wenn niemand mehr fragt"],
   ["Das ist die Definition of Done.", "Bei mir lief es ist keine Abgabe."]),
 ]),
 ("test", 29, 15, "Umsetzung II und systematischer Test", [
  ("Welche Testart deckt die meisten Fehler auf?",
   "Der Grenzwerttest",
   ["Der Darstellungstest", "Der Navigationstest", "Der Ladezeittest"],
   ["Fehler sitzen an den Rändern.", "Direkt darunter, genau darauf, direkt darüber."]),
  ("Welche Spalten gehören mindestens in ein Testprotokoll?",
   "Testfall, erwartet, beobachtet, Status",
   ["Nur der Testfall", "Nur der Status", "Nur die Fehlerbeschreibung"],
   ["Erwartet und beobachtet müssen nebeneinander stehen.", "Ausgefüllt wird beim Testen, nicht danach."]),
  ("Warum sollte ein anderes Teammitglied den Code testen?",
   "Weil der Autor seine eigenen Lücken nicht sieht",
   ["Weil das schneller geht", "Weil der Autor keine Rechte hat", "Weil das der Lehrplan verlangt"],
   ["Fremde Augen finden andere Fälle.", "Beim Hallway Testing findet man 80 Prozent der Bedienprobleme."]),
  ("Welcher Fall wird beim Testen fast immer vergessen?",
   "Die leere Datenbank beim ersten Besuch",
   ["Der normale Ablauf", "Die Startseite", "Der Seitentitel"],
   ["Eine leere Ergebnisliste braucht einen Hinweistext.", "Sonst sieht der Nutzer eine leere Seite."]),
  ("Was ist der erste Schritt bei einem gemeldeten Fehler?",
   "Ihn selbst nachstellen",
   ["Sofort den Code ändern", "Das Testprotokoll löschen", "Den Server neu starten"],
   ["Was man nicht nachstellen kann, kann man nicht beheben.", "Danach eingrenzen und die Ursache benennen."]),
  ("Warum ändert man beim Beheben nur eine Sache auf einmal?",
   "Weil man sonst nicht weiß, welche Änderung gewirkt hat",
   ["Weil der Editor nur eine Änderung erlaubt", "Weil das Zeit spart", "Weil PHP das verlangt"],
   ["Nach der Änderung erneut testen.", "Auch die Nachbarfälle prüfen."]),
  ("Was bedeutet Dijkstras Satz zum Testen?",
   "Testen zeigt Fehler, beweist aber nie deren Abwesenheit",
   ["Testen findet alle Fehler", "Testen ist überflüssig", "Nur der Compiler findet Fehler"],
   ["Gesagt 1969.", "Deshalb testet man gezielt statt zufällig."]),
  ("Wie prüft man ein responsives Layout?",
   "Mit der Geräteansicht in den Entwicklertools",
   ["Durch Ausdrucken der Seite", "Durch Löschen des CSS", "Durch Vergrößern der Schriftart"],
   ["F12, dann Geräteansicht einschalten.", "Zusätzlich in einem zweiten Browser prüfen."]),
  ("Was ist die wichtigste Regel beim Feedback geben?",
   "Beschreiben statt bewerten",
   ["Nur Positives sagen", "Nur Fehler nennen", "Möglichst allgemein bleiben"],
   ["Ich habe den Knopf nicht gefunden statt unübersichtlich.", "Konkret: Seite, Klick, Erwartung, Beobachtung."]),
  ("Was tut der Empfänger einer Rückmeldung?",
   "Zuhören und mitschreiben",
   ["Sofort widersprechen", "Alles erklären", "Die Kritik zurückgeben"],
   ["Erklären kann man später auch niemandem.", "Danach entscheidet das Team, was es übernimmt."]),
 ]),
 ("sicherheit", 30, 16, "Datensicherheit und Datenschutz", [
  ("Was ist der Unterschied zwischen Datenschutz und Datensicherheit?",
   "Datenschutz schützt die Person, Datensicherheit die Daten",
   ["Beide bedeuten dasselbe", "Datenschutz ist Technik, Datensicherheit ist Recht", "Datenschutz gilt nur für Firmen"],
   ["Darf ich die Daten haben - gegenüber - sind sie geschützt.", "Man braucht beides."]),
  ("Was besagt der Grundsatz der Datenminimierung?",
   "Nur erheben, was für den Zweck wirklich nötig ist",
   ["Daten möglichst klein komprimieren", "Alle Daten verschlüsseln", "Daten nur einmal im Jahr speichern"],
   ["Was nicht gespeichert wird, kann nicht gestohlen werden.", "Die wirksamste Sicherheitsmaßnahme überhaupt."]),
  ("Wie verhindert man SQL-Injection?",
   "Mit vorbereiteten Anweisungen und Platzhaltern",
   ["Mit längeren Passwörtern", "Mit einem anderen Browser", "Mit HTTPS allein"],
   ["Der Befehl steht fest, bevor der Wert eintrifft.", "Nutzertext wird nie Teil des SQL-Befehls."]),
  ("Was passiert bei einer erfolgreichen SQL-Injection?",
   "Fremder SQL-Code wird von der Datenbank ausgeführt",
   ["Die Seite lädt langsamer", "Das CSS wird verändert", "Der Browser stürzt ab"],
   ["Eingaben wie x' OR '1'='1 liefern alle Datensätze.", "Im schlimmsten Fall wird eine Tabelle gelöscht."]),
  ("Wogegen schützt htmlspecialchars?",
   "Gegen Cross-Site-Scripting",
   ["Gegen SQL-Injection", "Gegen zu lange Passwörter", "Gegen Serverausfälle"],
   ["Es entschärft Sonderzeichen in der Ausgabe.", "Gegen SQL-Injection hilft nur prepare."]),
  ("Wie speichert man Passwörter richtig?",
   "Nur als Hash, erzeugt mit einer geprüften Funktion",
   ["Verschlüsselt mit einem eigenen Verfahren", "Im Klartext, aber in einer eigenen Tabelle", "Als Kommentar im Quelltext"],
   ["Ein Hash lässt sich nicht zurückrechnen.", "Beim Anmelden wird nur verglichen."]),
  ("Warum bekommt jedes Passwort einen zufälligen Zusatzwert (Salt)?",
   "Damit gleiche Passwörter verschiedene Hashes ergeben",
   ["Damit der Hash kürzer wird", "Damit das Passwort entschlüsselt werden kann", "Damit es schneller geht"],
   ["Sonst verrät ein gleicher Hash gleiche Passwörter.", "password_hash erledigt das automatisch."]),
  ("Warum darf die Datenbankdatei nicht über die URL erreichbar sein?",
   "Weil sie sonst heruntergeladen werden könnte",
   ["Weil sie sonst zu groß wird", "Weil der Browser sie löscht", "Weil SQLite das verbietet"],
   ["Bei SQLite ist die Datenbank eine einzelne Datei.", "Sie gehört außerhalb des Webordners."]),
  ("Wozu dient ein Datenschutzhinweis auf der Seite?",
   "Er macht transparent, welche Daten wozu gespeichert werden",
   ["Er ersetzt die Verschlüsselung", "Er beschleunigt die Seite", "Er ist nur für Onlineshops nötig"],
   ["Transparenz ist ein Grundsatz der DSGVO.", "Er gehört auch in ein Schulprojekt."]),
  ("Seit wann gilt die DSGVO?",
   "Seit Mai 2018",
   ["Seit 2005", "Seit 2012", "Seit 2021"],
   ["Sie gilt europaweit.", "Verstöße können sehr teuer werden."]),
 ]),
 ("dokumentation", 31, 17, "Fertigstellung und Dokumentation", [
  ("Was bedeutet Funktionsstopp in der letzten Projektwoche?",
   "Es werden keine neuen Funktionen mehr gebaut, nur noch repariert",
   ["Das Projekt wird abgebrochen", "Alle Tests entfallen", "Die Dokumentation wird gestrichen"],
   ["Wer kurz vor Schluss anbaut, hat eine Baustelle.", "Neue Ideen kommen auf eine eigene Liste."]),
  ("Welches Kapitel der Dokumentation wird am häufigsten unterschätzt?",
   "Die Auswertung mit kritischer Würdigung",
   ["Das Inhaltsverzeichnis", "Die Quellenliste", "Der Titel"],
   ["Ehrliche Auswertung bringt mehr Punkte als Schönfärberei.", "Eine benannte Schwäche ist ein Kompetenznachweis."]),
  ("Was gehört zu einer vollständigen Quellenangabe?",
   "Urheber, Titel, URL, Abrufdatum und Lizenz",
   ["Nur die URL", "Nur der Name der Website", "Nur das Datum"],
   ["Bilder und Codeschnipsel gehören dazu.", "Auch die Nutzung von KI-Werkzeugen wird angegeben."]),
  ("Wie unterscheidet sich Dokumentation von einer Bedienungsanleitung?",
   "Sie begründet Entscheidungen, statt nur Schritte zu beschreiben",
   ["Sie ist kürzer", "Sie enthält keine Bilder", "Sie wird nicht bewertet"],
   ["Der Code sagt wie, der Text sagt warum.", "Jede Entscheidung braucht eine Begründung."]),
  ("Wie lang sollte die Live-Demo in der Präsentation etwa sein?",
   "Etwa vier Minuten",
   ["Eine halbe Minute", "Zehn Minuten", "So lange wie nötig"],
   ["Die Demo ist das Herzstück, aber nicht alles.", "Insgesamt sind zwölf Minuten vorgesehen."]),
  ("Warum zeigt man in der Demo auch einen Fehlerfall?",
   "Weil abgewiesene Falscheingaben Qualität beweisen",
   ["Weil es die Zeit füllt", "Weil sonst Punkte abgezogen werden", "Weil der Browser das verlangt"],
   ["Eine ungültige Eingabe muss abgelehnt werden.", "Das beeindruckt mehr als ein glatter Ablauf."]),
  ("Was ist der Plan B für eine Live-Demo?",
   "Screenshots oder eine Bildschirmaufnahme lokal auf dem Gerät",
   ["Die Demo weglassen", "Die Demo improvisieren", "Auf ein anderes Team warten"],
   ["Technik fällt genau dann aus, wenn es zählt.", "Alles auf dem Gerät, nicht nur in der Cloud."]),
  ("Was macht man bei einer Generalprobe?",
   "Den Vortrag komplett mit Uhr halten, ohne zu unterbrechen",
   ["Nur die Folien durchblättern", "Nur die Technik prüfen", "Den Text auswendig lernen"],
   ["Das Partnerteam schreibt mit.", "Danach höchstens drei Verbesserungen festlegen."]),
  ("Was tut man, wenn die Zeit im Vortrag nicht reicht?",
   "Kürzen",
   ["Schneller sprechen", "Folien überspringen und trotzdem alles sagen", "Überziehen"],
   ["Schnelles Sprechen macht es unverständlich.", "Kürzen ist eine bewertete Kompetenz."]),
  ("Was ist der häufigste Kritikpunkt bei Vorträgen?",
   "Folien werden vorgelesen",
   ["Zu wenige Folien", "Zu viel Blickkontakt", "Zu leise Musik"],
   ["Folien sind Stütze, nicht Manuskript.", "Frei sprechen wird bewertet."]),
 ]),
 ("praesentation", 32, 18, "Projektabschluss und kritische Würdigung", [
  ("Wie viele Punkte entfallen im Kriterienraster auf den Prozess?",
   "30 von 100",
   ["10 von 100", "50 von 100", "70 von 100"],
   ["Produkt 40, Prozess 30, Präsentation 30.", "Deshalb wird von Anfang an dokumentiert."]),
  ("Was ist der Zweck einer Selbsteinschätzung?",
   "Das eigene Ergebnis nach Kriterien bewerten zu üben",
   ["Die Note auszuhandeln", "Die Lehrkraft zu entlasten", "Fehler zu verstecken"],
   ["Der Lehrplan verlangt sich positionieren.", "Verglichen wird anschließend gemeinsam."]),
  ("Was gehört zu einer kritischen Würdigung des eigenen Projekts?",
   "Benennen, was gut lief, was nicht und was offen blieb",
   ["Nur die Stärken aufzählen", "Nur die Fehler der anderen nennen", "Auf die Note warten"],
   ["Drei Sätze: können wir jetzt, würden wir anders, blieb offen.", "Ehrlichkeit bringt Punkte."]),
  ("Welche Frage gehört zur gesellschaftlichen Bewertung einer Anwendung?",
   "Wem nützt sie und wem könnte sie schaden?",
   ["Wie schnell lädt sie?", "Welche Schriftart wurde benutzt?", "Wie viele Zeilen Code sind es?"],
   ["Technik ist nie neutral.", "Auch Nachhaltigkeit gehört dazu."]),
  ("Was besagt Brooks' Gesetz?",
   "Mehr Leute auf ein verspätetes Projekt machen es noch später",
   ["Doppelt so viele Leute sind doppelt so schnell", "Jedes Projekt dauert genau ein Jahr", "Code wird mit der Zeit schneller"],
   ["Einarbeitung und Absprachen kosten Zeit.", "Aus The Mythical Man-Month, 1975."]),
  ("Was ist laut Untersuchungen der wichtigste Erfolgsfaktor in IT-Projekten?",
   "Die Kommunikation im Team",
   ["Die verwendete Programmiersprache", "Die Rechenleistung", "Die Anzahl der Codezeilen"],
   ["Technik ist selten das Problem.", "Der Standish-Report untersucht das seit 1994."]),
  ("Welche Kompetenz aus LB 1 taucht im Projekt wieder auf?",
   "Modellieren mit ER-Modell und Normalformen",
   ["Struktogramme zeichnen", "Klassen ableiten", "Folien gestalten"],
   ["Das Datenmodell des Projekts stammt aus LB 1.", "LB 2 lieferte die Algorithmen."]),
  ("Was zeigt der rote Faden aller vier Lernbereiche?",
   "Modellieren, umsetzen, testen, bewerten",
   ["Programmieren, kopieren, abgeben", "Lesen, schreiben, rechnen", "Planen, warten, hoffen"],
   ["In jedem Lernbereich dieselbe Abfolge.", "Das Projekt hat sie zusammengeführt."]),
  ("Wie viele Minuten dauert die Präsentation je Team?",
   "Zwölf",
   ["Fünf", "Zwanzig", "Dreißig"],
   ["Danach fünf Minuten Nachfragen.", "Alle im Team sprechen."]),
  ("Wann ist ein Projekt nach Saint-Exupéry fertig?",
   "Wenn nichts mehr wegzulassen ist",
   ["Wenn nichts mehr hinzuzufügen ist", "Wenn die Zeit abgelaufen ist", "Wenn alle Ideen umgesetzt sind"],
   ["Vollkommenheit entsteht durch Weglassen.", "Deshalb der Funktionsstopp vor der Abgabe."]),
 ]),
]

if __name__ == "__main__":
    for slug, nr, kw, topic, qs in QUIZZES:
        path, sol = build(slug, nr, kw, topic, qs)
        print(os.path.basename(path), "Lösungen:", "".join("ABCD"[s] for s in sol))
