/**
 * labs-search.js — central hub search (index.html, tools.html)
 *
 * Two things the old inline filters could not do:
 *  1. Umlaut-blind matching — "Würfel" and "wuerfel" are the same word, so the
 *     Körper lab is found either way (ä→ae, ö→oe, ü→ue, ß→ss, accents dropped).
 *  2. Deep terms — every lab is searched by the words that live *inside* it
 *     (js/labs-terms.js, generated by tools/build-labs-terms.mjs), not just by
 *     its title, description and keywords.
 *
 * It also renders the hit list under the search line (`.search-drop`), the same
 * idea as the shape search inside koerper.html: the matching terms, each with
 * the lab it belongs to, click to jump straight there.
 */
const LabSearch = (() => {
    'use strict';

    const UMLAUT = { 'ä': 'ae', 'ö': 'oe', 'ü': 'ue', 'ß': 'ss', 'æ': 'ae', 'œ': 'oe', 'å': 'aa' };
    const MAX_HITS = 14;

    /**
     * Folds a string into its comparable form: lower case, umlauts spelled out,
     * remaining accents dropped. "Fußball" and "Fussball", "Würfel" and
     * "wuerfel", "Asunción" and "Asuncion" all land on the same key.
     */
    function fold(value) {
        return String(value == null ? '' : value)
            .normalize('NFC')            // macOS hands out decomposed umlauts too
            .toLowerCase()
            .replace(/[äöüßæœå]/g, ch => UMLAUT[ch])
            .normalize('NFD')
            .replace(/[\u0300-\u036f]/g, '');
    }

    /**
     * Same folding, but per character, so a match in the folded string can be
     * mapped back onto the original: `at[i]` is where folded character `i`
     * started in `value` ("Würfel" folds to "wuerfel", 7 chars over 6).
     */
    function foldMap(value) {
        const src = String(value == null ? '' : value).normalize('NFC');
        let folded = '';
        const at = [];
        for (let i = 0; i < src.length; i++) {
            const piece = fold(src[i]);
            for (let k = 0; k < piece.length; k++) at.push(i);
            folded += piece;
        }
        at.push(src.length);
        return { src, folded, at };
    }

    /** Query split into words — every word has to match somewhere (AND). */
    function tokens(query) {
        return fold(query).split(/\s+/).filter(Boolean);
    }

    const labs = () => (typeof LABS_DATA !== 'undefined' ? LABS_DATA : []);
    const termsOf = id => (typeof LABS_TERMS !== 'undefined' && LABS_TERMS[id]) || [];

    const loc = (key, fallback) =>
        (typeof CyberI18n !== 'undefined' && typeof CyberI18n.getOr === 'function')
            ? CyberI18n.getOr(key, fallback)
            : fallback;

    const labTitle = lab => loc('index.labs.' + lab.id + '.title', lab.title || lab.id);
    const labDesc = lab => loc('index.labs.' + lab.id + '.description', lab.description || '');

    // Haystacks are rebuilt when the display language changes.
    let hayCache = new Map();
    let hayLang = null;

    function currentLang() {
        return (typeof CyberI18n !== 'undefined' && CyberI18n.current) || '';
    }

    /** Everything about one lab, folded into a single searchable string. */
    function haystack(lab) {
        if (hayLang !== currentLang()) {
            hayCache = new Map();
            hayLang = currentLang();
        }
        let h = hayCache.get(lab.id);
        if (h === undefined) {
            // Padded, so whole-word probes like " uni " also hit at the edges.
            h = ' ' + fold([
                lab.id, lab.title, labTitle(lab), lab.tagline,
                lab.description, labDesc(lab),
                lab.keywords, lab.category,
                termsOf(lab.id).join(' ')
            ].filter(Boolean).join(' ')) + ' ';
            hayCache.set(lab.id, h);
        }
        return h;
    }

    /** Does this lab match the query? "university" still finds the `uni` tag. */
    function matchesLab(lab, query) {
        const toks = tokens(query);
        if (!toks.length) return true;
        const h = haystack(lab);
        return toks.every(t => h.includes(t) || (t === 'university' && h.includes(' uni ')));
    }

    /** Ids of all matching labs — for filtering already-rendered cards. */
    function matchingIds(query) {
        const ids = new Set();
        for (const lab of labs()) if (matchesLab(lab, query)) ids.add(lab.id);
        return ids;
    }

    function href(lab) {
        if (/^https?:\/\//i.test(lab.href)) return lab.href;
        return (typeof CyberI18n !== 'undefined' && typeof CyberI18n.appendLangToRelativeHref === 'function')
            ? CyberI18n.appendLangToRelativeHref(lab.href)
            : lab.href;
    }

    const WORD_BREAK = /[\s\-–—·,.(\[\/]/;

    /**
     * Where the query sits inside a term decides its place in the list:
     * "Kugel" before "Kuboktaeder" before "Batman-Kurve" before
     * "Schmetterlingskurve" — start of the term, start of a word, anywhere.
     */
    function position(folded, token) {
        const at = folded.indexOf(token);
        return {
            prefix: at === 0 ? 0 : 1,
            wordStart: (at === 0 || (at > 0 && WORD_BREAK.test(folded[at - 1]))) ? 0 : 1,
            pos: at < 0 ? 1e6 : at
        };
    }

    /**
     * The terms that contain the query, best first: terms beginning with it,
     * then terms with it at a word start, and inside each group the lab itself
     * ahead of its inner terms, shortest first.
     */
    function termHits(query, limit = MAX_HITS) {
        const toks = tokens(query);
        if (!toks.length) return [];
        const first = toks[0];
        const hits = [];

        for (const lab of labs()) {
            const title = labTitle(lab);
            const fTitle = fold(title);
            if (toks.every(t => fTitle.includes(t) || fold(lab.id).includes(t))) {
                hits.push({ lab, term: title, note: lab.tagline || '', rank: 0, ...position(fTitle, first) });
            }
            for (const term of termsOf(lab.id)) {
                const f = fold(term);
                if (!toks.every(t => f.includes(t))) continue;
                if (f === fTitle) continue;                      // already listed as the lab itself
                hits.push({ lab, term, note: title, rank: 1, ...position(f, first) });
            }
        }

        hits.sort((a, b) =>
            a.prefix - b.prefix ||
            a.wordStart - b.wordStart ||
            a.rank - b.rank ||
            a.pos - b.pos ||
            a.term.length - b.term.length ||
            a.term.localeCompare(b.term, hayLang || 'de'));

        return hits.slice(0, limit);
    }

    /** Wraps the matched part of a term in <mark>, umlauts included. */
    function highlight(term, query) {
        const toks = tokens(query);
        if (!toks.length) return escapeHtml(term);
        const m = foldMap(term);
        const hit = m.folded.indexOf(toks[0]);
        if (hit < 0) return escapeHtml(term);
        const from = m.at[hit];
        const to = m.at[Math.min(hit + toks[0].length, m.at.length - 1)];
        return escapeHtml(m.src.slice(0, from)) +
            '<mark>' + escapeHtml(m.src.slice(from, to)) + '</mark>' +
            escapeHtml(m.src.slice(to));
    }

    function escapeHtml(s) {
        return String(s).replace(/[&<>"']/g, c =>
            ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
    }

    /**
     * Mounts the shared lab-scan input plus the hit drop-down underneath it.
     *
     * @param {string} mountId   container id (#search-mount)
     * @param {string} placeholder
     * @param {function(string)} onInput  card filtering of the calling page
     */
    function attach(mountId, placeholder, onInput) {
        if (typeof CyberUI === 'undefined' || typeof CyberUI.createSearch !== 'function') return;
        let drop = null;
        CyberUI.createSearch(mountId, placeholder, value => {
            onInput(value);
            if (drop) renderDrop(value);
        });

        const mount = document.getElementById(mountId);
        const box = mount && mount.querySelector('.search-container');
        const input = mount && mount.querySelector('.search-input');
        if (!box || !input) return;

        drop = document.createElement('div');
        drop.className = 'search-drop';
        drop.setAttribute('role', 'listbox');
        box.appendChild(drop);

        // The surrounding row must out-stack the tiles below while the list is open.
        const row = mount.closest('.search-scan-row') || mount.parentElement;
        const setOpen = open => {
            drop.classList.toggle('open', open);
            if (row) row.classList.toggle('search-drop-open', open);
        };
        const close = () => { setOpen(false); drop.innerHTML = ''; };

        function renderDrop(value) {
            const q = value.trim();
            if (q.length < 2) return close();
            const hits = termHits(q);
            if (!hits.length) {
                const none = loc('index.ui.search_no_terms', 'nichts gefunden');
                drop.innerHTML = `<div class="search-drop-empty">${escapeHtml(none)}</div>`;
                setOpen(true);
                return;
            }
            drop.innerHTML = hits.map(h => {
                const ext = /^https?:\/\//i.test(h.lab.href);
                const attrs = ext ? ' target="_blank" rel="noopener noreferrer"' : '';
                return `<a class="search-drop-row" role="option" href="${escapeHtml(href(h.lab))}"${attrs}>` +
                    `<span class="search-drop-term">${highlight(h.term, q)}</span>` +
                    `<span class="search-drop-lab">${escapeHtml(h.note)}</span></a>`;
            }).join('');
            setOpen(true);
        }

        // Keyboard: ↓/↑ walk the list, Enter follows, Esc closes.
        input.addEventListener('keydown', e => {
            const rows = [...drop.querySelectorAll('.search-drop-row')];
            if (e.key === 'Escape') { close(); input.blur(); return; }
            if (!rows.length) return;
            const at = rows.findIndex(r => r.classList.contains('active'));
            if (e.key === 'ArrowDown' || e.key === 'ArrowUp') {
                e.preventDefault();
                const next = e.key === 'ArrowDown'
                    ? (at + 1) % rows.length
                    : (at <= 0 ? rows.length - 1 : at - 1);
                rows.forEach(r => r.classList.remove('active'));
                rows[next].classList.add('active');
                rows[next].scrollIntoView({ block: 'nearest' });
            } else if (e.key === 'Enter') {
                const pick = at >= 0 ? rows[at] : rows[0];
                if (pick) { e.preventDefault(); pick.click(); }
            }
        });

        input.addEventListener('focus', () => renderDrop(input.value));
        document.addEventListener('click', e => { if (!e.target.closest('#' + mountId)) close(); });
    }

    return { fold, tokens, matchesLab, matchingIds, termHits, attach };
})();

if (typeof module !== 'undefined' && module.exports) module.exports = { LabSearch };
